### ISSUE TITLE
[BUG] Docker cannot be killed with ^C

### ISSUE THREAD

**Issue by ivokwee** [ThinkR-open/golem#1001]
**Describe the bug**
Docker cannot be killed with ^C when run with 'docker run -p 80:80 example1:latest' as in the README of deployment folder..

**To Reproduce**
1.  Make docker files with golem::add_dockerfile_with_renv()
2. Build dockers and run with 'docker run -p 80:80 example1:latest'

**Expected behavior**

**Solution**
Run with -it flag  'docker run -it -p 80:80 example1:latest'

**Comment by VincentGuyader** [comment]
i'm on it

**Comment by ColinFay** [comment]
@VincentGuyader there was a PR already by @ivokwee :) 

It's now merged to dev via #1002
