### ISSUE TITLE
As a dev, I want to create template files for R6 classes [FR]

### ISSUE THREAD

**Issue by ilyaZar** [ThinkR-open/golem#1008]
**Quick helper in the spirit of add_XXX**
Create R6 boilerplate in  a new file 

**Describe the solution you'd like**
`add_r6()` with same interface as `add_fct()` and `add_utils`

`R6` comes with shiny and is thus already a dependency for golem, so the feature does not need "real" additional dependencies. 

The overall usefulness though is difficult to asses for me, it would certainly be beneficial when creating R6 classes for exchanging data between modules.

**Comment by D3SL** [comment]
Sounds like [TidyModules](https://github.com/Novartis/tidymodules)

**Comment by ilyaZar** [comment]
Well I think tidymodules is more of a framework that suggests a pecific style for usining R6 and (adjusted) modules when developing shiny apps.

Sometimes using basic R6 classes (without a fully fledged framework) can have merit on its own. For example, this is suggested in https://engineering-shiny.org/common-app-caveats.html?q=r6#using-r6-as-data-storage and https://youtu.be/fo4eiwGE6bw as a usedul development pattern in some cases.

Thus, this FR only asks for a quick boilerplate generator in the style of the already available `add_module()` or `add_function()` to help users to speed things up whenever they frequently make use of R6.

**Comment by ColinFay** [comment]
Done via 5cefbab
