### ISSUE TITLE
[BUG] - Error: 'pkg_path' is not an exported object from 'namespace:golem'

### ISSUE THREAD

**Issue by gabrielburcea** [ThinkR-open/golem#1032]
Hello got a error when attempted to create a golem shiny app. 

Error: 'pkg_path' is not an exported object from 'namespace:golem'
Error in yaml.load(string, error.label = error.label, ...) : 
  (mtrclogs/inst/golem-config.yml) Could not evaluate expression: golem::pkg_path()

Can you help ?

**Comment by ColinFay** [comment]
@gabrielburcea what's your current golem version?

**Comment by gabrielburcea** [comment]
@ColinFay -  the problem was that I have developed a rbuild package, and then wanted to add the golem shiny inside of it. Now, I just done shiny app on it's own and did not have anymore issues. Thus, consider it as closed?

**Comment by ColinFay** [comment]
Sure, feel free to comment here again if you encounter this issue.
