### ISSUE TITLE
remove old artefacts + face-lift in 01_start.R, a_start.Rmd and fill_desc() [FR]

### ISSUE THREAD

**Issue by ilyaZar** [ThinkR-open/golem#1046]
### remove old artefacts of `set_golem_options()` from docs + improve docs

Sorry I was working  (__too slowly !__) on the now closed #1040  :)

+ there is some un-updated stuff in `01_start.R`  and ` a_start.Rmd` regarding `set_golem_options`
+ add some more documentation

I’ll leave the suggestions here, maybe it will become useful at some point

__*but feel free to close at any point ! !*__

**Comment by ColinFay** [comment]
closed via #1047
