### ISSUE TITLE
Refactor dockerfile creators with {pkgload}

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#106]
Instead of parsing the DESCRIPTION dcf

**Comment by VincentGuyader** [comment]
what was your meaning about this ?

**Comment by ColinFay** [comment]
We're using things like `read.dcf(input)[1]` but the `dcf` file can exist in a different order (which is kind of unlikely, but possible).

https://github.com/ThinkR-open/golem/blob/master/R/add_deploy_helpers.R#L160

I think we can use `pkgload::pkg_name()` there 

Also https://github.com/ThinkR-open/golem/blob/master/R/add_deploy_helpers.R#L234

**Comment by ColinFay** [comment]
Let's keep it dependency free
