### ISSUE TITLE
Building Dockerfile in R < 3.1.0

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#107]
Current rocker/r-versioned goes back to `R 3.1.0`, so we should think about how to handle these cases if the user has a version before that

**Comment by ColinFay** [comment]
https://github.com/rocker-org/rocker-versioned/tree/master/r-ver

**Comment by VincentGuyader** [comment]
I can see the problem. But I'm not sure the problem will ever arise :)

**Comment by ColinFay** [comment]
Shiny depends on `R (>= 3.0.2)`, so building before that is relatively impossible I guess. 

I think we should add a warning that we're building on top of `3.1.0` if someone tries to go before that (current oldest version of r-ver)

**Comment by ColinFay** [comment]
Given that R 3.0.2 was released on September, 2013, it's very unlikely that anybody using `{golem}` will come to still be using that version. 

If ever you come by and it's the case for you, please leave a comment here.
