### ISSUE TITLE
Customize app_ui function to allow other shiny templates

### ISSUE THREAD

**Issue by DivadNojnarg** [ThinkR-open/golem#109]
By default, the app_ui file contains a classic fluidPage design. Would it be possible to add an option to allow for shiny dashboard or other templates like navbarPage?

**Comment by ColinFay** [comment]
Thanks for the idea. 

That should be pretty straightforward with package templating, I'll have a look into that. 

Could be nice to also have a "golem_format" options (a la rmarkdown) to implement your own app_ui / app_server templates
