### ISSUE TITLE
Move `use_git()` to bottom to commit all at once in `dev/01_start.R` [FR]

### ISSUE THREAD

**Issue by ilyaZar** [ThinkR-open/golem#1093]
**Is your feature request related to a problem?**
When starting a fresh golem I tend to immediately run `01_start.R` just to set up __*everything*__ and do not bother anymore. 

I also add  a `git`-workflow every time and can imagine that for many this became the start up workflow when starting a new shiny golem app.

However, because the `use_git()` call does not appear in the end I will have to commit twice:

1. doing the default "initial commit" as per the `use_git()` call in `dev/01_start.R` AND
2. when I execute the last lines (which I have to do manually again because the `use_git()` call restarts RStudio which is a bit annoying too) and __*again re-commit*__ the `test/`, `R/golem_utils_server.R` and `R/golem_utils_ui.R` etc. files:

![re-commit](https://github.com/ThinkR-open/golem/assets/36898027/2cd908d0-eb91-4594-ba4f-31e4c941825e)

**Describe the solution you'd like**
It would be somewhat nicer (in my opinion) if sourcing the `dev/01_start.R` file would end with an initial commit and nothing else to do to be able to move e.g. `dev/02_dev.R` or somewhere else directly (without an additional re-commit step).

So ideally something like that:

![Screenshot from 2023-08-10 15-01-36](https://github.com/ThinkR-open/golem/assets/36898027/c16f95d4-dbaa-437c-83b6-0309be2eed6d)

**Additional context**
Can be changed by moving `git`-calls to the bottom #1094

**Comment by ColinFay** [comment]
Merged in dev
