### ISSUE TITLE
Consider \dontrun for ui utils examples

### ISSUE THREAD

**Issue by rpodcast** [ThinkR-open/golem#11]
I am trying out `golem` on a new project and so far it's been fantastic!  As I was creating custom functions for my app (more for backend functionality) I documented examples and tested them out via `devtools::run_examples()`, and one of the built-in `golum` utility functions `tagRemoveAttributes` had an example that couldn't be run without error (something about missing the tags object).  I'd recommend putting the examples for these utility functions in a `\dontrun` block so the user can opt-in to having those run as actual examples.

**Comment by VincentGuyader** [comment]
Hi, 
I made some corrections. Can you confirm e that's ok now ?

Regards

**Comment by rpodcast** [comment]
Just tried the new version and `devtools::run_examples()` reports no errors.  Thanks for the quick fix!

**Comment by ColinFay** [comment]
As it seems to be fixed, I'm closing this one. Thanks Eric for the feedback 💪
