### ISSUE TITLE
[FR] Fix broken tests in `test-with_opt.R`

### ISSUE THREAD

**Issue by ilyaZar** [ThinkR-open/golem#1119]
The tests in `tests/test-with_opt.R` are defunct as the `run_app()` function is not properly sourced in a dummy-golem.

One can add a call to `devtools::load_all()` inside the test so the dummy golem has `run_app()` in its workspace. The test should run in non-interactive mode then.

Can be fixed via #1120

**Comment by ColinFay** [comment]
Closed via test refactoring
