### ISSUE TITLE
[FR] Improved fix for broken test `test-use_readme.R` 

### ISSUE THREAD

**Issue by ilyaZar** [ThinkR-open/golem#1121]
Via https://github.com/ThinkR-open/golem/commit/9ad97753a585ca1ec418025f3ff08db629592702 a test fix for `test-use_readme()` is done that skips the test in non-interactive mode.

However, when eliminating the `devtools:::build_readme()` call at the very end, the test passes successfully in non-interactive mode, so no need for skipping.

Hence, to improve codecov one may delete the `devtools:::build_readme()` line and run the test as usual.

Can be fixed via #1122

**Comment by ColinFay** [comment]
This has been closed via #1131
