### ISSUE TITLE
[BUG] golem::create_golem() doesnt with `path = "."` if `package_name` is missing

### ISSUE THREAD

**Issue by ymansiaux** [ThinkR-open/golem#1123]
![image](https://github.com/ThinkR-open/golem/assets/49268931/33dc57b6-7ad6-475b-a9af-02a3fb89b3d5)

golem::create_golem() doesnt with `path = "."` if `package_name` is missing. 

According to the function documentation, this should be doable.

![image](https://github.com/ThinkR-open/golem/assets/49268931/2679210d-3b3c-4c61-8447-faa6f3ef8977)

**Comment by ColinFay** [comment]
Merged
