### ISSUE TITLE
run_app not found in github branch after document_and_reload() [BUG]

### ISSUE THREAD

**Issue by David-Rattray** [ThinkR-open/golem#1128]
I have two github branches for the app I am developing in golem. On the main branch no issues going into the run_dev.R and running all the steps. golem::document_and_reload() followed by run_app() goes off without a hitch and my app loads up.

However if I switch to my development branch this no longer works as "Error in run_app() : could not find function "run_app".
Now I've found an easy fix for this, I just call pkg_load::load_all() prior to run_app() and everything seems to work fine.

Not sure if this is a known problem, or something specific to how I've got everything setup?

Thanks!

**Comment by VincentGuyader** [comment]
Hi
Do you have a like to your app ?

**Comment by ColinFay** [comment]
Closing for lack of a reproducible example. 

@David-Rattray feel free to comment back if you can share a link with us to a repo that shows the issue :) 

Thanks
