### ISSUE TITLE
Do not use installed.packages

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#114]
> You are using installed.packages(): "This needs to read several files per installed package, which will be slow on Windows and on some network-mounted file systems.

**Comment by VincentGuyader** [comment]
I made all `docker run rocker/r-ver:3.6 R -e 'dput(rownames(installed.packages(priority="base")))'`

And the output is always the same:

I thinkk we can hardcode 

```
reco <- c("base", "compiler", "datasets", "graphics", "grDevices", "grid", 
              "methods", "parallel", "splines", "stats", "stats4", "tcltk", 
              "tools", "utils")```
