### ISSUE TITLE
Could not find function "with_golem_options"

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/golem#118]
When running `golem::set_golem_options()`, it is necessary to run `roxygen2::roxygenize()` after because a new function is introduced. Otherwise, we cannot run the default app.  
*Image*
![image](https://user-images.githubusercontent.com/21193866/61967698-537bdf80-afd6-11e9-98b2-cc0477903759.png)
  
I would recommend adding a message to encourage the user to run `roxygen2::roxygenize()` because after that, the app launches.  
*Image*
![image](https://user-images.githubusercontent.com/21193866/61967888-d735cc00-afd6-11e9-8656-59c1d3c7ec72.png)
 

Also, if we do not run `golem::set_golem_options()`, then the default app cannot start as `with_golem_options` does not exist.

**Comment by VincentGuyader** [comment]
It's because you use `devtools::load_all()` instead of `golem::document_and_reload()`

But I made the correction in the default NAMESPACE
