### ISSUE TITLE
Unable to run the salesforce audit and event log flex files from AWS server

### ISSUE THREAD

**Issue by ArunprasadGugan123** [ThinkR-open/golem#1182]
Hi Team,

While migrating we are suppose to move all the flex config which is running currently in on premise and while we are trying to migrate we face issue in running the salesforce exporter and receive the below error. The necessary ports are opened at firewall end and we can see the traffic while running the flex files.
The same file while running from on premise server we do not face any issue and the data is reporting to Newrelic.
Please find the sample error image and the config sample attached FYR..
As this AWS migration plays a huge impact we are on the phase of cutoff period. So, we would like to resolve this issue asap.
Please feel free to schedule call anytime between 11 am IST to 11 PM IST.

Regards,
Arunprasad Gugan

[error flex.txt](https://github.com/user-attachments/files/17044347/error.flex.txt)

![attribute error](https://github.com/user-attachments/assets/071fddd1-e419-46bb-a9f4-753d77f5be1e)

**Comment by VincentGuyader** [comment]
hi,

are you sure thaht you are on the correct github repo ?

I dont get the point :)

**Comment by ArunprasadGugan123** [comment]
Hi @VincentGuyader,

It is not the right github repo. We can close it.

Regards,
Arunprasad
