### ISSUE TITLE
Better error on missing name in add_*

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#120]
Current is

``` r 
> golem::add_js_handler()
Error in eval(parse(text = text, keep.source = FALSE), envir) : 
  argument "name" is missing, with no default
```

Should be something like 

``` r 
> golem::add_js_handler()
Error: name is required
```

Should be easy to implement with `attempt::stop_if(name, is.missing)`

**Comment by novica** [comment]
Using `is.missing` returns `object 'is.missing' not found`. But 
```
attempt::stop_if(rlang::is_missing(name),
  msg = "Name is required")
```
seems  to do the job.

**Comment by ColinFay** [comment]
@novica Yes, this is what we need: if there is no "name" argument passed by the user, we return an informative message :)
