### ISSUE TITLE
Calling data in ui.R saved in data-raw

### ISSUE THREAD

**Issue by dilsherdhillon** [ThinkR-open/golem#127]
I'm trying to develop a simple app that takes in a pre-trained model(*.RDS), and given the input by user, outputs predictions.  <30 lines of code.  

I now want to package this up in an app, and eventually docker + shinyproxy.  

My question is - 
What path do I use to call the model in my ui.R file, if I keep my data in the `data-raw` folder?  
This is what I'm using but when I run it, it says model_1 not found.   
```{r}
model_1 <- readRDS("data-raw/trained_model.rds")  

## the UI stuff below here

```
How do I ensure my relative path when reading in the model object in ui.R calls in the model?

**Comment by VincentGuyader** [comment]
Hi, 

the `data-raw` folder will not be present in your builded package. you cant use it in your app.
a nice way to do what you need is to put your rds file inside the `inst/extdata` folder dans to use :

`readRDS(system.file("extdata","plop.rds",package = "yourgolem")))`

Regards

**Comment by ColinFay** [comment]
Just as any package the `data-raw` folder is ignored when build, so you can't refer to data from there. 

As far as I see it if you need something accessible in your UI, you should: 
- save your RDS as a data file in your package (http://r-pkgs.had.co.nz/data.html)
- in the `with_golem_options`, use `golem_opts(mydata = mypkg::mydata)` at https://github.com/ThinkR-open/golem/blob/master/inst/shinyexample/R/run_app.R#L9
- in your UI function, use `get_golem_options("mydata")` to access your dataset. 
See https://github.com/ColinFay/golemexample/blob/master/README.md#passing-arguments-to-run_app 

Does it do what you need? Let me know if you need a more detailed example

**Comment by dshelldhillon** [comment]
Hi Vincent and Colin - 
Thank you for your help and sorry for the late reply. I've been out and will give this a try and close the issue. 
Once again, thanks a ton!! 

Dilsher

**Comment by ColinFay** [comment]
Ok so I thought this through and realized it's way easier than that with the way `{golem}` is implemented. 

You just have to:
- Register your dataset as a package data (follow http://r-pkgs.had.co.nz/data.html) : 
<https://github.com/ColinFay/golemexample/blob/master/data-raw/dataset.R#L6> which is turned into <https://github.com/ColinFay/golemexample/blob/master/data/plop.rda>

+ Use your data object wherever you need it (in your UI or server)
<https://github.com/ColinFay/golemexample/blob/master/R/mod_my_fourth_module.R#L21> and <https://github.com/ColinFay/golemexample/blob/master/R/mod_my_fourth_module.R#L36>

<img width="1438" alt="Screenshot 2019-08-21 at 22 52 06" src="https://user-images.githubusercontent.com/17936236/63467706-5697ad80-c466-11e9-9fd0-fc85fb5dfb96.png">

**Comment by ColinFay** [comment]
hi @dilsherdhillon 

Have you worked on that? Do you need any more info? 

Don't hesitate to close the issue if everything is ok :)

**Comment by dshelldhillon** [comment]
Sorry! Yes it worked - thank you so much for this package!

**Comment by ajmoralesa** [comment]
> Ok so I thought this through and realized it's way easier than that with the way `{golem}` is implemented.
> 
> You just have to:
> 
> * Register your dataset as a package data (follow http://r-pkgs.had.co.nz/data.html) :
>   https://github.com/ColinFay/golemexample/blob/master/data-raw/dataset.R#L6 which is turned into https://github.com/ColinFay/golemexample/blob/master/data/plop.rda
> 
> * Use your data object wherever you need it (in your UI or server)
>   https://github.com/ColinFay/golemexample/blob/master/R/mod_my_fourth_module.R#L21 and https://github.com/ColinFay/golemexample/blob/master/R/mod_my_fourth_module.R#L36
> 
> <img alt="Screenshot 2019-08-21 at 22 52 06" width="1438" src="https://user-images.githubusercontent.com/17936236/63467706-5697ad80-c466-11e9-9fd0-fc85fb5dfb96.png">

@ColinFay I'm having troubles with this in a dockerized golem app. Everything works well when I install or test locally the app, but when running a docker container, I keep having:

```
Listening on http://0.0.0.0:3838
Warning: Error in get: object 'db_coord' not found
  [No stack trace available]
```

As suggested [here](https://www.gitmemory.com/issue/ThinkR-open/golem/321/570251784), I called explicitly the data set using mypackage::mydataset, but the error remains. I also tested [your suggestions](https://github.com/ThinkR-open/golem/issues/127#issuecomment-522167475) but did not resolve the issue either.

Do you have any idea of what can be happening? Many thanks in advance!

**Comment by ajmoralesa** [comment]
I guess my issue is related to #413 and more specifically #321
