### ISSUE TITLE
Allow to download CSS / JS file from the web

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#130]
Instead of having to do `download.file("", "inst/...")`, {golem} should have a `download_external_css` or something like this, that downloads the file and add it at the right place.

**Comment by VincentGuyader** [comment]
Good idea.
I think I could be good to have a consistent notation with 'use_favicon' (it's the same spirit)

**Comment by ColinFay** [comment]
That should also work for images and any external file

**Comment by zwycl** [comment]
Hello, I would like to work at this issue for hacktoberfest!

**Comment by ColinFay** [comment]
Thanks @zwycl! 

You're now assigned to it then :) 

Is the issue description explicit enough or do you need more information?

**Comment by zwycl** [comment]
The idea is to create functions _download_external_css_ and _download_external_js_ that download specific types of file from the web and put them in the right place ("inst/app/www"), and then call _add_js_file_ or _add_css_file_ to add the application, correct?

Thanks in advance!

**Comment by ColinFay** [comment]
That's it, perfect! 

Thanks :)

**Comment by VincentGuyader** [comment]
we maybe need to adapt the `use_favicon` function with the same principe...

**Comment by ColinFay** [comment]
implemented
