### ISSUE TITLE
Add examples to README

### ISSUE THREAD

**Issue by edgararuiz-zz** [ThinkR-open/golem#134]
It would be great if there was a section in the README with links to repos that are using `golem`.  Ideally, one of them would be a "hello world" super simple repo that would help us obtain basic understanding of the process.  Something similar to how `drake` does it in its README: https://github.com/ropensci/drake#use-cases

**Comment by ColinFay** [comment]
Very good idea. 

I think we can also get inspiration from https://github.com/rstudio/shiny-examples

**Comment by ChrisBeeley** [comment]
I'd be up for having a go at this, although you both seem to have slightly different things in mind @edgararuiz seems to be suggesting just a load of links to repos all over the place with golem project, whereas @ColinFay seems to be suggesting that it would be good to have a repo all on its own with examples of how to do different things in golem, just like in the Shiny examples repo.

I could spend a bit of time tracking down some repos and linking to them in the README, or I wouldn't mind making a start on some examples a la shiny-examples, but I can't do all 182 straight away :smiley: 

Where would you put it? In ThinkR-open? Happy to submit a PR to a bare repo there if that's what you would like to do

**Comment by ColinFay** [comment]
hey @ChrisBeeley ! 

Thanks for joining :) 
I think starting with a series of link in the README (ideally deployed app + link to repo) would be awesome 🤘

When it comes to a series of example à la shiny-examples, I think I'll first need to organize all the examples I have on my account before :)

**Comment by ChrisBeeley** [comment]
I've found a few, your golem example could be one https://github.com/ColinFay/golemexample, although it is showing the error message fixed here https://github.com/ThinkR-open/golem/pull/432. Shall I add that one too? I can host it as well if you would like?

**Comment by ChrisBeeley** [comment]
I found your repo too @seanhardison1 would it be okay to link to the code and hosted version? I wasn't sure if you wanted the traffic if you're not on a paid shinyapps.io account

**Comment by seanhardison1** [comment]
Hey @ChrisBeeley, sure that's fine with me, so long as you don't mind the fact that it's still pretty early in dev.  

We're moving the app onto a more capable server in a couple of months so I'll let you know when the link changes.
