### ISSUE TITLE
run_app.R should be renamed app_run.R 

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#137]
As we need to use a convention for file names (mod_*, fct_*, utils_*) #123, run_app.R should be renamed app_run.R to follow the top level convention of app_ui and app_server.

**Comment by VincentGuyader** [comment]
is it too late to change the `run_app()` function to `app_run()` ?

It's important to have  the same name for function *and* source file script.
maybe we can do the change everywhere like this :
shinyexample::run_app() to shinyexample::app_run()
and also let somewhere `run_app <- app_run` to avoid breaking change

**Comment by ColinFay** [comment]
Strictly speaking, there is no reason to do `run_app <- app_run`: the name will be changed only in golem created after the change.

As the `run_app` function is defined inside the package, even if newer version of golem uses `app_run()`, that wouldn't break old code. 

But that would break documentation :)

**Comment by ColinFay** [comment]
I think I can live without changing that
