### ISSUE TITLE
Profiling a golem app with profvis

### ISSUE THREAD

**Issue by fmmattioni** [ThinkR-open/golem#146]
I have asked a question to @ColinFay on twitter regarding how I could run [profvis](https://github.com/rstudio/profvis/) in a golem app (twitter discussion may be accessed [here](https://twitter.com/felipe_mattioni/status/1171521806571728896)).

The problem is that if we try to wrap `profvis::profvis()` into `golemapp::run_app()` (let's imagine here the `golemapp`is the name of our app) as in:
```
profvis::profvis({
     golemapp::run_app()
})
```

We get the following error:

`Error in parse_rprof(prof_output, expr_source) : 
  No parsing data available. Maybe your function was too fast?`

According to @ColinFay, the current workaround is to wrap `golemapp::run_app()` into `print()` and then wrap in in `profvis::profvis()` as in:

```
profvis::profvis({
  print(
    golemapp::run_app()
  )
})
```

Thank you all!

**Comment by ColinFay** [comment]
Thanks @fmmattioni! 

As said on Twitter, that's because run_app() returns the App objet but doesn't actually run it.

The print S3 for shiny app object is responsible for launching the app. 

Reminder to myself: talk about this `profvis()` / `{golem}` interaction somewhere.

**Comment by dwhdai** [comment]
Thanks! Another potential work-around that I have found is using the profvis_ui() and profvis_server() module. There is an example of this at the bottom of this page: https://rdrr.io/github/rstudio/profvis/man/profvis_ui.html#heading-4

**Comment by ColinFay** [comment]
Given #496, it's now possible to do `profvis::profvis(run_app())` by default, no need for explicitly printing anymore :)

**Comment by fmmattioni** [comment]
Does anyone know if something changed with `profvis`?

Doing `profvis::profvis(run_app())`, I get the following:

```r
Error in parse_rprof(prof_output, expr_source) : 
  No parsing data available. Maybe your function was too fast?
```

**Comment by ColinFay** [comment]
@fmmattioni the print arg turned to TRUE by default used to make shiny apps io and connect crash, so now you need to explicitly set the print argument to TRUE if you need to :)

**Comment by fmmattioni** [comment]
Hey, @ColinFay! Do you mean `profvis(run_app(print = TRUE))`? If so, I get the same error as above ☹️

**Comment by MallerBeach** [comment]
Hey, @ColinFay same error occurs for me.

**Comment by aeron15** [comment]
In case it's helpful the solution to this problem is documented [here](https://engineering-shiny.org/need-for-optimization.html#profiling-shiny) `profvis(print(run_app()))`
