### ISSUE TITLE
Allow to add fct and utils_ on module creation

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#154]
The `add_module()` should have two arguments more to allow to automatically create the `mod_fct_` and `mod_util_` associated. 

So instead of 

``` r 
add_module("plop")
add_fct("server", "plop")
add_utils("ui", "plop")
```

We would have `add_module("plop", fct = "server", utils = "ui")`

**Comment by novica** [comment]
Hi. I noticed golem on my twitter feed and would like to use hacktoberfest to learn some more R. What is the best way to continue in order to try to contribute some code? Is there any guidance on your part?

**Comment by ColinFay** [comment]
Hey @novica, 

I just added a CONTRIBUTING.md guide here : https://github.com/ThinkR-open/golem/blob/master/CONTRIBUTING.md

Let me know if that helps.

**Comment by novica** [comment]
Hi @ColinFay thanks for the guide. 

So, I was looking at the code in the `dev` branch, and this is my thinking: add the two arguments in `add_modules.R` so it looks like this: 

`add_module <- function(
  name, 
  fct = NULL,
  utils = NULL,
  pkg = get_golem_wd(), 
  open = TRUE, 
  dir_create = TRUE
)`

Then, following the logic in `add_r_files.R` add tow `if` statements to `add_modules.R`:
``` 
if (!is.null(fct)){
    ext_fct <- "fct_"
  }
  
  if (!is.null(utils)){
    ext_utils <- "utils_"
  }
  
  where <- file.path(
    "R", paste0("mod_", ext_fct, ext_utils, name, ".R")
  )
```

Am I on the right track here?

By the way, would this make `add_r_files.R` obsolete?

**Comment by ColinFay** [comment]
Hello @novica, 

Thanks for digging into that. 

Yeah that's the spirit. 

Here are some ideas:

+ The new argument should be placed at the end of the function `()` so that there is no breaking change with old code :) 
+ We will definitely keep the functions from `add_r_files`, so that these functions can still be called whenever you want. So the idea would be more to have something like : 

```
if (!is.null(utils)){
  golem::add_utils(utils, module = module_name)
}
```

Let me know if this makes sense :) 

Colin

**Comment by novica** [comment]
Hi @ColinFay 

I guess it does make sense. The `if` statements call the functions that are exported from `add_r_files.R`. Unless I am missing something then all of the changes to `add_module.R` are not very complicated. This is how I changed the file: https://github.com/novica/golem/commit/62c8e8fa320ec683f73f5efa461370d95ccc6be0

**Comment by ColinFay** [comment]
Perfect! 

Do you feel like writing a unit test for this?
It should be included in: 
https://github.com/ThinkR-open/golem/blob/master/tests/testthat/test-add_module.R 

+ If you prefer me to write it, no worries, I'll be happy to :) 
+ If you're not familiar with tests and want to know more, you can start there: http://r-pkgs.had.co.nz/tests.html

**Comment by novica** [comment]
Sure, I will try to write the test. I haven't used `testthat` before only `testit` but I hope it is not too different.

**Comment by novica** [comment]
OK. I think this is it: https://github.com/novica/golem/commit/355e7a95fc4da1ab8f33004803cf457a3b123cee

**Comment by ColinFay** [comment]
Yep, as `fileext` is vectorized you'll get three R there so `expect_equal` will fail. 

``` r 
script <- list.files("R")
tools::file_ext(script)
 [1] "R" "R" "R" "R" "R" "R" "R" "R" "R" "R" "R" "R" "R" "R" "R" "R" "R" "R" "R" "R"
[21] "R" "R" "R" "R" "R" "R"
```

so 

``` r 
testthat::expect_equal(tools::file_ext(script), "R")
```

fails. 

Updating to `lapply(tools::file_ext(script), function(x)  testthat::expect_equal(x, "R"))` should work :)

**Comment by novica** [comment]
Awesome :) Thanks for the guidance @ColinFay 
All tests pass. Here is the last commit.
https://github.com/novica/golem/commit/79ebb0b59078bde726b65e64d45fdbadd0e1b4e2

**Comment by ColinFay** [comment]
Very cool 🤘

Can you PR this into `dev`?

**Comment by novica** [comment]
Done.

**Comment by ColinFay** [comment]
Merged. 

Thanks @novica !
