### ISSUE TITLE
golem::invoke_js can't handle lists

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#155]
```
golem::invoke_js(
      "update_select_menu", 
      list(
        vals = r$vals, 
        id = ns("selectMesure")
      )
    )
```
should behave just like : 

```
session$sendCustomMessage(
      "update_select_menu", 
      list(
        vals = r$vals, 
        id = ns("selectMesure")
      )
    )
```

**Comment by ColinFay** [comment]
This might be due to `mapply()`

**Comment by zwycl** [comment]
Hello, I would like to work on this.

**Comment by ColinFay** [comment]
@zwycl Of course, please do.

**Comment by ColinFay** [comment]
So to give more context about `invoke_js`, the reason why it's with a `mapply` is that I wanted to be able to do something like `golem::invoke_js("hide_id", c("a", "b"))` so calling the JS fun on several elements. The issue is that the current implementation prevents from doing this:

``` r
golem::invoke_js(
      "alertthis", 
      list(
        vals = 1234, 
        vouls = "selectMesure"
      )
    )
```

to send to 

``` r
Shiny.addCustomMessageHandler('alertthis', function(arg) {
  alert(arg.vals + " " + arg.vouls);
})
```

Which is available with 

``` r
session$sendCustomMessage(
      "alertthis", 
      list(
        vals = 1234, 
        vouls = "selectMesure"
      )
    )
```

I'm wondering what would be the best way to do this without doing too much of a breaking change. Wonder if `invoke_js(fun, ...)` would allow to do 

``` r
invoke_js(fun, list(a = a, b = b), list(a = c, b = d)) 
```

Which would be a breaking change but for a very specific use case 🤔

**Comment by zwycl** [comment]
Basically, we want some kind of `mapply` function that does not destructure lists and only applies to vectors, yes?

**Comment by zwycl** [comment]
I'm not sure about but perhaps it's better to refactor `invoke_js`, into two functions - `invoke_js` which takes in lists as a JSON sort of argument list for `sendCustomMessage` and `map_invoke_js` which takes in lists as in multiple things we want apply to `sendCustomMessage`.

So code would be like the following:
``` r
#' @export
#' @rdname golem_js
invoke_js <- function( 
  fun, 
  session = shiny::getDefaultReactiveDomain(),
  ...
){
  res <- session$sendCustomMessage(fun, list(...))
  invisible(res)
}

#' @export
#' @rdname golem_js
map_invoke_js <- function( 
  fun, 
  session = shiny::getDefaultReactiveDomain(),
  ...
){
  res <- mapply(function(x, ...){
    invoke_js(x, ...)
  }, x = fun)
  invisible(res)
}
```

**Comment by ColinFay** [comment]
That's, like, a perfect idea 💡
