### ISSUE TITLE
Typo in add_dockerfile_shinyproxy()?

### ISSUE THREAD

**Issue by fmmattioni** [ThinkR-open/golem#156]
I believe the following line is missing to separate `-e` from the following code:

https://github.com/ThinkR-open/golem/blob/master/R/add_deploy_helpers.R#L190

The generated Dockerfile displays the following result:

`CMD  ["R", "-e options('shiny.port'=3838,shiny.host='0.0.0.0'); xxx::run_app()"]`

And it ignores `xxx::run_app()` when it is run.

I manually changed it to:

`CMD  ["R", "-e", "options('shiny.port'=3838,shiny.host='0.0.0.0'); xxx::run_app()"]`

And it works.

Any thoughts?

P.S.: Docker beginner here, so excuse me if it was my mistake somehow.

**Comment by ColinFay** [comment]
You're very right, that's a typo. 

Would you be willing to make a PR to solve that ? 

I think this where the problem lies: https://github.com/ThinkR-open/golem/blob/master/R/add_deploy_helpers.R#L190

**Comment by fmmattioni** [comment]
Oh, that is great! I will do that today!

**Comment by Brabin3** [comment]
Hi Colin,

I see that the provided links are not working. 
I am stuck up in the same place while configuring to ShinyProxy with Brochure App.
The app gets deployed and the first page alone loads.
All other pages are missing when deployed with ShinyProxy (404).

In shiny Proxy application.yml file,
container-cmd: ["R", "-e", "shiny::runApp('/root/euler')"]

Any help is greatly invited.
