### ISSUE TITLE
Favicon is lost when deployed with shinyproxy

### ISSUE THREAD

**Issue by fmmattioni** [ThinkR-open/golem#159]
This is related to [this discussion](https://twitter.com/felipe_mattioni/status/1174636363808989184) on Twitter.

I have noticed that after deploying my shiny app with shinyproxy (this is currently in a temporary testing URL), I loose my favicon that was added through `golem::use_favicon()`.

I have two versions of this app:

1) Deployed with Shiny Server (favicon works): https://shiny.fmattioni.me/lactate
2) Deployed with ShinyProxy (favicon doesn't work): https://shiny.fmattioni.me/lactate2

Looking at the elements of the page in both the apps I have:

`<link rel="shortcut icon" href="www/favicon.ico">`

I also have other documents under the `www/` that still work perfectly in ShinyProxy, so I wonder if this is an issue with ShinyProxy instead of golem?

**Comment by VincentGuyader** [comment]
tanks for this issue, 

I will look at this !

Regards

**Comment by VincentGuyader** [comment]
I've been thinking about this problem.
I think the favicon that is displayed is the one of shinyproxy (the green leaf) and there's not much we can do about it. Because of the shinyproxy iframe system...

**Comment by fmmattioni** [comment]
Thank you, @VincentGuyader for looking into this.. I am going to contact the authors of shinyproxy to check whether they might consider adding an option to remove this green leaf, thus not overwriting the favicon.

**Comment by VincentGuyader** [comment]
There is an option `favicon-path: favicon.ico` in the application.yml file. But it's the same for all the apps

**Comment by fmmattioni** [comment]
One comment on this... I have just realized that if I have `favicon.png` instead of having `favicon.ico` it works. For some reason, `favicon.ico` does't get uploaded.

**Comment by fmmattioni** [comment]
All I had to do was to use `golem::favicon(ico = "www/favicon.png")`

**Comment by ColinFay** [comment]
Ah, that's good to know! 

Any chance you could add a small note about this there: https://github.com/ThinkR-open/golem/blob/master/vignettes/a_start.Rmd#L177 ?

**Comment by fmmattioni** [comment]
Of course!

I just wished I knew the reason why this happens... any thoughts?

**Comment by fmmattioni** [comment]
Another comment: this only is going to work if you have the following option in the `application.yml` in shinyproxy:

```
proxy:
  landing-page: /app_direct/
```
As @VincentGuyader pointed out, if we keep the default settings (iframe), this isn't going to work.

**Comment by fmmattioni** [comment]
I guess a definite solution would be the authors from shinyproxy modifying the HTML template here:

https://github.com/openanalytics/shinyproxy/blob/f4576055af7f51934470ada82bbf07b5d5fc65df/src/main/resources/templates/app.html#L26-L33

I don't know how, but it would make sense for this template to include the 

`<link rel="shortcut icon" href="www/favicon.png">`

But now the problem would be that `www/favicon.png` wouldn't work anymore, as it would reference to `mydomain.com/www/favicon.png` instead of `mydomain.com/app/www/favicon.png` because it is a head tag before the iframe.

I am sorry for the many comments on this issue. I just thought it could be of some help for you guys.

**Comment by fmmattioni** [comment]
OK, I finally got it working doing some modifications in the html template from shinyproxy. I know this is nothing related directly to `golem`, but I just wanted to mention that a fix is possible with some `HTML` and `JS` adjustments.

**Comment by ColinFay** [comment]
Closing this issue as it seems to be solved, feel free to comment if you encounter the same issue
