### ISSUE TITLE
Alternative "add_module" function

### ISSUE THREAD

**Issue by robertoromor** [ThinkR-open/golem#161]
I am trying to come up with my own "add_module" function a special template but it has so many dependencies. I created an exact replica of the file in here ThinkR-open/golem/R/add_files.R, sourced it inside 02_dev.R just changing the function name and it does not work. It fails throwing this:

Error in cat_bullet(..., bullet = "tick", bullet_col = "green") : 
 could not find function "cat_bullet

**Comment by VincentGuyader** [comment]
cat_bullet comes from the {cli} package

**Comment by robertoromor** [comment]
do you have an easy way to have all the dependecies used by "add_module" in the edited version. The edited version as I mentioned is the same file with different file and function name sourced in 02_dev,R

**Comment by VincentGuyader** [comment]
Everything is explicitly written in the source file:


#' @importFrom glue glue
#' @importFrom cli cat_bullet
#' @importFrom utils file.edit
add_module <- function(

**Comment by robertoromor** [comment]
That is added in the file too. 
I had to add: 
require(cli)
and the whole function for create_dir_if_needed
I was wondering if it was something that I can change in the NAMESPACE file.

**Comment by VincentGuyader** [comment]
I m not sure to understand what you try to do.
It's seems more an issue about your skill on package creation than a golem issue. 

Regards

**Comment by ColinFay** [comment]
Hey @robertoromor, 

Copying and pasting a function from `{golem}` might indeed not be that easy as it has a small amount of internal functions to run smoothly. 

As Vincent said, it's quite unclear what you're trying to achieve there: are you building your own version of golem or are you building a new package? Or are you trying to create a new function inside your Shiny project? 

Please note that adding this specific add_module_custom function inside your shiny app might not be the best solution. But if this is your intent, you can access golem internal functions with `:::` or `getFromNamespace()`. 

Cheers, 
Colin

**Comment by robertoromor** [comment]
I am trying to create a new function inside my shiny project. I intend to create a dashboard for time series, and this dashboard will have repetitive workflows that need to have their own modules. This makes me want to have a template ready to use as close as possible as my workflow: documentations-extractsqlquery-plottimeseries-DT
I admit my lack of knowledge on package creation as Vincent mentions and I also have to admit that this is not the right place because it is a non-issue. I just could not find a place to post an specific question like this.
Thanks for the tips.

**Comment by ColinFay** [comment]
Ah ok, got it now :) 

What you're asking actually makes sense, so let's call it a feature request ;) 

To sum up, the idea would be to be able to use `add_modules()` but passing a template as a parameter. So you could design your own module skeletons and use them here. 

I need to think about the best way to implement this. 

In the meantime, the best thing you can do is add a file in your `R/`, and in it add the code from `add_module`. The core of the function being the `write_there` statements, which live there: https://github.com/ThinkR-open/golem/blob/master/R/add_modules.R#L43

As far as I know, refactoring this part should suffice adding a custom module. Then call `pkgload::load_all()` in your console and the function should be available. 

Let me know if that works.

**Comment by robertoromor** [comment]
Went on to learn everything about package creation, as recommended by Vincent, to fill up gaps before applying your fix, to learn that I just needed to move the file from the Dev folder where I had it to the R folder. Still everything makes more sense when you dig deeper into package development.
Thanks!
