### ISSUE TITLE
wizard like setup

### ISSUE THREAD

**Issue by dan-reznik** [ThinkR-open/golem#162]
I was wondering if it would make sense for the whole setup phase under golem to be placed on a select-and-click wizard. there's simply too much code-oriented stuff for one to just get to a basic shiny dashboard!

**Comment by ColinFay** [comment]
Hey @dan-reznik, 

Thanks for the suggestion :) 

The reason we have these scripts being that you keep track of what happens during the development process, so I'm not sure I'm comfortable with the idea of having a dynamic wizard unless it writes in the file 🤔

If we build this feature, this should be a wizard that will write inside the dev files, so we are sure that we keep the general philosophy, i.e. documenting the whole dev process :)

**Comment by dan-reznik** [comment]
that's what i meant. you will increase golem's appeal 100 fold. the level
of complexity and detail is just untenable. in a way that's a problem w R
in general. code is very hard to read and maintain. un cas d'amour et haine.

dan

**Comment by ColinFay** [comment]
I've been thinking about this, and I suppose it's quite unlikely that we add this to `{golem}`, but thanks for the suggestion!

Closing this for now, I've worked on detailing more with text the `dev/` scripts, which could help understanding more the dev process, but I don't think that for now we'll be working on making it through a widget :)
