### ISSUE TITLE
Refactor the run_dev script

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#163]
Two things: 

+ [ ] Refactor the script so that it's function based

Notably because of #157 

``` r
run_dev <- function(
  run_app, 
  app_prod = FALSE 
){
  options(golem.app.prod = app_prod)
  golem::detach_all_attached()
  golem::document_and_reload()
  run_app()
}

run_dev(
  shinyexample::run_app
)

```

+ [ ] Allow to open in a new R session

One way to do that can be through processx: 

``` r 
if (!exists('ping')){
  ping <- new.env(parent = emptyenv())
  ping$x <- processx::process$new( "ls")
}

if (ping$x$is_alive()){
  x$kill()
}

ping$x <- processx::process$new(
  "R", 
  c("-e", "options(shiny.port = 1234);pkgload::load_all();run_app()"), 
  echo_cmd = TRUE, stdout = w, stderr =  z  
)
x$is_alive()
Sys.sleep(5)
readLines(z)
browseURL("http://127.0.0.1:1234")
```

Issue being that we don't have the logs from the app in live. 

Another way could be to use RStudio Terminals, as suggested by @Cervangirard: 

``` r
a <- rstudioapi::terminalExecute(
  "R -e 'options(shiny.port = 1234);pkgload::load_all();run_app()'"
)

rstudioapi::terminalKill(a)
``` 

Or 

``` r 
library(R6)

GolemLaunch <- R6Class(
  "GolemLaunch", 
  public = list(
    process = character(0), 
    initialize = function(){
      self$process <- rstudioapi::terminalExecute(
        "R -e 'options(shiny.port = 1234);pkgload::load_all();run_app()'"
      )
    }, 
    stop = function(){
      rstudioapi::terminalKill(
        self$process
      )
    }, 
    get_buffer = function(){
      rstudioapi::terminalBuffer(
        self$process
      )
    },
    is_running = function(){
      rstudioapi::terminalBusy(
        self$process
      )
    }
  )
)
app <- GolemLaunch$new()
app$get_buffer()
app$is_running()
app$stop()

```

**Comment by marciz** [comment]
Any option to include `options(shiny.autoreload = TRUE)` in `run_dev()`, which helps in development?
Tried but without success

**Comment by xari** [comment]
> Any option to include `options(shiny.autoreload = TRUE)` in `run_dev`, which helps in development?
> Tried but without success

I have also been trying to get this to work, without success.

**Comment by xari** [comment]
> > Any option to include `options(shiny.autoreload = TRUE)` in `run_dev`, which helps in development?
> > Tried but without success
> 
> I have also been trying to get this to work, without success.

I would also favor setting the default value to `TRUE`.

**Comment by xari** [comment]
Hey; I'm just checking in to see whether there's been any development regarding `shiny.autoreload`.

@Cervangirard —I had a quick look through 06b0326, but couldn't really tell whether it addresses the `shiny.autoreload` option.

I asked a question on StackOverflow to see whether anyone else out there has any experience with `shiny.autoreload` in `{golem}`:

https://stackoverflow.com/questions/58648662/autoreload-in-golem-apps-shiny-option-doesnt-work

Btw; thanks for developing a great package @ColinFay and @Cervangirard !

Merci, et à +

**Comment by ColinFay** [comment]
hey @xari 

Sorry for the late reply about this. 

As far as I can tell your question isn't related to the original topic of this issue so I'd rather move that conversation to another one :)

**Comment by ColinFay** [comment]
`{golem}` now has `golem::run_dev()`
