### ISSUE TITLE
Document that you can use `{golem}` outside of a `{golem}` project

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#166]
Related to #165 

These functions can work outside of a package structure, it should be documented.

Related twitter thread: https://twitter.com/grrrck/status/1178417852812087296

**Comment by novica** [comment]
Not sure what exactly is needed, but I thought maybe this: https://github.com/novica/golem/commit/c03578a68d8197d9bac17970dfb399f844060647 is a step in the document direction.

**Comment by ColinFay** [comment]
That's very nice. 

I think another good place to have this would be the `02_dev` vignette : https://github.com/ThinkR-open/golem/blob/master/vignettes/b_dev.Rmd
