### ISSUE TITLE
add_dockerfile cant deal with package version in description

### ISSUE THREAD

**Issue by VincentGuyader** [ThinkR-open/golem#169]
If you use `usethis::use_tidy_versions()` before launchin `golem::add_dockerfile()` the dockerfile will not create an line per dependencies.

**Comment by ColinFay** [comment]
I feel like these functions should be handled by {desc} so we have a better grasp on it.

**Comment by VincentGuyader** [comment]
I saw this comment :

>         # Specific versions can cause pblm in Docker (which have a specific date)
>        # And will be handled by install_local so we don't add them

we need to discuss about it :)

**Comment by ColinFay** [comment]
Yep, the reason why it's skipped is that install_version will look for $MRAN/archives, but if we have a newer package version installed in DESCRIPTION, it will throw an error 🤔

Another way to do it would be to install from the Sys.Date()-1 MRAN snapshot when using install_version.

**Comment by VincentGuyader** [comment]
linked to #175

**Comment by ColinFay** [comment]
@VincentGuyader Seems to be done, right?

**Comment by VincentGuyader** [comment]
Yep
