### ISSUE TITLE
golem_add_external_resources should inclue a title tag

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#172]
There should be a title tag included in the `golem_add_external_resources` with the name of the app. 

https://www.w3schools.com/tags/tag_title.asp

**Comment by novica** [comment]
This is in `inst/shinyexample/R/app_ui.R` right?

**Comment by ColinFay** [comment]
Yes it is! 

We should have a `tags$title` that takes the name of the current package (`shinyexample` in the template, which is `str_replace`d on project creation

**Comment by novica** [comment]
Adding `tags$title(package_name)` to the `golem_add_external_resources <- function()` seems to me to be the answer. But I don't know how to run the example app, or test this, so maybe I am missing something obvious.

**Comment by VincentGuyader** [comment]
@novica you can edit this  part : https://github.com/ThinkR-open/golem/blob/1411477d328a306f8b176ab5ee9bb09779e87f34/inst/shinyexample/R/app_ui.R#L17 by putting `tags$title(shinyexample)`

Everything inside shinyexample is used as template during golem creation and `shinyexample` is replaced by the golem names.

Regards

**Comment by novica** [comment]
Hi @VincentGuyader,

I am confused. Shouldn't `tags$title` be inside of `tags$head()`?

**Comment by ColinFay** [comment]
Hey, 

Yes, the title tag should be put inside the tags$head() in the file Vincent pointed to. 

You can simply add the piece of code (`tags$title("shinyexample")` ) there. 

The best way to test it for now is to reinstall your local version and to create a new package with golem :)

**Comment by novica** [comment]
Right. Apologies for all the questions.

**Comment by ColinFay** [comment]
No problem, on the contrary, you're very welcome to ask questions. 

Thanks for your contributions :)
