### ISSUE TITLE
No icon for github in the pkgdown website

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#182]
<img width="370" alt="Screenshot 2019-10-04 at 10 06 13" src="https://user-images.githubusercontent.com/17936236/66191448-a46f1a80-e68e-11e9-8e4a-a32cacedc104.png">

**Comment by espinielli** [comment]
This is strange if you inspect the `fa` home icon you see it has `class="fas fa fas fa-home fa-lg"`
while the github one is  `class="fab fa fab fa-home fa-lg"`.

Changing `fab` to `fas` locally in the browser makes it work, but it is strange.
I thought this icon was coming directly from `pkgdown`...in fact the [news](https://github.com/r-lib/pkgdown/blob/d01672efa3baa80fd7ab238b7143080b0daf49a4/NEWS.md#front-end) for version 1.4.0 mentions new prefix for fa brands.

Then it means it is a matter of fa version to be changed in `thinkrtemplate`, see https://github.com/ThinkR-open/thinkrtemplate/pull/1

**Comment by ColinFay** [comment]
Thanks @espinielli 💪

Waiting for `thinkrtemplate` to be updated then, and pinging @statnmap for that :)

**Comment by statnmap** [comment]
PR accepted in {thinkrtemplate}.  Github icon back.    
Thank you.
