### ISSUE TITLE
golem::detach_all_attached should be silent

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#186]
``` r 
golem::detach_all_attached()
[[1]]
NULL

[[2]]
NULL

[[3]]
NULL

[[4]]
NULL
```

The NULL here are just noise, I think we should silence this. 

> Silence Is Golden

http://www.catb.org/~esr/writings/taoup/html/ch11s09.html

The responsible part being:

``` r
lapply(
	all_attached,
	detach, 
	character.only = TRUE, 
	unload = TRUE
)
```

in `detach_all_attached`

**Comment by annakau** [comment]
Can I try to fix this?

**Comment by VincentGuyader** [comment]
@annakau yes, please !

**Comment by ColinFay** [comment]
thanks @annakau, closing the issue now
