### ISSUE TITLE
implement a logging tool such as futile.logger

### ISSUE THREAD

**Issue by VincentGuyader** [ThinkR-open/golem#192]
see : https://github.com/zatonovo/futile.logger

I could be good to have a true, nice log during dev process

**Comment by ColinFay** [comment]
Related: 

https://github.com/ThinkR-open/building-shiny-apps-workflow/issues/48

See in particular : https://github.com/daroczig/logger/pull/25 

I would be against reinventing the wheel here, I think the best way to go would be to leverage existing tools and integrate them in the workflow.

**Comment by ColinFay** [comment]
Closing for now, I think a logging tool might be out of scope of `{golem}`, and it might be safer to reuse existing packages rather than recreating and maintaining our own.
