### ISSUE TITLE
Article pages don't work on pkgdown site

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#196]
https://thinkr-open.github.io/golem/articles/a_start.html and friends are a 404

<img width="1552" alt="Screenshot 2019-10-07 at 21 30 11" src="https://user-images.githubusercontent.com/17936236/66342440-b5978000-e949-11e9-8280-c14c81ff218d.png">

ping @statnmap

**Comment by statnmap** [comment]
Infos here: https://github.com/r-lib/pkgdown/issues/1158
