### ISSUE TITLE
Remove stringr dependency 

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#201]
We should remove the stringr dependency which is just used once for str_remove_all()

https://github.com/ThinkR-open/golem/blob/master/NAMESPACE#L66

**Comment by ColinFay** [comment]
The only time we use it is : https://github.com/ThinkR-open/golem/blob/1c31dc932a30cfb85b9231879842091c5da960c2/R/create_golem.R#L63

**Comment by TomerPacific** [comment]
@ColinFay , I'd like to help. Apart from removing the dependency, what would like to replace the current usage?

**Comment by ColinFay** [comment]
Thanks @TomerPacific! 

You're now assigned to it :) 

As far as I know the `stringr::str_remove_all` can be replaced by a `gsub`: 

``` r
a <- c("REMOVEME pouet pouet REMOVEME")
stringr::str_remove_all(a, "REMOVEME")
#> [1] " pouet pouet "
gsub("REMOVEME", "", a)
#> [1] " pouet pouet "
```

<sup>Created on 2019-10-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by TomerPacific** [comment]
@ColinFay ,

I opened a [PR](https://github.com/ThinkR-open/golem/pull/202).

Let me know if it checks out.
