### ISSUE TITLE
Function idea : app_deps

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#207]
We regularly call `system.file("blalba", package = "myapp")`. 

it would be nice to have a wrapper around this by default.

**Comment by novica** [comment]
I don't understand what is needed here. After looking at the code, the only place I can see `system.file("blalba", package = "myapp")` is in `utils.R`, and it is in a function. Can you clarify the issue?

**Comment by ColinFay** [comment]
The idea here is to use it in the generated project. 

For example, in this app https://github.com/ColinFay/tidytuesday201942/blob/master/R/mod_about.R#L20 I reuse 

``` r 
system.file(something, package = "tidytuesday201942")
```

four times, where I could have created a wrapper function in the spirit of the internal `golem_sys()` function. 

Would be nice to have an "app_sys" function in golem that can be reused, so that way we can have it at https://github.com/ThinkR-open/golem/blob/dev/inst/shinyexample/R/app_ui.R#L17 and it can be reused anywhere else in the app. 

Maybe we can rely on the `options("golem.pkg.name" = golem_name)` set by `golem::set_golem_options()` so that we can have a function like 

``` r 
app_sys <- function(...){
	system.file(..., package = get_golem_name() )
}
```

Note that `get_golem_name()` doesn't exist, but would be a nice parallel to `get_golem_wd()`

**Comment by novica** [comment]
Does this make sense? https://github.com/novica/golem/commit/b7a0aff06ab7a95d769177558ddd34b8d4f608a5

**Comment by ColinFay** [comment]
Ok, that it, except that you should export the app_sys() function so that it's available for the end user :) 
(The idea is to make it usable inside your app, so it should be exported)

**Comment by novica** [comment]
Yes. I knew I forgot the export as soon as I made the commit.

**Comment by ColinFay** [comment]
implemented
