### ISSUE TITLE
base packages shouldn't be exported in the Dockerfile 

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#21]
Current version of `add_dockerfile()` generates a line with `RUN R -e "remotes::install_cran('utils')" ` if you have utils in the DESCRIPTION, but one can't install recommended packages, so the build of this file fails.

**Comment by ColinFay** [comment]
Will use `dockerfiler::dock_from_description()` once the new version is on CRAN.

**Comment by VincentGuyader** [comment]
or `attachment::att_from_description(field = "Imports")` ;)

**Comment by ColinFay** [comment]
Mmh', as ˋutils` is listed in the Imports field of DESCRIPTION, it will still be listed in the  as an install_cran(). 

I was under the impression that att_from_description doesn't filter out base packages

**Comment by ColinFay** [comment]
Done in last PR
