### ISSUE TITLE
RStudio Shortcuts for opening files

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#212]
We should have a series of RStudio Shortcuts (in an Addin) to go to common files, built on top of `{rstudioapi}`.

For example: 

``` r
go_to<- function(
  file,
  wd = golem::get_golem_wd()
){
  file <- file.path(
    wd, file
  )
  if (! file.exists(file)){
    message(file, "not found.")
  }
  if ( rstudioapi::hasFun("navigateToFile") ){
    rstudioapi::navigateToFile(
      
    )
  } else {
    message("Your version of RStudio does not support `navigateToFile`")
  }
}

go_to_run_dev <- function(){
  go_to("dev/run_dev.R")
}

```

**Comment by novica** [comment]
I will work on this one next.

**Comment by novica** [comment]
Does this make sense: https://github.com/novica/golem/commit/4760b8f295fdbd78da58612688370d42be9601fd ?

**Comment by ColinFay** [comment]
This + app_ui / app_server / run_app and that's exactly what I had in mind :)

**Comment by novica** [comment]
This is it I think: https://github.com/novica/golem/commit/ee33beed4a11d6c3a010ad3e2cef8f773d4b3a10

**Comment by ColinFay** [comment]
Perfect, thanks! 

Can you add yourself as a contributor in the DESCRIPTION file at the same time?

**Comment by novica** [comment]
Should I make the PR to dev? 

About the DESCRIPTION file: I'm not sure how to do that, there isn't a section contributors as far as I can see.

**Comment by ColinFay** [comment]
Yes, please PR. 

For the DESCRIPTION, you can add : 

```
      person(given = "Your",
             family = "Name",
             role = "ctb",
             email = "onlyifyouwant@this.com"),
```

Just before : 

https://github.com/ThinkR-open/golem/blob/master/DESCRIPTION#L25

If you prefer not to add yourself, feel free to skip it :) 

Colin
