### ISSUE TITLE
document and reload should use goleù_wd() and fail gracefully

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#219]
We shouldn't use `.` here https://github.com/ThinkR-open/golem/blob/master/R/reload.R#L36 but `get_golem_wd()`, as in https://github.com/ThinkR-open/golem/blob/master/R/add_deploy_helpers.R#L81

**Comment by j450h1** [comment]
I'd like to take this one.

**Comment by ColinFay** [comment]
Sure, thanks !

**Comment by j450h1** [comment]
Done! See https://github.com/ThinkR-open/golem/pull/221 for details
