### ISSUE TITLE
App fails to run if www/ is empty

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#223]
Following https://twitter.com/therealpsmst/status/1182655124482777089: 

The app fails to run if the inst/app/www is empty, as addResourcePath doesn't find the folder. 

My guess is that R doesn't integrate the empty folders when compiling the package. 

reprex: 

```
colin:~ colin$ cd /tmp
colin:tmp colin$ Rscript -e 'golem::create_golem("pouetpouet", open = FALSE)'
── Created ─────────────────────────────────────────────────────────────────────
colin:tmp colin$ cd pouetpouet/
colin:pouetpouet colin$ Rscript -e 'golem::remove_favicon()'
✔ Removing favicon at inst/app/www/favicon.ico
Rscript -e 'remotes::install_local()'
Rscript -e 'pouetpouet::run_app()'
```

Then go to your browser : 

```
ERROR: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'www'; `directoryPath` = ''
```

The www is indeed empty:

```
colin:pouetpouet colin$ Rscript -e 'system.file("app/www", package = "pouetpouet")'
[1] ""
```

**Comment by webscale** [comment]
@ColinFay  I am getting this problem in R 4.0 on ubuntu. using the latest version of golem (stable)

**Comment by ColinFay** [comment]
@webscale have you changed the name of the golem in the DESCRIPTION but not in app_sys() ? 

What is your current version of golem?

**Comment by webscale** [comment]
@ColinFay  seems to be a machine issue. It works on a different machine. Differences
1.  It works on R 3.6 / It did not work on R 4.  Note sure if this is the issue though.
2. I am probably missing some lib's realted to systemfont on the machine that it does not work on. Trying to figure it out

**Comment by shahreyar-abeer** [comment]
> @webscale have you changed the name of the golem in the DESCRIPTION but not in app_sys() ?
> 
> What is your current version of golem?

@ColinFay I have done this and am getting the same error now.
How do you fix this?

**Comment by shahreyar-abeer** [comment]
Okay, found it.

**Comment by gowachin** [comment]
@shahreyar-abeer I have the same issue, could it be possible for you to give your fix ? (Ubuntu too)

**Comment by KasperThystrup** [comment]
I have the same issue. When installing my package from github, and executing `run_app()` this error shows up:

> Warning: Error in value[[3L]]: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'www'; `directoryPath` = ''
When I run the `run_dev.R` code, everything works fine though.

Package and title from `DESCRIPTION` matches the `golen_name:` of `golem_config.yaml`

**Comment by shahreyar-abeer** [comment]
Changing the name in app_sys() under app_config.R did it for me!
