### ISSUE TITLE
Internal function golem:::dock_from_desc() doesn't recognize `Remotes`

### ISSUE THREAD

**Issue by fmmattioni** [ThinkR-open/golem#226]
I have noticed that the internal function `golem:::dock_from_desc()` creates the `Dockerfile` with all the packages from `DESCRIPTION` as `RUN R -e 'remotes::install_cran("xxx")'`.

If I have for example:

```
Imports: 
    shiny,
    golem,
    attempt,
    DT,
    glue,
    htmltools,
    bs4Dash
Remotes:
    RinteRface/bs4Dash
```

And if I run `golem::add_dockerfile()`, `golem::add_dockerfile_shinyproxy()`, or `golem::add_dockerfile_heroku()`, the resulting `Dockerfile` will have the following line:

`RUN R -e 'remotes::install_cran("bs4Dash")'` instead of 
`RUN R -e 'remotes::install_github("RinteRface/bs4Dash")'`

Of course, I can easily modify it once the `Dockerfile` is created, but I was wondering if this is something that could be improved in `golem:::dock_from_desc()`?

**Comment by VincentGuyader** [comment]
Hi,
I m already working on it on branche "issue_175".
I need to fin a few hours to finish this. 

Regards

**Comment by fmmattioni** [comment]
Oh, my bad! I was careless in double checking existing issues related to this.

Thank you for the feedback!

**Comment by ColinFay** [comment]
Yes, you can check https://github.com/ThinkR-open/golem/pull/190 for more info. 

We're working on refactoring the Docker creation :)

**Comment by ColinFay** [comment]
@VincentGuyader is this one solved?

**Comment by VincentGuyader** [comment]
Yep
