### ISSUE TITLE
golem::add_js_file should allow to include $(function()

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#227]
Maybe with a param, but we should create the JS file with :

```

$(function() {

});
```

**Comment by gadenbuie** [comment]
Along these lines, it could also be useful to insert a `$(document).ready()` template.

I'd also request vanilla JS options, although it starts to get difficult to fit all that in one function argument.

**Comment by ColinFay** [comment]
@gadenbuie AFAIK, both the code (`$(document).ready()` and `$(function(){})`) are the very same function. 

What's the idea behind providing the option to set the two? 

I think we might default to `$(document).ready()` which might be more straightforward

**Comment by gadenbuie** [comment]
Yup, that's right, so the jQuery IIFE-like is fine. But I agree the other form is more straightforward and is even suggested [in the docs]:

> Experienced developers sometimes use the shorthand `$()` for `$( document ).ready()`. If you are writing code that people who aren't experienced with jQuery may see, it's best to use the long form.

In any case, I completely agree; there's no need to complicate things by providing more than one method.

**Comment by ColinFay** [comment]
We now default to having 

```js
$( document ).ready(function() {
  
});
```

In any new JavaScript file.
