### ISSUE TITLE
golem::add_js_file() should not duplicate file extension

### ISSUE THREAD

**Issue by gadenbuie** [ThinkR-open/golem#231]
A minor issue: `golem::add_js_file()` will add an extra `.js` if one already exists on the input name.

```
golem::add_js_file("test.js")
✔ File created at /Users/garrick/golemDemo/inst/app/www/test.js.js
```

I was expecting it to work like `usethis::use_r()`

```
use_r("test.R")
● Modify 'R/test.R'
```

**Comment by ColinFay** [comment]
That definitely shouldn't happen. 

I think wrapping the file name in `tools::file_path_sans_ext()` would solve that. 

We might have the same thing happening with the other file creators. 

I will give it a shot, thanks for reporting that!

**Comment by ColinFay** [comment]
Close by https://github.com/ThinkR-open/golem/pull/236. 

Thanks for the bug report !
