### ISSUE TITLE
unit testing on add_module is broken 

### ISSUE THREAD

**Issue by VincentGuyader** [ThinkR-open/golem#247]
test-add_module.R:5: error: add_module
menu() cannot be used non-interactively

**Comment by VincentGuyader** [comment]
only on dev branche

**Comment by novica** [comment]
I saw this. I think it is because the code 
```
add_module("test", open = FALSE, pkg = pkg,  fct = "ftest", utils = "utest")
expect_true(file.exists("R/mod_test.R"))
expect_true(file.exists("R/mod_test_fct_ftest.R"))
expect_true(file.exists("R/mod_test_utils_utest.R"))
```
shows twice in the file: lines 7-10 and lines 24-27.

It doesn't look to me like both are needed. Commenting out one of these chunks doesn't return errors on test.

**Comment by ColinFay** [comment]
Yeah having it twice will trigger a yesno which is (right now) failing when used non interactively. 

@novica would you be willing to do a PR as you've got it ready? 

And thanks for checking :)

**Comment by VincentGuyader** [comment]
I'm on it.

**Comment by ColinFay** [comment]
now pass

**Comment by novica** [comment]
Apologies for not being able to answer sooner. 

By the way, I was looking into this because I was trying to figure out if other tests are needed, so maybe you can suggest how to go about finding the parts of the code that still need testing?

**Comment by ColinFay** [comment]
@novica if you want to watch the code coverage, you can check : 
https://codecov.io/gh/ThinkR-open/golem, especially https://codecov.io/gh/ThinkR-open/golem/tree/master/R where you have the detail line by line of the code covered by tests. 

It's kind of hard to go for a 100% code coverage in golem as there are functions that appears only when used in the final app. 

But enhancing the current code coverage will definitely be a good thing to work on 
 :)
