### ISSUE TITLE
pacakge name is "." when using golem::create_golem(path = ".") without using pacakge_name

### ISSUE THREAD

**Issue by VincentGuyader** [ThinkR-open/golem#248]
use `golem::create_golem(path = ".",package_name = "nametrend")`

instead of golem::create_golem(path = ".",check_name = FALSE)

-> add a message to avoid 

  golem::add_resource_path(
    'www', system.file('app/www', package = '.')
  )

**Comment by ColinFay** [comment]
It's also FALSE when created from command line. 

And if you specify a non valid package_name with check_name false the DESCRIPTION is invalid

**Comment by VincentGuyader** [comment]
we may use `rstudioapi::getActiveProject()` as default name if `path='.'`

**Comment by ColinFay** [comment]
That won't work outside of RStudio though

**Comment by ColinFay** [comment]
I think we'd better use `{rprojroot}` there so that it also works when not in an RStudio project https://github.com/r-lib/rprojroot

**Comment by ColinFay** [comment]
I think there is something weird with the current implementation: 

```r 
> setwd("/tmp")
> dir.create("ppp")
> setwd("ppp")
The path . already exists, override?
1: I agree
2: Uhhhh... Maybe?
3: I forget

1

● Couldn't find golem working directory
✔ Definining golem working directory as `.`
You can change golem working directory with set_golem_wd('path/to/wd')
✔ Definining golem working directory as `/private/tmp/ppp`
A new golem package nametrend was created in /private/tmp/ppp/nametrend directory.
To continue work on your package start editing the 01_start.R file

> list.files()
[1] "DESCRIPTION" "dev"         "inst"        "man"         "NAMESPACE"   "R"          
> getwd()
[1] "/private/tmp/ppp"
> desc::desc("DESCRIPTION")
Package: nametrend
Title: An Amazing Shiny App
Version: 0.0.0.9000
Authors@R (parsed):
    * firstname lastname <your@email.com> [aut, cre]
Description: What the package does (one paragraph).
License: What license is it under?
Imports:
    golem,
    shiny
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.1.1
```

The fact that the package is created in `.`, the folder is said to exist already, so we override it in a sense but don't rename it 🤔

Well, that's kind of a fringe case so I'll be able to live with it for now 😛
