### ISSUE TITLE
golem::app_sys dont work with devtools_shims

### ISSUE THREAD

**Issue by VincentGuyader** [ThinkR-open/golem#258]
after running `devtools::load_all()`

`golem:::app_sys('app/www')` will return `""`

but 
`system.file('app/www', package = golem:::get_golem_name())`
[1] "D:/xxx/inst/app/www"

**Comment by ColinFay** [comment]
Ok issue here is the use of system.file inside the exported function, which is the base::system.file, not the one shimed by pkgload. 

That should work if app_sys is exported in the template, not in golem itself
