### ISSUE TITLE
Error with building package after using golem::add_dockerfile()

### ISSUE THREAD

**Issue by kuty-kajot** [ThinkR-open/golem#259]
Hi guys,
I encountered a weird behavior when building golem package. It might be due to my incomplete understanding of the whole process, tho. 

Basically, once I create a docker file using golem::add_dockerfile() I am unable to build a package using devtools::build() due to error occuring. Even if I remove the file and restart the R session, the same error occurs. The function golem::add_dockerfile() is merely establishing a  description file for docker building, right? It is not as if it was creating an image...? At the same time building package multiple times in a row does not result in any strangeness.

A sucessful build.
```
> devtools::build()
√  checking for file 'C:\Users\kuty.jiri\Documents\R\golgol/DESCRIPTION' (342ms)
-  preparing 'golgol':
√  checking DESCRIPTION meta-information ... 
-  installing the package to build vignettes
√  creating vignettes (2s)
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'golgol_0.0.0.9000.tar.gz'
   
[1] "C:/Users/kuty.jiri/Documents/R/golgol_0.0.0.9000.tar.gz"
> ## 5.2 If you want to deploy via a generic Dockerfile
```

Add dockerfile
```
> golem::add_dockerfile()
✔ Adding '^C:\\Users\\kuty\\.jiri\\Documents\\R\\golgol/Dockerfile$' to '.Rbuildignore'
√ Dockerfile created at Dockerfile
* Be sure to put your golgol_0.0.0.9000.tar.gz file (generated using `devtools::build()` ) in the same folder as the Dockerfile file generated
```

Build again with an error
```
> devtools::build()
√  checking for file 'C:\Users\kuty.jiri\Documents\R\golgol/DESCRIPTION' ...
-  preparing 'golgol':
√  checking DESCRIPTION meta-information ... 
   Warning in grepl(e, files, perl = TRUE, ignore.case = TRUE) :
     PCRE pattern compilation error
   	'PCRE does not support \L, \l, \N{name}, \U, or \u'
   	at 'Users\kuty\.jiri\Documents\R\golgol/Dockerfile$'
   Error in grepl(e, files, perl = TRUE, ignore.case = TRUE) : 
     invalid regular expression '^C:\Users\kuty\.jiri\Documents\R\golgol/Dockerfile$'
   Execution halted
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error
```

**Comment by ColinFay** [comment]
Hey, 

This is due to a bug in `golem::add_dockerfile()` which has been corrected in https://github.com/ThinkR-open/golem/pull/152

Can you change in your .Rbuildignore : 
`^C:\\Users\\kuty\\.jiri\\Documents\\R\\golgol/Dockerfile$`
to 
`^Dockerfile$`

And retry?

**Comment by kuty-kajot** [comment]
Thanks Colin! This solves the problem.
