### ISSUE TITLE
@param are missing in some R files inside shinyexample

### ISSUE THREAD

**Issue by VincentGuyader** [ThinkR-open/golem#288]
missing `@param request` here : 
>#' Application UI
>#'
>#' @import shiny
>app_ui <- function(request) {
>  tagList(

and missing `@param` here :  

>#' @import shiny
>app_server <- function(input, output,session) {
>  # List the first level callModules here
>}

**Comment by VincentGuyader** [comment]
the request parameters was here in a previous commit...

![image](https://user-images.githubusercontent.com/10470699/68990222-03f54400-0851-11ea-9da9-439e4bb646cc.png)

**Comment by ColinFay** [comment]
That was removed on purpose : app_ui is not exported so we don't need to document that param. 

 if ever we chose to document that, we need to document to app_server params too in order to be consistent in the way we promote the way golem elements are documented.

**Comment by VincentGuyader** [comment]
yes, but with this solution, you dont pass the check.
Im ok to use `noRd` but every parameters sould be documented
