### ISSUE TITLE
Refactor test files so each test file corresponds to proper R file

### ISSUE THREAD

**Issue by novica** [ThinkR-open/golem#291]
Discussion here: https://twitter.com/_ColinFay/status/1195741989502947329

**Comment by novica** [comment]
OK. Started working on this here: https://github.com/novica/golem/tree/issue-291

I also noticed that the test files begin with ```context()```

Didn't know what that was, but I checked and it seems it is no longer [necessary](https://www.rdocumentation.org/packages/testthat/versions/2.2.1/topics/context). Should I remove these lines completely?

**Comment by novica** [comment]
@ColinFay can you have a look at this? I think I have sorted out the filenames of test files so they correspond to filenames of R files.

**Comment by ColinFay** [comment]
Sorry for the late reply, I'll have a look over the weekend :)

For the context() I'd say yes, we've sticked to our old habits and used them but indeed they are not necessary anymore !

**Comment by ColinFay** [comment]
Looks good to me!

**Comment by novica** [comment]
Thank you @ColinFay. I really enjoy doing this.

**Comment by ColinFay** [comment]
Thanks a lot @novica for refactoring this!
