### ISSUE TITLE
How to enable bookmark restore?

### ISSUE THREAD

**Issue by rpodcast** [ThinkR-open/golem#30]
I am trying to implement Shiny's [bookmarkable state](http://shiny.rstudio.com/articles/bookmarking-state.html) feature in an app using `golem` and my only problem is with the restoring of bookmarks.  It's not clear to me how to get the `request` parameter necessary for the app's UI to be passed correctly to the downstream function creating the app UI.  The default function golem has for running the app does not take any arguments.  I've tried hacking around various parameters but haven not gotten far.  Any advice?

**Comment by rpodcast** [comment]
I forgot to update this, it turns out the issue was due to something else outside of golem's control, so I will close now

**Comment by ColinFay** [comment]
That has been quite an easy issue to fix :D
