### ISSUE TITLE
add covrpage to coverage pipeline

### ISSUE THREAD

**Issue by yonicd** [ThinkR-open/golem#31]
Is it possible to add {covrpage} to the code coverage pipeline in {golem}?

**Comment by ColinFay** [comment]
I think it could either go there: 
https://github.com/ThinkR-open/golem/blob/master/inst/shinyexample/dev/02_dev.R#L40
or there:
https://github.com/ThinkR-open/golem/blob/master/inst/shinyexample/dev/03_deploy.R#L5

**Comment by yonicd** [comment]
in `02_dev` for sure. 

practically it could also replace `devtools::test()` since that is run within `covrpage::covrpage()`
