### ISSUE TITLE
Deployment with shinyproxy

### ISSUE THREAD

**Issue by kuty-kajot** [ThinkR-open/golem#311]
Hi guys. 

I know it might not be a priority right now, but I am missing some training wheels when deploying golemized shiny as a docker inside shinyproxy. 
First of all do these directives still hold for golem https://rtask.thinkr.fr/shiny-application-in-production-with-shinyproxy-docker-and-debian/ ? I mean this matryoshka doll setup of docker inside shinyproxy inside docker :). 
Second, when I use the dockerized application inside shinyproxy, I get Timeout Error. It probably has to do with a fact, that when I run the example shinyproxy image, it runs the application actively listening on 3838:

`
> shinyproxy::run_01_hello()
Loading required package: shiny

Listening on http://0.0.0.0:3838
`

Whereas when I run golemized docker with default dockerfile configuration it shows only:

```
> options('shiny.port'=3838,shiny.host='0.0.0.0');
```

The dockerfile looks like this:

```
FROM rocker/tidyverse:3.6.1
RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_github("r-lib/remotes", ref = "97bbf81")'
RUN R -e 'remotes::install_cran("shiny")'
RUN R -e 'remotes::install_cran("golem")'
RUN R -e 'remotes::install_cran("htmltools")'
COPY golex_*.tar.gz /app.tar.gz
RUN R -e 'remotes::install_local("/app.tar.gz")'
EXPOSE 3838
CMD  ["R", "-e options('shiny.port'=3838,shiny.host='0.0.0.0'); golex::run_app()"]
```

Thanks!

**Comment by ColinFay** [comment]
Hey, 

Sorry for being late on this. 

Have you successfully deployed to ShinyProxy since?

**Comment by kuty-kajot** [comment]
Yeah, I did. It had to something to do with host address defined within the shiny app itself, if I remember correctly.

**Comment by ColinFay** [comment]
Ok glad to hear that then :) 

I'm closing the issue, thanks for taking the time to report!
