### ISSUE TITLE
should automatic additions to .Rbuildignore use forward slashes on windows ?

### ISSUE THREAD

**Issue by moodymudskipper** [ThinkR-open/golem#320]
`golem::add_dockerfile()` adds a line of code to `.Rbuildignore` but it uses backslashes which makes `devtools::build()` crash. In my case the line is `^C:\R\00 packages\kpiFRA/DESCRIPTION$` and `devtools::build()` 's error is :

```
devtools::build()
√  checking for file 'C:\R\00 packages\kpiFRA/DESCRIPTION' (546ms)
-  preparing 'kpiFRA': (884ms)
√  checking DESCRIPTION meta-information ... 
   Warning in grepl(e, files, perl = TRUE, ignore.case = TRUE) :
     PCRE pattern compilation error
   	'\k is not followed by a braced, angle-bracketed, or quoted name'
   	at 'kpiFRA/Dockerfile$'
   Error in grepl(e, files, perl = TRUE, ignore.case = TRUE) : 
     invalid regular expression '^C:\R\00 packages\kpiFRA/Dockerfile$'
   Execution halted
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error
```

It might be `devtools::build()` 's fault, but this is solved by changing the backward slashes to forward slashes so maybe it'd be more robust for you to write forward slashes by default ?

**Comment by ColinFay** [comment]
Thanks for this! 

This has been solved in newer version of `{golem}` :)

Cheers, 
Colin
