### ISSUE TITLE
add_ functions do not all have roxygen comments 

### ISSUE THREAD

**Issue by allaway** [ThinkR-open/golem#330]
Perhaps I'm missing something obvious, but is there any reason that `golem::add_fct`/`add_utils` does not add a roxygen comment section to the resulting file like `add_module` does to the module files?
It seems like it would be helpful to add this for parity across the `add_` functions and to encourage good documentation practices.

**Comment by allaway** [comment]
Related to #165

**Comment by ColinFay** [comment]
You're right, there should be roxygen tags here. 

Would you be willing to PR that? 
I think we should do this in the spirit of the way `add_module()` works https://github.com/ThinkR-open/golem/blob/dev/R/add_modules.R#L71 (i.e with an `export` parameter to the function)

**Comment by novica** [comment]
@ColinFay I would like to try to do this if no one is working on it.

My thinking is that first we should move

 ```    write_there <- function(...){
      write(..., file = where, append = TRUE)
    }  ```

from add_modules.R so it can be reused to utils.R.
and then modify add_modules and add_r_files accordingly.
Does this make sense?

**Comment by allaway** [comment]
Apologies for never following up on this, I intended to but it got lost in
the shuffle. @novica - I am not working on this, so there won't be
duplicated effort :)

Thanks for doing this!

**Comment by novica** [comment]
Maybe: https://github.com/ThinkR-open/golem/pull/525

**Comment by ColinFay** [comment]
This has been implemented in https://github.com/ThinkR-open/golem/commit/4fc81baf1f579de9630430451a8a4d9515cd3c49 :) 

Thanks everyone for the ideas and for contributing 🤘

**Comment by allaway** [comment]
Thanks so much, and my apologies for totally forgetting about trying to
tackle this!
