### ISSUE TITLE
golem fails to put inputs in URL

### ISSUE THREAD

**Issue by pachamaltese** [ThinkR-open/golem#335]
comparing https://github.com/tradestatistics/visualization-with-shiny/tree/master/embed-trade-golem and https://github.com/tradestatistics/visualization-with-shiny/tree/master/embed-trade I see that golem fails to work with reactive parameters and a URL that contains the "API call"

**Comment by ColinFay** [comment]
Hello, 

Can you point to the piece of code that works / doesn't work? 

Thanks

**Comment by pachamaltese** [comment]
@ColinFay yes :(

**Comment by ColinFay** [comment]
I'm not sure exactly where to look, could you point to the exact line in both code? 

Cheers,
colin

**Comment by pachamaltese** [comment]
thanks, let me rebuild the app and I'll be back

—————

*Mauricio Vargas Sepúlveda 帕夏*
Do you like Data Science? visit pacha.hk
你爱科学数据专吗？你走pacha.hk

**Comment by ColinFay** [comment]
Closing now, feel free to comment if you haven't solved it yet and I'll reopen :)
