### ISSUE TITLE
test to use `pkgload::load_all(export_all = FALSE)` in the app.R file for Rconnect deploy

### ISSUE THREAD

**Issue by VincentGuyader** [ThinkR-open/golem#341]
to mimic a proper package installation, instead of doing multiple `library`

**Comment by VincentGuyader** [comment]
seems ok :)

**Comment by cderv** [comment]
You may be interested to also set `helpers = FALSE` and `attach_testthat = FALSE` as you don't needs tests to run when running the app. right ? 🤷‍♂

**Comment by ColinFay** [comment]
I'd be in favor of writing a wrapper function instead of having all parameters set in the script

**Comment by VincentGuyader** [comment]
my understanding of `load_all` was wrong, we dont need this.
the actual call is good enough.

but maybe we can use `pkgload::load_all(export_all = FALSE,helpers = FALSE,attach_testthat = FALSE)`
