### ISSUE TITLE
Add empty line at the end of these files

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/golem#342]
This list of files spotted as warnings after using {packageMetrics2} means that we have to add a blank line at the end of the files.
`packageMetrics2::package_metrics("golem")`  
![image](https://user-images.githubusercontent.com/21193866/73363265-b8c3cc80-42a8-11ea-9128-c6d60b8aa606.png)

**Comment by lmeninato** [comment]
I'll give it a shot

**Comment by ColinFay** [comment]
Thanks @lmeninato! 

Here's a quick reminder about the process:

- fork the repo 
- create a branch with the number of your issue (for example `issue-342`)
- when PRing, be sure to do so in {golem} dev branch :) 

Thanks for the help!
