### ISSUE TITLE
Change setwd to here() in tests recommended

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/golem#350]
https://github.com/ThinkR-open/golem/blob/cc6ce097113400adc6f66c7f7a64597dd9187d74/inst/utils/test-golem-recommended.R#L25

Recommend to try: 
```r
        # As we are in the tests/testthat dir, we are moving 
        # to the root of the package before launching the whole package
        # and we try to launch the app
        "here::here(); pkgload::load_all(); run_app()"
```

Needs to be a Rstudio project though, otherwise set a file named ".here" at the root of the project.

**Comment by ColinFay** [comment]
AFAIK `here::here()` also looks for a DESCRIPTION file so it should be ok even if we're not in RStudio 🤔
