### ISSUE TITLE
Where to put config files

### ISSUE THREAD

**Issue by samWieczorek** [ThinkR-open/golem#363]
Hi,
In my shiny app, I need to use config files (*.conf) but I am not sure in which directory it is advised to put them. It seems to me that the 'www' directory in not the right place. Can I create a new directory in my package and add it in app_ui.R whith addRessource ?

Thanks

Sam

**Comment by ColinFay** [comment]
Hey Sam, 

There are two ways to refer to external files in `{golem}` based applications, depending on where you need them: 

- From the UI side, you can add files in inst/app/www, then the UI has access to it with `www/myfile.png`

- From the server side, you can add files in `inst` itself, then the UI has access to it with `app_sys("myfile.css")`

I suppose you need to use the config file from the server side, and in that case you can add it at `inst/`, next to the `golem-config.yml`.

**Comment by ColinFay** [comment]
Hey Sam, 

This seems solved, feel free to comment if you want this issue to be re-open :)
