### ISSUE TITLE
App with user-provided data

### ISSUE THREAD

**Issue by lcolladotor** [ThinkR-open/golem#364]
Hi,

I'm working on my first `golem` app post-`rstudio::conf(2020)` and I dug myself into a hole. The use case I have is similar to `iSEE::iSEE()` https://github.com/iSEE/iSEE/blob/master/R/iSEE-main.R where I was planning to enable users to explore their own input data (`se` object in the `iSEE` scenario). The main use case, however, is to showcase our data. The data is big enough that I won't store it inside the package itself, so `pkg::dataset` won't work for me (and well, wouldn't work for data from users) as it does in https://github.com/ThinkR-open/golem/issues/321#issuecomment-570251784. So I wrote a function called `fetch_data()` that pulls the data from the web. With this in mind, I modified `mypkg::run_app()` to have a few arguments (the data objects) and it currently looks like this:

```R
#' Run the Shiny Application
#'
#' @param sce
#' @param sce_layer
#' @param modeling_results
#' @param image_path
#' @param ...
#'
#' @export
#' @importFrom shiny shinyApp
#' @importFrom golem with_golem_options
run_app <- function(sce = fetch_data(type = 'sce'),
    sce_layer = fetch_data(type = 'sce_layer'),
    modeling_results = fetch_data(type = 'modeling_results'),
    image_path = system.file('app/www/data', package = 'spatialLIBD'),
    ...) {


    ## There has to be a better way than using global assignment here...
    ## https://ildiczeller.com/2017/08/09/shiny-app-as-r-package/ server has to be a function
    ## This is empty =(
    ## https://thinkr-open.github.io/building-shiny-apps-workflow/optimizing-shiny-code.html#reading-data


    # on_load <- function() {
        message(paste(Sys.time(), 'assigning data'))
        sce <<- sce
        sce_layer <<- sce_layer
        modeling_results <<- modeling_results
        image_path <<- image_path
    #     return(NULL)
    # }

    with_golem_options(app = shinyApp(ui = app_ui, server = app_server),
        golem_opts = list(...))
    # shinyApp(ui = app_ui, server = app_server, onStart = on_load)
    # shinyApp(ui = app_ui, server = app_server)

}
```

The main object, `sce` (similar to the `se` object from `iSEE`), is used by both the `ui` and `server` functions. Previously, this is something I was defining on `global.R`.

As you can see, I'm using global assignment to get the app to work. I tried the approach at [czeildi/shinypackage](https://github.com/czeildi/shinypackage) described in [this blog post](https://ildiczeller.com/2017/08/09/shiny-app-as-r-package/), which will work for the `ui` function, but not the `server` one. I also tried using the `onStart` argument from `shiny::shinyApp()` but I couldn't get that to work either even with the global assignments. 

Currently, the following code in `app.R` works though I think that there has to be a better way than using global assignment. Plus, I'm not even sure that `rsconnect::deployApp()` will work.

```R
pkgload::load_all()
options("golem.app.prod" = TRUE)

## will download the data automatically
# spatialLIBD::run_app()

## Easier to re-use the data
ori_sce <-
    fetch_data('sce', here::here('data-raw/spatialLIBD_files'))
ori_sce_layer <-
    fetch_data('sce_layer', here::here('data-raw/spatialLIBD_files'))
ori_modeling_results <-
    fetch_data('modeling_results',
        here::here('data-raw/spatialLIBD_files'))


spatialLIBD::run_app(sce = ori_sce,
    sce_layer = ori_sce_layer,
    modeling_results = ori_modeling_results) # add parameters here (if any)

## This adds 4 objects to the global enviornment
```

So, I was wondering, do you have any recommendations? The code at `iSEE` looks quite complicated :P 

## Solution?

Ahh.... I just found https://github.com/ThinkR-open/golem/issues/127#issuecomment-522167475 which might work. 

This is one of those cases where writing the issue leads to a possible solution :P Ok, I just tried it, and this works!  🎉 

```R
run_app <- function(...) {
    with_golem_options(app = shinyApp(ui = app_ui, server = app_server),
        golem_opts = list(...))
}

app_server <- function(input, output, session) {
    ## Get options
    sce <- golem::get_golem_options('sce')
    sce_layer <- golem::get_golem_options('sce_layer')
    modeling_results <- golem::get_golem_options('modeling_results')

    ## more code
    ## Example how I use the image_path argument in the end (from ui)
    ## which might not be the right thing to do... :P 
    pen <-
            png::readPNG(file.path(resourcePaths()['imagedata'], sampleid, 'tissue_lowres_image.png'))
    ## more code
}

app_ui <- function() {
    ## Get options
    sce <- golem::get_golem_options('sce')
    image_path <- golem::get_golem_options('image_path')

    tagList(
        # Leave this function for adding external resources
        golem_add_external_resources(image_path),

        ## more code
    )
}

golem_add_external_resources <- function(image_path) {
    addResourcePath('www', system.file('app/www', package = 'spatialLIBD'))
    addResourcePath('imagedata', image_path)

    tags$head(golem::activate_js(),
        golem::favicon()
    )
}
```

I only had to add the `image_path` argument to the `run_app()` call since it was a default before.

```R
pkgload::load_all()
options("golem.app.prod" = TRUE)

## will download the data automatically
# spatialLIBD::run_app()

## Easier to re-use the data
ori_sce <-
    fetch_data('sce', here::here('data-raw/spatialLIBD_files'))
ori_sce_layer <-
    fetch_data('sce_layer', here::here('data-raw/spatialLIBD_files'))
ori_modeling_results <-
    fetch_data('modeling_results',
        here::here('data-raw/spatialLIBD_files'))


spatialLIBD::run_app(sce = ori_sce,
    sce_layer = ori_sce_layer,
    modeling_results = ori_modeling_results,
    image_path = system.file('app/www/data', package = 'spatialLIBD')
) # add parameters here (if any)
```

I went ahead and re-added the default arguments to `run_app()` and explicitly passed the arguments and it works still without messing up the global environment.

```R
run_app <- function(sce = fetch_data(type = 'sce'),
    sce_layer = fetch_data(type = 'sce_layer'),
    modeling_results = fetch_data(type = 'modeling_results'),
    image_path = system.file('app/www/data', package = 'spatialLIBD'),
    ...) {
    
    with_golem_options(
        app = shinyApp(ui = app_ui, server = app_server),
        golem_opts = list(
            sce = sce,
            sce_layer = sce_layer,
            modeling_results = modeling_results,
            image_path = image_path,
            ...
        )
    )
    
}
```

Having written all this, I assume/hope that `rsconnect::deployApp()` will work. I'll figure this out once I get permission to make the app public. Prior to `golem` I was using

```R
library('rsconnect')
load('.deploy_info.Rdata')
rsconnect::setAccountInfo(name = deploy_info$name,
    token = deploy_info$token,
    secret = deploy_info$secret)
options(repos = BiocManager::repositories())
deployApp(
    appFiles = c(
        'ui.R',
        'server.R',
        'global.R',
        dir('data', full.names = TRUE, recursive = TRUE)
    ),
    appName = 'spatialLIBD',
    account = 'jhubiostatistics',
    server = 'shinyapps.io'
)
Y
```

I did notice that `x <- spatialLIBD::run_app()` now has way more stuff inside of it using `str(x)` (the data is stored in the `shiny.appobj` so I'm assuming that it will work.

Anyway, hopefully some of this and/or https://github.com/ColinFay/golemexample/blob/master/README.md#passing-arguments-to-run_app (I only found it thanks to https://github.com/ThinkR-open/golem/issues/127#issuecomment-522167475) could make it's way to  https://thinkr-open.github.io/building-shiny-apps-workflow/optimizing-shiny-code.html#reading-data. 

Best,
Leo

## Code and reproducibility

The app is at [LieberInstitute/spatialLIBD](https://github.com/LieberInstitute/spatialLIBD) and I'm will be made public soon (just waiting for approval). The app is deployed (a pre-`golem` version as I write this) at https://jhubiostatistics.shinyapps.io/spatialLIBD/.

```R
sessioninfo::session_info()
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.2 (2019-12-12)
 os       macOS Catalina 10.15.2      
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2020-02-19                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## truncated
  golem                    0.1      2019-08-05 [1] CRAN (R 3.6.0)   
```

**Comment by lcolladotor** [comment]
Hi, 

https://github.com/LieberInstitute/spatialLIBD is now public if you want to take a look. 

I have a question about how `golem` works with the data that gets passed. If I pass a large object, in my case I have a 2 GB one (from `pryr::object_size()`), does `golem::get_golem_options()` generate multiple copies of the object per connection to an R worker? 

I'm using terminology from https://docs.rstudio.com/shinyapps.io/applications.html#ApplicationPerformanceTuning as I try to find the best settings for https://jhubiostatistics.shinyapps.io/spatialLIBD/.

In any case, I'll likely close this issue since I found the solution myself while writing it.

Best,
Leo

**Comment by ColinFay** [comment]
@lcolladotor Woaw very sorry I didn't answer to this issue sooner. 

Yes, that's what `get_golem_options()` was thought for :) 
I agree that it's not documented though... would you be ok turning the content of this issue into a Wiki on the repo, so that we could point users to it? 
https://github.com/ThinkR-open/golem/wiki

That would be awesome. 

Cheers, 
Colin

**Comment by ColinFay** [comment]
This seems to have been solved :) 

Thanks for the details report. 

Cheers, 
Colin

**Comment by lcolladotor** [comment]
No problem Colin! And sorry, I haven't had the time to turn this issue into a Wiki.

Best,
Leo
