### ISSUE TITLE
Remove devtools explicit call 

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#371]
Devtools is called here but not imported and it shouldn't.

https://github.com/ThinkR-open/golem/blob/a222c5224d9dee2c4d8ac5635a109f4291cfcf19/R/add_deploy_helpers.R#L563

Switch to `pkgbuild::build` but that adds one dep

**Comment by ColinFay** [comment]
ping @VincentGuyader

**Comment by ColinFay** [comment]
As `{pkgbuild}` is an explicit import of `{pkgload}`, we can hack something with `getFromNamespace()`. 

We can also do something like :

``` r 
if (rlang::is.installed("pkgbuild")){
	pkgbuild::build()
} else {
	stop("please install {pkgbuild})
}
```

Number 2 seems like the best way to go.

**Comment by VincentGuyader** [comment]
Yes but :

> √  checking loading without being on the library search path (1.6s)
> W  checking dependencies in R code (1.6s)
>    '::' or ':::' import not declared from: 'pkgbuild'
> √  checking S3 generic/method consistency (3.3s)
> √  checking replacement functions (1.4s)

see https://github.com/ThinkR-open/golem/commit/5f8ca1da7a0375ba926ceeacf2e87b978bdb8fba

**Comment by VincentGuyader** [comment]
dirty way :

      if (rlang::is_installed("pkgbuild")) {
        getFromNamespace("build","pkgbuild")(path = ".")
      } else {
        stop("please install {pkgbuild}")
      }

**Comment by ColinFay** [comment]
@VincentGuyader as long we put `pkgbuild` in Suggests, that's good

https://github.com/ThinkR-open/golem/pull/380/commits/c212935516bc8031d8d411297401fc850be95d3c
