### ISSUE TITLE
favicon can't be online files

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#372]
`golem::use_favicon("https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/237/fire_1f525.png")`

```
Error: [ENOENT] Failed to copy '/Users/colin/Seafile/documents_colin/R/opensource/joburg1/https:/emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/237/fire_1f525.png' to '/Users/colin/Seafile/documents_colin/R/opensource/joburg1/inst/app/www/favicon.png': no such file or directory
```

**Comment by ColinFay** [comment]
ping @VincentGuyader

**Comment by ColinFay** [comment]
How to implement: 

+ Check if file exist locally, if it does, perform as already implemented

+ If it doesn't, check that it's reachable on the internet:

```
> x <- attempt::attempt(curlGetHeaders("http://doesnt/exi"), silent = TRUE)
> attempt::is_try_error(x)
[1] TRUE

> x <- attempt::attempt(curlGetHeaders("https://colinfay.me"), silent = TRUE)
> attempt::is_try_error(x)
[1] FALSE
> attr(x, 'status') == 200
[1] TRUE
```

+ If it's reachable, download the file from the web and perform as usual when it becomes a local file

**Comment by VincentGuyader** [comment]
If because of : https://github.com/ThinkR-open/golem/commit/9b5fb4d5cfc096ffede0b481a4a2bd7f14901cfd the change from `normalizePath` to `path_abs` , and because I didnt create an unit testing for this.
