### ISSUE TITLE
Add .rproj when using create_shiny_template

### ISSUE THREAD

**Issue by Cervangirard** [ThinkR-open/golem#38]
Using the create_shiny_template function, there is no.rproj to create in the folder.

May be add : 
``` 
 if (rstudioapi::isAvailable()) {
    rstudioapi::initializeProject(path)
  }
```

**Comment by ColinFay** [comment]
@Cervangirard that seems good to me on current version, do  you confirm ?

**Comment by Cervangirard** [comment]
Yes sir !
