### ISSUE TITLE
Suggested way to refer to external javascript files hosted on cdn

### ISSUE THREAD

**Issue by chintanp** [ThinkR-open/golem#396]
Often the external javascript libraries of interest are hosted on cdnjs like https://cdnjs.com/libraries/two.js/ and are considered as the faster way to load them. Is there a suggested way to use this using golem?

**Comment by ColinFay** [comment]
Hey, 

Sure, the best way to do this is to add a `tags$script(src= "")` inside `golem_add_external_resources()` at `app_ui.R#29`. 

I realise this is not documented, neither in the vignette nor inside the R file. 

I'll add this, unless you feel like doing a PR to include that ?

**Comment by chintanp** [comment]
Submitted a PR. Thanks.
