### ISSUE TITLE
Run devtools::check() with default unit tests in Rstudio build pane fail

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/golem#401]
I created a new golem:
```r
golem::create_golem("~/my.app")
```
Then, I directly use : `golem::use_recommended_tests()`

If I run `devtools::check()` in the console, unit tests are ok.
If I click on "Check" in the "Buld" pane of Rstudio, unit test fails:
```
 test_check("my.golem")
── 1. Failure: app launches (@test-golem-recommended.R#
x$is_alive() isn't true.
```

If I click on "Run Tests" on top right of the test file: 
![image](https://user-images.githubusercontent.com/21193866/77563910-2f083800-6ec2-11ea-9c0d-ce87a1964593.png)
Tests are executed in the pane and are ok

**Comment by jimbrig2011** [comment]
Have this same issue, except devtools::check does not work from the console for me either. The test works/passes with devtools::test or if I manually run the code in the test script but fails with devtools::check and RStudio build pane check.

**Comment by ColinFay** [comment]
Hey, 

This bug should have been corrected via #435. 

Can you confirm by reinstalling the current version of `{golem}` from GitHub, then run: 

``` r
packageVersion("golem") == "0.2.1.9010"
unlink("tests/testthat/test-golem-recommended.R")
golem::use_recommended_tests()
devtools::test()
devtools::check()
``` 

Thanks

**Comment by statnmap** [comment]
On windows : golem ‘0.2.1.9020’

Ok after my corrections in this PR: https://github.com/ThinkR-open/golem/pull/441

**Comment by ColinFay** [comment]
thanks!
