### ISSUE TITLE
Golem / RStudio : template not found

### ISSUE THREAD

**Issue by Welsh44** [ThinkR-open/golem#402]
Hi

I'm trying to use golem and follow this : https://thinkr-open.github.io/golem/articles/a_start.html

I'm using RStudio 1.0.143. Using File > New project I can't find hown to use Golem. I know I can use command line, but I'm trying golem in order to present this as a way of developing in my unit.

thanks in advance
Stay safe

**Comment by ColinFay** [comment]
Hey @Welsh44 

Have you installed golem on your machine ? 

If yes, can you try stopping RStudio and restart it ?

**Comment by Welsh44** [comment]
Hi @ColinFay 

Sorry for the lack of precision.
Windows 10, RStudio installed locally, stopped and restart.

Here are some sreenshots
- first screen after file > New Project
- after selecting new directory
- after selecting R Package
![Capture_03](https://user-images.githubusercontent.com/28830333/77660423-93d29980-6f79-11ea-8976-4798c1067e78.PNG) 

![Capture_01](https://user-images.githubusercontent.com/28830333/77660379-89180480-6f79-11ea-88b3-e6596cf351f4.PNG)
![Capture_02](https://user-images.githubusercontent.com/28830333/77660397-8e754f00-6f79-11ea-8e71-81fb2fc60dc7.PNG)

**Comment by VincentGuyader** [comment]
Hi, can you update your rstudio IDE?
You have an old version

**Comment by Welsh44** [comment]
OK. I'll try this update as soon as possible.

**Comment by ColinFay** [comment]
Hey, 

RStudio templates have been introduced in RStudio V1.1 : 
https://rstudio.github.io/rstudio-extensions/rstudio_project_templates.html

Updating the IDE should do the trick :) 

Otherwise, you can also create a golem template through command line: 

```
golem::create_golem()
```

Cheers, 
Colin

**Comment by Welsh44** [comment]
Hey

If templates have been introduced in v1.1, it's a good explanation to my issue 😆 

Installed nd check : it solved.

Thanks.
