### ISSUE TITLE
if (interactive()) {} in test_that( "app launches" )

### ISSUE THREAD

**Issue by novica** [ThinkR-open/golem#410]
I was building a demo app just to see how different parts of golem work.

When running the devtools::check() from 03_deploy.R I got an error that said: 
`Failure: app launches (@test-golem-recommende x$is_alive() isn't true.`

When running the `x <- processx::process$new()` I could verify that the app runs, `x$is_alive()` returned `TRUE` and I could access the app on localhost. 

After trying various things, I solved this issue with wrapping the test in `if (interactive()) {}`.
I don't know if this is something specific to my app. It's just an app that reads some data and makes a plot, so nothing fancy. So, I don't know if this is something that should be part of the default test or not, but reporting it just in case.

**Comment by ColinFay** [comment]
Hey @novica  

Thanks for the feedback. 

Indeed that's a known bug, I hadn't thought about using interactive(), that should indeed solve the problem, wrapping it inside `skip_if_not`, thanks for the idea!

**Comment by novica** [comment]
Hi @ColinFay 

Should I do a pull request for this then?

**Comment by ColinFay** [comment]
I think I'd like the whole testing to be wrapped inside a function so that it's cleaner in the testing files. 

Would you mind implementing something so that the test file looks like: 

```
test_that(
  "app launches",{
    expect_running(sleep = 5)
  }
)
```

So basically, wrapping this into a function?

``` r
skip_on_cran()
skip_on_travis()
skip_on_appveyor()
skip_if_not(interactive())
x <- processx::process$new(
	"R", 
	c(
	"-e", 
	"pkgload::load_all(here::here());run_app()"
	)
)
Sys.sleep(5)
expect_true(x$is_alive())
x$kill()
```

**Comment by novica** [comment]
Yes. I will work on in.

**Comment by novica** [comment]
How does this look @ColinFay ?
https://github.com/novica/golem/commit/4eac63b287dc40e3c6a1ef95e3cf17d96b7ea8f8

**Comment by ColinFay** [comment]
Thanks @novica ! 

Can you make it a `{golem}` function? 
I mean, instead of adding it to the test file itself, we should have it integrated to the package (so that we have `golem::expect_running()`? 
That would be easier to understand, as it would be lighter :)

**Comment by novica** [comment]
OK. I moved to test_helpers.R. I guess that's a good place for it? 

I am not sure if it should import anything though.

https://github.com/novica/golem/commit/afc8a15d588511baba6b93c66d1cefec641d8899

**Comment by ColinFay** [comment]
Yes, you should @importFrom function from {testthat} :) 

`#' @importFrom testthat skip_on_cran skip_on_travis skip_on_appveyor`

Have you tried this implementation on a brand new golem application?

**Comment by novica** [comment]
OK. I added the import.

Yes just tested. I did `devtools::install()` from my branch, and created a new app. Then I run `devtools::check()` got only one warning about missing license, which I didn't add. So I think it's OK? :)

**Comment by ColinFay** [comment]
Sounds good @novica, can you PR to dev? 

Thanks :)

**Comment by CorradoLanera** [comment]
I faced this issue today both with the CRAN and GH version.
I have solved, but I have two questions/purposes:

- if the `skip_on_*` are all inside `expect_running`, why the `skip_if_not(interactive())` is not? I think it could be more clear for the user (like me at least :-)) if the logic for "mandatory skips" is completely managed in a single place. My (not so strong) opinion is that they are quite mandatory for this expectation to run without errors, so they should be included in it (but "all outside" could be work as well).

- what about a switch to `skip_on_ci` to include all those skips in a single call (including GH-Actions too)?

Thank you!

**Comment by CorradoLanera** [comment]
@ColinFay, maybe this issue is not related to interactivity at all. I have supposed to have solved it, but that was not the case.

Clearly, using `skip_if_not(interactive))` "works" (the test does not fail, because it was not run :-)).

On the other hand, an interactive call is triggered with `CTRL + SHIFT + T` on RStudio, and without `skip_if_not(interactive))` it passed! using `skip_if_not(interactive))` is not run anymore by standard RStudio testing workflow.

I.e., it was during `CTRL + SHIFT + E` check executions only that it failed. I do not understand why during non-interactive `devtools::test` execution it passes, but not during the same tests called by the `devtools::check`.

So, maybe, `skip_if_not(interactive))` could be a sub-optimal solution: it avoids but not solve the issue, and it stops running the test quite every time it could be useful (user should go directly to call it manually at every app's change or run it in the current interactive session).

**Comment by CorradoLanera** [comment]
The problem is in the call
```
x <- processx::process$new(
      "R",
      c("-e", "pkgload::load_all(here::here());run_app()")
)
```

in particular, (I am conviced) in the usage of `here::here()` and in "where" CMD-check runs the tests.



## Step to reproduce the problem:

Removing `run_app()` and including a `Sys.sleep(60)` to be sure the process still running when tested (if no error occurred before)

```
expect_true({

    processx::process$is_alive
    x <- processx::process$new(
      "R",
      c("-e", "pkgload::load_all(here::here());Sys.sleep(60)"))
    cat(str(x))
    is_alive <- x$is_alive()
    x$kill()
    is_alive
  })
```

With `CTRL + SHIFT + T` the `cat`s returned 
```
Classes 'process', 'R6' PROCESS 'R', running, pid 1014781.
```



With `CTRL + SHIFT + E` the `cat`s returned
```
Classes 'process', 'R6' PROCESS 'R', finished.
```

So, that means that the call to `load_all()` returned an error (my best guess is that it does not find a package "`here::here()`").

**Comment by ColinFay** [comment]
Hey @CorradoLanera, 

thanks for exploring this. 
This is an issue about both here::here and testthat using a subprocess and a temp lib to run the test.  And the fact that there are 6 different ways to run the tests :)

I've spend way too much time solving this and it should be good with the current dev version of golem, as of https://github.com/ThinkR-open/golem/commit/eec0d21f8f95a93f4dfdc083796052f19a0738fe

You can find more details here https://github.com/ThinkR-open/golem/blob/dev/R/test_helpers.R#L71

can you try with the dev version (remotes::install_github("thinkr-open/golem", ref = "dev") ) of golem and let me know ?

Colin

**Comment by CorradoLanera** [comment]
I don't know if there is some option to recover the package root from all the possible places (check path included). For the moment, I use the following solution:

```
is_pkg <- function() {
    pkg_root <- tryCatch(
      rprojroot::find_package_root_file(path = here::here()),
      error = function(e) NULL
    )
    !is.null(pkg_root)
  }

  skip_if_not(is_pkg())
```

That skips the test on tests triggered by the check but runs it during standard tests

**Comment by CorradoLanera** [comment]
@ColinFay,  that was the output:

```
Warning (test-golem-recommended.R:16:3): app launches
path[1]="/usr/lib/R/R": No such file or directory
Backtrace:
  1. golem::expect_running(5) test-golem-recommended.R:16:2
 14. base::normalizePath(file.path(Sys.getenv("R_HOME"), "R"))

Error (test-golem-recommended.R:16:3): app launches
Error: cannot start processx process '/usr/lib/R/R' (system error 2, No such file or directory) @unix/processx.c:602 (processx_exec)
Backtrace:
  1. golem::expect_running(5) test-golem-recommended.R:16:2
  8. base::.handleSimpleError(...)
  9. h(simpleError(msg, call))
 10. throw(e)
```


It worked for me changing the `command` value to both the `processx::process$new` call into

```
command = normalizePath(file.path(Sys.getenv("R_HOME"), "bin", "R"))
```


### --- Session info ---
``` 
 setting  value                        
 version  R version 4.0.3 (2020-10-10) 
 os       Debian GNU/Linux bullseye/sid
 system   x86_64, linux-gnu            
 ui       RStudio                      
 language en_US:it                     
 collate  en_US.UTF-8                  
 ctype    en_US.UTF-8                  
 tz       Europe/Rome                  
 date     2021-02-06  
```


### --- Packages ---

```
package      * version date       lib source
 assertthat     0.2.1   2019-03-21 [1] CRAN (R 4.0.2)                             
 attempt        0.3.1   2020-05-03 [1] CRAN (R 4.0.2)                             
 autotestthat * 0.1.1   2020-10-01 [1] Github (Corradolanera/autotestthat@c54fe30)
 cachem         1.0.3   2021-02-04 [1] RSPM (R 4.0.3)                             
 callr          3.5.1   2020-10-13 [1] RSPM (R 4.0.3)                             
 cli            2.3.0   2021-01-31 [1] RSPM (R 4.0.3)                             
 config         0.3.1   2020-12-17 [1] RSPM (R 4.0.3)                             
 covr         * 3.5.1   2020-09-16 [1] CRAN (R 4.0.2)                             
 crayon         1.4.0   2021-01-30 [1] RSPM (R 4.0.3)                             
 desc           1.2.0   2018-05-01 [1] CRAN (R 4.0.2)                             
 devtools     * 2.3.2   2020-09-18 [1] CRAN (R 4.0.2)                             
 digest         0.6.27  2020-10-24 [1] RSPM (R 4.0.3)                             
 dockerfiler    0.1.3   2019-03-19 [1] CRAN (R 4.0.2)                             
 ellipsis       0.3.1   2020-05-15 [1] CRAN (R 4.0.2)                             
 fastmap        1.1.0   2021-01-25 [1] RSPM (R 4.0.3)                             
 fortunes       1.5-4   2016-12-29 [1] CRAN (R 4.0.2)                             
 fs             1.5.0   2020-07-31 [1] CRAN (R 4.0.2)                             
 glue           1.4.2   2020-08-27 [1] CRAN (R 4.0.2)                             
 golem          0.3.0   2021-02-06 [1] Github (thinkr-open/golem@281fc5d)         
 htmltools      0.5.1.1 2021-01-22 [1] RSPM (R 4.0.3)                             
 httpuv         1.5.5   2021-01-13 [1] RSPM (R 4.0.3)                             
 jsonlite       1.7.2   2020-12-09 [1] RSPM (R 4.0.3)                             
 knitr          1.31    2021-01-27 [1] CRAN (R 4.0.3)                             
 later          1.1.0.1 2020-06-05 [1] CRAN (R 4.0.2)                             
 lazyeval       0.2.2   2019-03-15 [1] CRAN (R 4.0.2)                             
 lifecycle      0.2.0   2020-03-06 [1] CRAN (R 4.0.2)                             
 magrittr       2.0.1   2020-11-17 [1] RSPM (R 4.0.3)                             
 memoise        2.0.0   2021-01-26 [1] RSPM (R 4.0.3)                             
 mime           0.9     2020-02-04 [1] CRAN (R 4.0.2)                             
 pkgbuild       1.2.0   2020-12-15 [1] RSPM (R 4.0.3)                             
 pkgload        1.1.0   2020-05-29 [1] CRAN (R 4.0.2)                             
 prettyunits    1.1.1   2020-01-24 [1] CRAN (R 4.0.2)                             
 processx       3.4.5   2020-11-30 [1] RSPM (R 4.0.3)                             
 promises       1.1.1   2020-06-09 [1] CRAN (R 4.0.2)                             
 ps             1.5.0   2020-12-05 [1] RSPM (R 4.0.3)                             
 purrr          0.3.4   2020-04-17 [1] CRAN (R 4.0.2)                             
 R6             2.5.0   2020-10-28 [1] RSPM (R 4.0.3)                             
 Rcpp           1.0.6   2021-01-15 [1] CRAN (R 4.0.3)                             
 remotes        2.2.0   2020-07-21 [1] CRAN (R 4.0.2)                             
 rex            1.2.0   2020-04-21 [1] CRAN (R 4.0.2)                             
 rlang          0.4.10  2020-12-30 [1] CRAN (R 4.0.3)                             
 roxygen2       7.1.1   2020-06-27 [1] CRAN (R 4.0.2)                             
 rprojroot      2.0.2   2020-11-15 [1] RSPM (R 4.0.3)                             
 rstudioapi     0.13    2020-11-12 [1] RSPM (R 4.0.3)                             
 sessioninfo    1.1.1   2018-11-05 [1] CRAN (R 4.0.2)                             
 shiny          1.6.0   2021-01-25 [1] RSPM (R 4.0.3)                             
 stringi        1.5.3   2020-09-09 [1] RSPM (R 4.0.3)                             
 stringr        1.4.0   2019-02-10 [1] CRAN (R 4.0.2)                             
 testthat     * 3.0.1   2020-12-17 [1] RSPM (R 4.0.3)                             
 usethis      * 2.0.0   2020-12-10 [1] RSPM (R 4.0.3)                             
 withr          2.4.1   2021-01-26 [1] RSPM (R 4.0.3)                             
 xfun           0.20    2021-01-06 [1] RSPM (R 4.0.3)                             
 xml2           1.3.2   2020-04-23 [1] CRAN (R 4.0.2)                             
 xtable         1.8-4   2019-04-21 [1] CRAN (R 4.0.2)                             
 yaml           2.2.1   2020-02-01 [1] CRAN (R 4.0.2) 

[1] /home/cl/R/x86_64-pc-linux-gnu-library/4.0
[2] /usr/local/lib/R/site-library
[3] /usr/lib/R/site-library
[4] /usr/lib/R/library
```
