### ISSUE TITLE
Golem changelog seems outdated

### ISSUE THREAD

**Issue by cderv** [ThinkR-open/golem#414]
Hi, 

In the website, the changelog page does not have the last released versions
https://thinkr-open.github.io/golem/news/index.html

Golem 0.2.1 is already on cran, as Golem 0.2.0 was before but none is really documented in the changelog page. only 0.1.9000+ and 0.2.9000+ with _Unreleased_ noted near the title. 

As the [NEWS file](https://github.com/ThinkR-open/golem/blob/master/NEWS.md) seems up to date for your release process, it could just be a compatibility issue with how pkgdown understand the versionning. 

However, I can add that 0.x.9000+ is not easy to understand - so I am really not if this is an issue, or it means everything above 0.x version. 🤷 

Cheers !

**Comment by ColinFay** [comment]
Seems good :) 

The pkgdown is built using the `dev` branch 🤘
