### ISSUE TITLE
Dockerfile dont build anymore

### ISSUE THREAD

**Issue by VincentGuyader** [ThinkR-open/golem#418]
> Step 7/13 : RUN Rscript -e 'remotes::install
> _version("golem",upgrade="never", version =
> "0.2.1")'
>  ---> Running in da742c76dc97
> Downloading package from url: https://cran.r
> studio.com/src/contrib/golem_0.2.1.tar.gz
> Error in vapply(remote, function(x) remote_s
> ha(x), character(1)) :
>   values must be length 1,
>  but FUN(X[[52]]) result is length 110
> Calls: <Anonymous> ... dev_package_deps -> c
> ombine_deps -> nrow -> package_deps -> vappl
> y
> Execution halted
> The command '/bin/sh -c Rscript -e 'remotes:
> :install_version("golem",upgrade="never", ve
> rsion = "0.2.1")'' returned a non-zero code:
>  1

**Comment by Cervangirard** [comment]
I had the same problem. By removing the dev version of remotes, the dockerfile compiles without problem.

**Comment by ShahnurIslam** [comment]
> I had the same problem. By removing the dev version of remotes, the dockerfile compiles without problem.

Thanks Cervan, that helped me!

**Comment by ColinFay** [comment]
Seems to be good right now. 

Issues with versions that solved themselves with time :)
