### ISSUE TITLE
Unable to view PDF file (inst/app/www) by using [tags$iframe] and [addResourcePath]

### ISSUE THREAD

**Issue by robertoromor** [ThinkR-open/golem#419]
- I am trying to view local pdf files using the golem. 

So as the demo mention I use addResourcePath in my app_ui.R file

golem_add_external_resources <- function(){
  

```
  addResourcePath(
    'www', system.file('app/www', package = 'rappExt')
  )
  
}
```

- I have a pdf saved in rappExt/inst/app/www

- Inside the module I am trying to view the local pdf like this without any success:

```
    output$test_results<-renderUI({
       
      tags$iframe(style = "height:1400px; width:100%", src = "www/file_name.pdf")
      
    })
```

I have tried different combinations of folders paths but still unable to view  any pdf files.

Is your framework capable of viewing pdf files and if so what am I doing wrong.

Best,

**Comment by ColinFay** [comment]
I tried your exact code and it works here. 

__NOTE that it won't show in RStudio default panel__

Can you share the whole application code?

**Comment by ColinFay** [comment]
![Screenshot 2020-05-01 at 16 09 38](https://user-images.githubusercontent.com/17936236/80811660-a2d6e800-8bc6-11ea-83fa-c354f7669290.png)

```r 
#' The application User-Interface
#' 
#' @param request Internal parameter for `{shiny}`. 
#'     DO NOT REMOVE.
#' @import shiny
#' @noRd
app_ui <- function(request) {
  tagList(
    # Leave this function for adding external resources
    golem_add_external_resources(),
    # List the first level UI elements here 
    fluidPage(
      uiOutput("pdf")
    )
  )
}

#' Add external Resources to the Application
#' 
#' This function is internally used to add external 
#' resources inside the Shiny application. 
#' 
#' @import shiny
#' @importFrom golem add_resource_path activate_js favicon bundle_resources
#' @noRd
golem_add_external_resources <- function(){
  
  add_resource_path(
    'www', app_sys('app/www')
  )
 
  tags$head(
    favicon(),
    bundle_resources(
      path = app_sys('app/www'),
      app_title = 'golempdf'
    )
    # Add here other external resources
    # for example, you can add shinyalert::useShinyalert() 
  )
}


```

```r 
#' The application server-side
#' 
#' @param input,output,session Internal parameters for {shiny}. 
#'     DO NOT REMOVE.
#' @import shiny
#' @noRd
app_server <- function( input, output, session ) {
  # List the first level callModules here
  output$pdf <- renderUI({
    tags$iframe(style = "height:1400px; width:100%", src = "www/sample.pdf")
  })
}

```

**Comment by robertoromor** [comment]
I missed the **bundle resources** and that did the trick. Thanks a lot!!

**Comment by robertoromor** [comment]
I am tryng to deploy the app using docker and shiny proxy and getting this error

^[[AError: 'bundle_resources' is not an exported object from 'namespace:golem'

I suppose the golem version that I am using is behind the golem version that has this function

This is the one that I have in my containerX right now

 sudo docker run -p  containerX R -e 'packageVersion("golem")'

 packageVersion("golem")
[1] ‘0.1’

and in local RStudio my package version is 

 packageVersion("golem")
[1] ‘0.2.1’

I tried installing the new version using this:

sudo docker run -p containerX R -e 'install.packages("golem")' 

and it does not do update

It seems like a question I should be posting in a docker thread but its worth asking if you have any advice for this?

**Comment by ColinFay** [comment]
bundle_resources comes with golem version 0.2.0, so if your container has 0.1.0 it won't work :)

To correct that, I suggest you edit your Dockerfile so that it install the correct version

**Comment by VincentGuyader** [comment]
If `install.packages("golem")` dont install the last version of golem, it maybe because the repos you use is an MRAN snapshot.

See `options('repos')` to check that

Regards

**Comment by robertoromor** [comment]
Yeah that's the answer (MRAN snapshot) I got from the docker community. 

Thanks!
