### ISSUE TITLE
Add `overwrite` argument to `create_golem`

### ISSUE THREAD

**Issue by antoine-sachet** [ThinkR-open/golem#424]
Trying to run `create_golem` on an existing directory in a non-interactive session fails with 

```
Rscript -e  "golem::create_golem('.')"
# The path . already exists, override?Error in menu(c("Yes", "No")) : menu() cannot be used non-interactively
```

Indeed, if the path already exists the user is prompted with `yesno` which only works in an interactive session.

It would be great to add an `overwrite` argument to allow overwriting in non-interactive sessions.

**Comment by ColinFay** [comment]
Linked issue : #101 and #100 

Right now this behavior has been fixed for the `add_*` files but indeed is still there for `create_`.

@antoine-sachet would you be willing to make a PR?

**Comment by antoine-sachet** [comment]
I have made the change already actually, just haven't done the PR because it ended up a bit larger than I thought. 

For a complete logic, there should be 3 valid values: NULL (default) prompts the user, TRUE overwrites if needed and FALSE stops if the directory already exists.

If the session is not interactive and overwrite is NULL, we should also stop if the directory already exists.

That was more if/else than I had imagined and I wasn't sure the NULL/T/F logic was consistent with the rest of the code, which is why I held off on the PR.

What do you think?

**Comment by ColinFay** [comment]
Implemented in https://github.com/ThinkR-open/golem/pull/777
