### ISSUE TITLE
`add_dockerfile_*` uses `install_github` for non-github remote dependencies

### ISSUE THREAD

**Issue by antoine-sachet** [ThinkR-open/golem#425]
The internal function creating the dockerfile `docker_from_desc` always uses `remotes::install_github` for any non-cran dependencies. But there's more than github!

Our company uses `bitbucket` but `gitlab` is also pretty common. Mind you, you're not the only ones to be github-centric - I have already fixed the same issues in `usethis` and others.

The `Remote` information is actually in the package description, so handling more providers is as easy as doing:

``` r
install_fun <- function(remote) {
  remote <- tolower(remote)
  ifelse(tolower(remote) %in% c("github", "bitbucket", "gitlab"),
           paste0("remote::install_", remote),
           "# Could not generate install code for: ")
}

install_fun("Bitbucket")
#> [1] "remote::install_bitbucket"
install_fun("Github")
#> [1] "remote::install_github"
```

From there it is easy to adapt `golem:::dock_from_desc`. I'll prepare a PR when I have some time.

**Comment by Ajuajmal** [comment]
I just checked the fork by @antoine-sachet, I didn't find any updates related to this issue.
So I would like to try this issue. 
I'm planned to implement as per the solution suggested by @antoine-sachet :-

**Comment by ColinFay** [comment]
Hey,

All docker-related functions have moved to [{dockerfiler}](https://github.com/ColinFay/dockerfiler).

We'll keep track of the issues here.
