### ISSUE TITLE
golem::add_module js argument 

### ISSUE THREAD

**Issue by MayaGans** [ThinkR-open/golem#447]
I was wondering if it'd be possible to add a js file argument to `golem::add_module` so that a `.js` will be created with the same naming conventions? For example:

`golem::add_module("01_import", fct = "readr", utils = "ui", js = "script")` will give you something like: 

- `R/mod_01_import.R`
- `R/mod_01_import_fct_readr.R`
- `R/mod_01_import_utils_ui.R`
- `app/www/mod_01_script.js` _not exactly sure this is where it would go but I think you get the idea 😊_

Thanks again for this awesome package!!!

**Comment by novica** [comment]
Is this issue as simple as this: https://github.com/novica/golem/commit/8812dae93ce5e87ad204819e2721f58f6de0eb7c or am I missing something?

**Comment by novica** [comment]
This should be closed right?

**Comment by ColinFay** [comment]
Implemented, closing now :) 

Thanks @novica
