### ISSUE TITLE
callModule() vs moduleServer

### ISSUE THREAD

**Issue by julianstanley** [ThinkR-open/golem#455]
Golem-initialized modules use `callModule()`. 

Upcoming shiny features include some nifty testing functions--mainly `testServer()` that do not work with `callModule()`.

In the `?shiny::moduleServer` entry from shiny 1.4.0.9003:

> Starting in Shiny 1.5.0, we recommend using moduleServer instead of callModule(), because the syntax is a little easier to understand, and modules created with moduleServer can be tested with testServer().

Because of that recommendation, I'm considering changing the syntax for all of my modules. 

Should `golem` change the way that it creates modules? I'm still pretty new to this, so I'm not sure if there's a good argument for keeping the `callModule()` format.

**Comment by ColinFay** [comment]
Hey! 

Thanks for this :) 

It's been on my todo for a couple of weeks, I think the easiest way to do it would be to check shiny version and change what we add to the users built modules. 

Something like 

```
if (packageVersion("shiny") > "1.5") 
```

So yeah we will switch to this new syntax once it's ready :)

**Comment by ColinFay** [comment]
@julianstanley, I've open a discussion about this on #486, would you be ok sharing your thoughts on this?

**Comment by ColinFay** [comment]
Thanks again @julianstanley !

This has been solved https://github.com/ThinkR-open/golem/blob/dev/R/add_modules.R#L205

**Comment by jordancampbell23** [comment]
@ColinFay Previously, when wanting to utilize an input from the app_ui within a module, I would do the following on the app_server:

`r <- reactiveValues()

observeEvent( input$var , {
r$var <- input$var
})

callModule(mod_mod1_server, "mod1_ui_1", **r = r**)
`

Is this possible within the new mod_mod1_server("mod_mod1_server")?


Thanks!

**Comment by Cervangirard** [comment]
hello, yes, no problem with the new way :
here a example of rv with modules 
https://github.com/Cervangirard/bddshow/blob/cf08bffad0471789c187efd71e234edf90e59236/R/mod_database_app.R#L75
https://github.com/Cervangirard/bddshow/blob/cf08bffad0471789c187efd71e234edf90e59236/R/mod_all_annee.R#L44

```
# inside the module
mod_mod1_server <- function(id, r) {
  moduleServer(id, function(input, output, session) {
    observeEvent(input$example,{
      r$plot <- plot(iris)
   })
  })
}

# inside the app_server
mod_mod1_server("mod1_ui_1", r = r)

```
