### ISSUE TITLE
Interface Golem and ShinyManager

### ISSUE THREAD

**Issue by artpulsion** [ThinkR-open/golem#460]
Hi ThinkR, 

Thanks a lot for this wonderful framework, since I use it I really see Shiny app development as a solid manner of creating useful and robust interface. 

I would love to know if there is any documentation about interfacing golem structure and shinymanager which is a package I use frequently to secure my app. The shinymanager workflow proposed on their github works well with a Ui.R / Server.R arborescence by wrapping the UI object in the secure_app() function and calling the server part to get the credentials, which in my case is a database called ‘credentials.sqlite’ stored on the package directory. 

Do you have any snippets for that ? 

Thanks you very much.

**Comment by ColinFay** [comment]
Hey @artpulsion 

Please refer to https://stackoverflow.com/questions/62640864/interfacing-shinymanager-and-golem/63082204#63082204 and https://github.com/ColinFay/golemshinymanager for an example :) 

Thanks for your question, 
Cheers, 
Colin
