### ISSUE TITLE
Multiple Repos in the add_dockerfile

### ISSUE THREAD

**Issue by ArthurPERE** [ThinkR-open/golem#462]
Hello, 

I remark that when we have multiple repository (BioConductor + CRAN) inside the repos options for all the add_dockerfile*, the comportement is to make the dockerfile with this : 

```
RUN echo "options(repos = c(CRAN = 'https://bioconductor.org/packages/3.10/bioc'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site
RUN echo "options(repos = c(CRAN = 'https://bioconductor.org/packages/3.10/data/annotation'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site
RUN echo "options(repos = c(CRAN = 'https://bioconductor.org/packages/3.10/data/experiment'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site
RUN echo "options(repos = c(CRAN = 'https://bioconductor.org/packages/3.10/workflows'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site
RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.com'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site
```

It should be in one line with different names than CRAN, the function BiocManager::repositories() is to be considered.

I think the function to modify is "dock_from_desc".

Thank you
Arthur

**Comment by VincentGuyader** [comment]
hi

thanks a lot I will correct this !


Regards

**Comment by VincentGuyader** [comment]
@ArthurPERE can you check using 
`remotes::install_github("thinkr-open/golem",ref="issue_462")`  

?


regards

**Comment by ArthurPERE** [comment]
Hello,

It's working perfectly fine. 

Thank you,
Regards
