### ISSUE TITLE
Image build problem for shinyproxy

### ISSUE THREAD

**Issue by AMillanFL** [ThinkR-open/golem#464]
Hello,

I just switch to R4.0.0 and new Rstudio. I used to build golem apps docker image on my OVH server with previous version of R and linked packages. I try with the new versions and I have several probems. The last of all is an issue during last steps of the build.

Here is may dockerfile :
`FROM rocker/r-ver:4.0.0
RUN apt-get update && apt-get install -y  git-core libcurl4-openssl-dev libgit2-dev libssh2-1-dev libssl-dev libxml2-dev make pandoc pandoc-citeproc zlib1g-dev && rm -rf /var/lib/apt/lists/*
RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site
RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_github("r-lib/remotes", ref = "97bbf81")'
RUN Rscript -e 'remotes::install_version("config",upgrade="never", version = "0.3")'
RUN Rscript -e 'remotes::install_version("golem",upgrade="never", version = "0.2.1")'
RUN Rscript -e 'remotes::install_version("shiny",upgrade="never", version = "1.4.0.2")'
RUN Rscript -e 'remotes::install_version("attempt",upgrade="never", version = "0.3.1")'
RUN Rscript -e 'remotes::install_version("DT",upgrade="never", version = "0.13")'
RUN Rscript -e 'remotes::install_version("glue",upgrade="never", version = "1.4.1")'
RUN Rscript -e 'remotes::install_version("htmltools",upgrade="never", version = "0.4.0")'
RUN Rscript -e 'remotes::install_version("shinyjs",upgrade="never", version = "1.1")'
RUN Rscript -e 'remotes::install_version("dplyr",upgrade="never", version = "1.0.0")'
RUN Rscript -e 'remotes::install_version("stringr",upgrade="never", version = "1.4.0")'
RUN Rscript -e 'remotes::install_version("readr",upgrade="never", version = "1.3.1")'
RUN Rscript -e 'remotes::install_version("purrr",upgrade="never", version = "0.3.4")'
RUN Rscript -e 'remotes::install_version("magrittr",upgrade="never", version = "1.5")'
RUN Rscript -e 'remotes::install_version("knitr",upgrade="never", version = "1.28")'
RUN Rscript -e 'remotes::install_version("rmarkdown",upgrade="never", version = "2.2")'
RUN mkdir /build_zone
ADD . /build_zone
WORKDIR /build_zone
RUN R -e 'remotes::install_local(upgrade="never")'
EXPOSE 3838
CMD  ["R", "-e", "options('shiny.port'=3838,shiny.host='0.0.0.0');myApp::run_app()"]` 

And the error message on step 24/26 RUN R -e 'remotes::install_local(upgrade="never")' :
`Error in read.dcf(path) : cannot open the connection
Calls: <Anonymous> ... remote_package_name.local_remote -> read_dcf -> colnames -> is.data.frame -> read.dcf
In addition: Warning message:
In read.dcf(path) :
  cannot open compressed file '/build_zone/DESCRIPTION', probable reason 'No such file or directory'
Execution halted
The command '/bin/sh -c R -e 'remotes::install_local(upgrade="never")'' returned a non-zero code: 1`

All the previous steps run well.
The dockerfile was generated by golem::add_dockerfile_shinyproxy()

Here my DESCRIPTION file :
`Package: myApp
Title: My App
Version: 0.0.0.9000
Authors@R: person('A_____', 'M_____', email = 'a.m____@______.com', role = c('cre', 'aut'))
Description: Tool blablabla. Use blablabla.
License: MIT + file LICENSE
Imports: 
    config,
    golem,
    shiny,
    attempt,
    DT,
    glue,
    htmltools,
    shinyjs,
    dplyr,
    stringr,
    readr,
    purrr,
    magrittr
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.1.0
Suggests: 
    knitr,
    rmarkdown
VignetteBuilder: knitr`

If someone can help me cause I'm stuck. Thanks

**Comment by VincentGuyader** [comment]
Hi, 

I tried to run your Dockerfile : 

```
FROM rocker/r-ver:4.0.0 
RUN apt-get update && apt-get install -y git-core libcurl4-openssl-dev libgit2-dev libssh2-1-dev libssl-dev libxml2-dev make pandoc pandoc-citeproc zlib1g-dev && rm -rf /var/lib/apt/lists/* 
RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site 
RUN R -e 'install.packages("remotes")' 
RUN R -e 'remotes::install_github("r-lib/remotes", ref = "97bbf81")' 
RUN Rscript -e 'remotes::install_version("config",upgrade="never", version = "0.3")' 
RUN Rscript -e 'remotes::install_version("golem",upgrade="never", version = "0.2.1")' 
RUN Rscript -e 'remotes::install_version("shiny",upgrade="never", version = "1.4.0.2")' 
RUN Rscript -e 'remotes::install_version("attempt",upgrade="never", version = "0.3.1")' 
RUN Rscript -e 'remotes::install_version("DT",upgrade="never", version = "0.13")' 
RUN Rscript -e 'remotes::install_version("glue",upgrade="never", version = "1.4.1")' 
RUN Rscript -e 'remotes::install_version("htmltools",upgrade="never", version = "0.4.0")' 
RUN Rscript -e 'remotes::install_version("shinyjs",upgrade="never", version = "1.1")' 
RUN Rscript -e 'remotes::install_version("dplyr",upgrade="never", version = "1.0.0")' 
RUN Rscript -e 'remotes::install_version("stringr",upgrade="never", version = "1.4.0")' 
RUN Rscript -e 'remotes::install_version("readr",upgrade="never", version = "1.3.1")' 
RUN Rscript -e 'remotes::install_version("purrr",upgrade="never", version = "0.3.4")' 
RUN Rscript -e 'remotes::install_version("magrittr",upgrade="never", version = "1.5")' 
RUN Rscript -e 'remotes::install_version("knitr",upgrade="never", version = "1.28")' 
RUN Rscript -e 'remotes::install_version("rmarkdown",upgrade="never", version = "2.2")' 
RUN mkdir /build_zone ADD . /build_zone WORKDIR /build_zone 
RUN R -e 'remotes::install_local(upgrade="never")' 
EXPOSE 3838 CMD ["R", "-e", "options('shiny.port'=3838,shiny.host='0.0.0.0');myApp::run_app()"]
```

there is only 23 step, and i dont have any error during `docker build .`

can you check ?

**Comment by AMillanFL** [comment]
Thanks for your answer,
The 26 steps came from the script `golem::add_dockerfile_shinyproxy()` the returns are not place like in your code.

I try but still have an error but it's not the same.
Step 21/23 : RUN mkdir /build_zone ADD . /build_zone WORKDIR /build_zone
 ---> Running in 42c039c1c784
mkdir: cannot create directory ‘.’: File exists
mkdir: cannot create directory ‘/build_zone’: File exists
mkdir: cannot create directory ‘/build_zone’: File exists

there is not buid_zone dir already existing in the directory I use.

**Comment by AMillanFL** [comment]
> 
> 
> Hi,
> 
> I tried to run your Dockerfile :
> 
> ```
> FROM rocker/r-ver:4.0.0 
> RUN apt-get update && apt-get install -y git-core libcurl4-openssl-dev libgit2-dev libssh2-1-dev libssl-dev libxml2-dev make pandoc pandoc-citeproc zlib1g-dev && rm -rf /var/lib/apt/lists/* 
> RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site 
> RUN R -e 'install.packages("remotes")' 
> RUN R -e 'remotes::install_github("r-lib/remotes", ref = "97bbf81")' 
> RUN Rscript -e 'remotes::install_version("config",upgrade="never", version = "0.3")' 
> RUN Rscript -e 'remotes::install_version("golem",upgrade="never", version = "0.2.1")' 
> RUN Rscript -e 'remotes::install_version("shiny",upgrade="never", version = "1.4.0.2")' 
> RUN Rscript -e 'remotes::install_version("attempt",upgrade="never", version = "0.3.1")' 
> RUN Rscript -e 'remotes::install_version("DT",upgrade="never", version = "0.13")' 
> RUN Rscript -e 'remotes::install_version("glue",upgrade="never", version = "1.4.1")' 
> RUN Rscript -e 'remotes::install_version("htmltools",upgrade="never", version = "0.4.0")' 
> RUN Rscript -e 'remotes::install_version("shinyjs",upgrade="never", version = "1.1")' 
> RUN Rscript -e 'remotes::install_version("dplyr",upgrade="never", version = "1.0.0")' 
> RUN Rscript -e 'remotes::install_version("stringr",upgrade="never", version = "1.4.0")' 
> RUN Rscript -e 'remotes::install_version("readr",upgrade="never", version = "1.3.1")' 
> RUN Rscript -e 'remotes::install_version("purrr",upgrade="never", version = "0.3.4")' 
> RUN Rscript -e 'remotes::install_version("magrittr",upgrade="never", version = "1.5")' 
> RUN Rscript -e 'remotes::install_version("knitr",upgrade="never", version = "1.28")' 
> RUN Rscript -e 'remotes::install_version("rmarkdown",upgrade="never", version = "2.2")' 
> RUN mkdir /build_zone ADD . /build_zone WORKDIR /build_zone 
> RUN R -e 'remotes::install_local(upgrade="never")' 
> EXPOSE 3838 CMD ["R", "-e", "options('shiny.port'=3838,shiny.host='0.0.0.0');myApp::run_app()"]
> ```
> 
> there is only 23 step, and i dont have any error during `docker build .`
> 
> can you check ?

**Comment by VincentGuyader** [comment]
can you post here the complete dockerfile you have ?

Regards

**Comment by AMillanFL** [comment]
Here my dockerfile
```
FROM rocker/r-ver:4.0.0
RUN apt-get update && apt-get install -y  git-core libcurl4-openssl-dev libgit2-dev libssh2-1-dev libssl-dev libxml2-dev make pandoc pandoc-citeproc zlib1g-dev && rm -rf /var/lib/apt/lists/*
RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site
RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_github("r-lib/remotes", ref = "97bbf81")'
RUN Rscript -e 'remotes::install_version("config",upgrade="never", version = "0.3")'
RUN Rscript -e 'remotes::install_version("golem",upgrade="never", version = "0.2.1")'
RUN Rscript -e 'remotes::install_version("shiny",upgrade="never", version = "1.4.0.2")'
RUN Rscript -e 'remotes::install_version("attempt",upgrade="never", version = "0.3.1")'
RUN Rscript -e 'remotes::install_version("DT",upgrade="never", version = "0.13")'
RUN Rscript -e 'remotes::install_version("glue",upgrade="never", version = "1.4.1")'
RUN Rscript -e 'remotes::install_version("htmltools",upgrade="never", version = "0.4.0")'
RUN Rscript -e 'remotes::install_version("shinyjs",upgrade="never", version = "1.1")'
RUN Rscript -e 'remotes::install_version("dplyr",upgrade="never", version = "1.0.0")'
RUN Rscript -e 'remotes::install_version("stringr",upgrade="never", version = "1.4.0")'
RUN Rscript -e 'remotes::install_version("readr",upgrade="never", version = "1.3.1")'
RUN Rscript -e 'remotes::install_version("purrr",upgrade="never", version = "0.3.4")'
RUN Rscript -e 'remotes::install_version("magrittr",upgrade="never", version = "1.5")'
RUN Rscript -e 'remotes::install_version("knitr",upgrade="never", version = "1.28")'
RUN Rscript -e 'remotes::install_version("rmarkdown",upgrade="never", version = "2.2")'
RUN mkdir /build_zone ADD . /build_zone WORKDIR /build_zone
RUN R -e 'remotes::install_local( upgrade="never")'
EXPOSE 3838 CMD  ["R", "-e", "options('shiny.port'=3838,shiny.host='0.0.0.0');myapp::run_app()"]
```
Thanks

**Comment by VincentGuyader** [comment]
yuo have to correct 
```

RUN mkdir /build_zone ADD . /build_zone WORKDIR /build_zone
RUN R -e 'remotes::install_local( upgrade="never")'
```

to
```

RUN mkdir /build_zone 
ADD . /build_zone WORKDIR /build_zone
RUN R -e 'remotes::install_local( upgrade="never")'
```

**Comment by AMillanFL** [comment]
With the correction the error message turns to :
Step 22/24 : ADD . /build_zone WORKDIR /build_zone
ADD failed: stat /var/lib/docker/tmp/docker-builder054865680/build_zone: no such file or directory

Looks like a docker problem ?

**Comment by VincentGuyader** [comment]
yes, maybe a space issue ?

Regards

**Comment by AMillanFL** [comment]
I find the problem.
I use to deploy my golem project from build source tar.gz file but with the golem::add_dockerfile_shinyproxy() function the dockerfile is made to work with direct source. I upload my whole project and it works without problem.
Sorry and thank you for the time spent.

**Comment by VincentGuyader** [comment]
ok, 

you may want to have a look to this parameters : 

`golem::add_dockerfile_shinyproxy(build_golem_from_source = FALSE,update_tar_gz = FALSE)`


you can choose if you want to deploy Dockerfile + tar.gz or source folde + Dockerfile.

you can play with `build_golem_from_source` `update_tar_gz` 

Regards
