### ISSUE TITLE
[Enhancement?] add_local_*() functions

### ISSUE THREAD

**Issue by KasperThystrup** [ThinkR-open/golem#465]
There doesn't seem to be an option for golem to physically copy a local file like an image to `www/`.

Keeping up with the philosophy to document most of the development process in the dev files, I suggest to implement golem::add_local_* functions. These functions could contain arguments for determining whether to hard copy or link target file. 

If this is integrated, you could likewise include a section in the 02_dev.R template which contains add_local_*() functions (e.g.golem::add_local_image()).

**Comment by ColinFay** [comment]
hey, 

That would make perfect sense to have that (I was under the impression that I had an issue for implementing that but apparently not :) )

The correct convention for naming would be `use_*`, following the pattern of `use_external_css`. 

Would you be willing to make a PR implementing that?

**Comment by ColinFay** [comment]
Thanks again for the idea! 

There is now a `use_external_file()` that will allow you to do the add from an online file. 
https://github.com/ThinkR-open/golem/blob/dev/R/use_files.R#L200

I suppose we could implement a `use_local_` version of these `use_external_` functions

**Comment by KasperThystrup** [comment]
Sorry that I didn't answer you back in July, my notifications settings were off...
 
I have just forked Golem, I will look into it now!

**Comment by KasperThystrup** [comment]
Functionality has been added, closing.
