### ISSUE TITLE
Specify extra system requirements for docker creation

### ISSUE THREAD

**Issue by jacobwindsor** [ThinkR-open/golem#474]
I have a situation where my shiny app needs extra system requirements. These are specified in `DESCRIPTION` under `SytemRequirements`. Running `golem::add_dockerfile()` doesn't pull in these system requirements to the docker file. It would be great if `get_sysreqs()` could read the requirements in DESCRIPTION or accept a character vector of system requirements.

**Comment by VincentGuyader** [comment]
hi, nice idea,

 can you please share with me the DESCRIPTION file you use ?

not usre if I can do something 100% automatic, but at least I can add a character vector of system requirements!

Regards

**Comment by jacobwindsor** [comment]
Thanks for the quick response!

Yeah I just looked into how `get_sysreqs()` works. It wouldn't be possible with the current https://sysreqs.r-hub.io/ lookup

Here you go:

```
Package: SQANTIExplorer
Title: SQANTI Explorer
Version: 0.0.0.9000
Authors@R: person('Jacob', 'Windsor', email = 'me@jcbwndsr.com', role = c('cre', 'aut'))
Description: Explore SQANTI classification files.
License: MIT + file LICENSE
Imports: 
    config,
    golem,
    shiny,
    processx,
    htmlwidgets,
    shinydashboard,
    plotly,
    igvShiny,
    shinycssloaders,
    readr,
    purrr,
    tibble,
    fs,
    stringr,
    magrittr,
    tidyr,
    ggplot2,
    dplyr,
    rtracklayer,
    ggthemr,
    attempt,
    DT,
    glue,
    htmltools,
    Rhtslib
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.1.1
Suggests: 
    knitr,
    rmarkdown,
    spelling
VignetteBuilder: knitr
Language: en-US
URL: https://github.com/jacobwindsor/SQANTIExplorer
BugReports: https://github.com/jacobwindsor/SQANTIExplorer/issues
bioCViews:
  Software,
  AnnotationData,
  ExperimentData,
  Workflow  
SystemRequirements:
  libbz2-dev,
  liblzma-dev
```

**Comment by VincentGuyader** [comment]
As I know, the `SystemRequirements` filed is not a really precise field. (we can write here what we want, without any precise formating) In your case you list debian package, but in some other DESCRPTION file we find many other spécification. (one of mine package on CRAN use this : `SystemRequirements: FFmpeg (http://ffmpeg.org)` )

On our case because we use debian based docker image, we need SystemRequirements for debian, 


I have to think more about it...

**Comment by jacobwindsor** [comment]
Okay, is it possible just to have a character vector then? I think it's a sensible quick fix. Just give it a list of debian packages that will be included in the install.

**Comment by VincentGuyader** [comment]
Hi, can you check wtih `remotes::install_github('thinkr-open/golem',ref='issue_474')`

if `add_dockerfile(extra_sysreqs = c("libbz2-dev","liblzma-dev")` do the job for you ?

Regards

**Comment by jacobwindsor** [comment]
Yep, perfect thanks so much

**Comment by ColinFay** [comment]
This seems to be solved, closing
