### ISSUE TITLE
run_dev.R works but installation errors with function not found.

### ISSUE THREAD

**Issue by quickbendelat** [ThinkR-open/golem#477]
I have written an app that uses RDCOMClient on R version 4.0.2, which required RDCOMClient to be installed from a Windows binary zip file from github as described [here](https://github.com/omegahat/RDCOMClient/issues/24).
Running the "run_dev.R" works; the app loads and displays as intended.

However, if I build my app as a package and then use "run_app()", it fails to load with an error relating to being unable to find a function from the RDCOMClient package.

I have imported RDCOMClient and it appears in the DESCRIPTION and NAMESAPCE files for my app.

When running `remotes::install_local()`, the first message is:

> "Skipping 1 packages not available: RDCOMClient"

I have also built my app using the "Build Binary Package" and then tried to install from that, but still the same problem when I try `run_app()`.

My app can be found here: https://github.com/quickbendelat/outlookcalendarR

Any assistance would be greatly appreciated.

**Comment by VincentGuyader** [comment]
I have : 

```
> library(outlookcalendarR)
> outlookcalendarR::run_app()
Le chargement a nécessité le package : shiny

Listening on http://127.0.0.1:5648
Warning: Error in createCOMReference: impossible de trouver la fonction "createCOMReference"
  59: COMCreate
  58: getCOMInstance
  57: COMCreate
  56: module [C:/sur_git/outlookcalendarR/R/mod_outlookcalendar.R#55]
  51: callModule
  50: server [C:/sur_git/outlookcalendarR/R/app_server.R#10]
Error in createCOMReference(<pointer: 0x000001d8b1e399f8>, "COMIDispatch") : 
  impossible de trouver la fonction "createCOMReference"
```


can you try by putting RDCOMClient in `Depends` and not in `Import` field in your DESCRIPTION file ?

**Comment by quickbendelat** [comment]
@VincentGuyader Thanks!
I manually edited the DESCRIPTION file to move RDCOMClient to the `Depends` field.
> library(outlookcalendarR)
Loading required package: RDCOMClient
> outlookcalendarR::run_app()
Loading required package: shiny
Listening on http://127.0.0.1:5759

**Comment by VincentGuyader** [comment]
\o/
