### ISSUE TITLE
Where to initialize ggthemr?

### ISSUE THREAD

**Issue by jacobwindsor** [ThinkR-open/golem#480]
I am using ggthemr to change the styles of ggplot2 but cannot get it working with golem. It worked previously without golem and just a basic shiny app.

The most sensible place I would think is at the top of app_server.R:

```
app_server <- function( input, output, session ) {
  ...
  
  # ggplot
  ggthemr(
    define_palette(
      swatch = structure(
        c(
          
          color_primary_light, color_secondary, 
          color_primary, color_primary_dark,
          color_secondary_light, color_secondary_dark
        )
      ),
      gradient = c(lower=color_primary_light, upper=color_primary_dark),
      background = '#ecf0f1'
    )
  )
...
}
```

However, that fails to theme ggplot2. I am not sure but I guess this might be something to do with scoping.

Any advice much appreciated.

**Comment by ColinFay** [comment]
Hey, 

I do not reproduce your issue, if I use `ggthemr::ggthemr("dust")` inside app_server, the theme is correctly set in the modules. 

- server

```
app_server <- function( input, output, session ) {
  # List the first level callModules here
  ggthemr::ggthemr("dust")
  mod_name_of_module1_server("name_of_module1_ui_1")
}
```

- ui

```
app_ui <- function(request) {
  tagList(
    # Leave this function for adding external resources
    golem_add_external_resources(),
    # List the first level UI elements here
    fluidPage(
      h1("giligligligii"),
      mod_name_of_module1_ui("name_of_module1_ui_1")
    )
  )
}
```

- module

```
mod_name_of_module1_ui <- function(id){
  ns <- NS(id)
  tagList(
    plotOutput(ns("plop"))
  )
}

mod_name_of_module1_server_core <- function(input, output, session){
  ns <- session$ns

  output$plop <- renderPlot({
    ggplot(iris, aes(Sepal.Length, Sepal.Width)) +
      geom_point()
  })

}

mod_name_of_module1_server <- function(id){
  moduleServer(
    id,
    mod_name_of_module1_server_core
  )
}
```


Are you getting any message in the console? 

Any change you could share a link to a repo with an example of that behavior ? 

Thanks

**Comment by ColinFay** [comment]
@jacobwindsor are you still struggling with this?

**Comment by jacobwindsor** [comment]
Hi, thanks for looking into it. Yes, I am still struggling with it. I've
been busy with other things these past weeks but I will take a look soon.
The app I am having this issue on is in the repo linked above (I referenced
this issue in an issue there)

**Comment by ColinFay** [comment]
Hey @jacobwindsor, 

Let me know if you still have issues with this one :) 

Cheers, 
Colin

**Comment by ColinFay** [comment]
Closing this one, feel free to reopen if you still have the issue :) 

Cheers, 
Colin
