### ISSUE TITLE
Non-standard file/directory found at top level:  ‘manifest.json’

### ISSUE THREAD

**Issue by MayaGans** [ThinkR-open/golem#482]
I was running my package check and got this note:

```
Non-standard file/directory found at top level:  ‘manifest.json’
```

 I was wondering, if I do eventually want to try to submit my package to CRAN where should this file should go if not in the root directory? [Maybe worth documenting this in https://engineering-shiny.org/? ]

**Comment by ColinFay** [comment]
Hey, 

If you want to submit to CRAN/pass the check, you can do `usethis::use_build_ignore("manifest.json")`, that should do the trick.

You're definitely right that this should be documented, thanks!

**Comment by MayaGans** [comment]
Ah duh, perfect, thanks!!
