### ISSUE TITLE
add_resource_path does not work in Docker image

### ISSUE THREAD

**Issue by jacobwindsor** [ThinkR-open/golem#488]
I have used `golem::add_resource_path` to point `inst/app/www/tmp` to `tmp` with `golem::add_resource_path("tmp", "inst/app/www/tmp")`. This works fine when running with run_dev but when I spin up the Docker image created with deploy using `sudo docker run -it -p 3838:80 jcbwndsr/sqantiexplorer` I get 404s when attempting to hit the files in "inst/app/www/tmp". 

I have checked that there are files in the folder by logging into the running Docker container.

**Comment by ColinFay** [comment]
Shooting in the dark here, but could you try with another folder name? Maybe /tmp is not allowed there. 

If you try to do `docker run -p 2811:80 colinfay/hexmake:latest` and go to localhost:2811, you'll see that the resource path is correctly found/handled. 

Do you have anything that might differ from the way https://github.com/ColinFay/hexmake is built in your folders?

**Comment by ColinFay** [comment]
Closing for lack of further information :) 

Feel free to comment if you need more help and I'll reopen this issue.

**Comment by ShinyFabio** [comment]
Hello I have the same problem. After run the container, i get an error. It says:

_An error has occurred!
Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'www'; `directoryPath` = ''_

What's wrong? I have a lot of pictures in the www folder (inst\app\www). I have also a folder inside www (with some sub-folders) to better arrange the big amount of images. Maybe this is a problem? Without docker the app runs correctly.

**Comment by ColinFay** [comment]
@ShinyFabio could you by any chance share a repo with me so I can have a look? (Even privately)

**Comment by ShinyFabio** [comment]
Sure i'll send you an email

**Comment by ShinyFabio** [comment]
Hi Colin, did you received my email? I sent to contact@colinfay.me. Maybe is it wrong?

**Comment by ColinFay** [comment]
Hey, 

yeah it's the correct mail, sorry I didn't have time to look at it in details yet :)

Do you happen to have a link to the source code so I can have more information ?

**Comment by ShinyFabio** [comment]
sure, what do you need? ui and server? something else?


________________________________
Da: Colin Fay <notifications@github.com>
Inviato: lunedì 8 marzo 2021 20:10
A: ThinkR-open/golem <golem@noreply.github.com>
Cc: ShinyFabio <fabiodellarocca94@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [ThinkR-open/golem] add_resource_path does not work in Docker image (#488)


Hey,

yeah it's the correct mail, sorry I didn't have time to look at it in details yet :)

Do you happen to have a link to the source code so I can have more information ?

**Comment by ColinFay** [comment]
The full project would be perfect, so I can reproduce the issue and debug it :)

**Comment by ColinFay** [comment]
@ShinyFabio the issue is that you changed the name of the app in the DESCRIPTION but not in `app_config.R`, function `app_sys()`.

If you do 

```
app_sys <- function(...){
  system.file(..., package = "olivehealthrdockerize")
}
```

and rebuild, it works (well, you have another function import error but the addResourcePath one is solved) :) 

@jacobwindsor, does it solves your issue too?

**Comment by ColinFay** [comment]
Seems solved, closing now. 

Feel free to comment if you need me to reopen :) 

Cheers, 
Colin
