### ISSUE TITLE
Feature request: golem::add_module

### ISSUE THREAD

**Issue by KasperThystrup** [ThinkR-open/golem#489]
The 02_dev file is really helpful for maintaining an overview of the existing module.

While the golem::add_module() is a smart and swift way of generating new modules, it would be neat if the function could be used as a shortcut as well.

Currently, using the add_module function on an existing file will result in a module skeleton being appended to the end of the module file.

I suggest that you add a prior step in the add_module (and other add_*) functions that determines whether a module file already exist, and which foregoes appending the module skeleton for TRUE cases.

**Comment by ColinFay** [comment]
Hey, 

Thanks for the feedback! 👍

This is a known bug that has been solved (and shouldn't happen if you are using the dev version of golem ) => Note the "✔ File already exists." when recreating the same module :)

```bash
colin:~ colin$ cd /tmp

colin:tmp colin$ Rscript -e "golem::create_golem('plop')"
── Checking package name ───────────────────────────────────────────────────────
✔ Valid package name
── Creating dir ────────────────────────────────────────────────────────────────
✔ Created package directory
── Copying package skeleton ────────────────────────────────────────────────────
✔ Copied app skeleton
── Setting the default config ──────────────────────────────────────────────────
✔ Configured app
✔ Setting active project to '/private/tmp/plop'
── Done ────────────────────────────────────────────────────────────────────────
A new golem named plop was created at /private/tmp/plop .
To continue working on your app, start editing the 01_start.R file.

colin:tmp colin$ cd plop/

colin:plop colin$ Rscript -e "golem::add_module('yes')"
✔ File created at R/mod_yes.R
● Go to R/mod_yes.R

colin:plop colin$ wc R/mod_yes.R 
      30      71     485 R/mod_yes.R

colin:plop colin$ Rscript -e "golem::add_module('yes')"
✔ File already exists.
● Go to R/mod_yes.R

colin:plop colin$ wc R/mod_yes.R 
      30      71     485 R/mod_yes.R
```

I plan on releasing a new version of `{golem}` this month, so it should be on CRAN soon.
