### ISSUE TITLE
Start a wiki with resources

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#51]
à la [data.table](https://github.com/Rdatatable/data.table/wiki/Presentations)

The idea would be to gather inside a wiki page on the repo with 

resources : (talk, blog post,...)
- get started with golem
- golem in the real world 
- Advanced golem (not sure if there are any?)

Links to applications (publicly available) built with golem:
- links to deploy apps
- Links to repositories 
Potentially these apps might examplify specific golem features ? 

Note : there are some informations already listed on the README, if you find some interesting link, that would be awesome to also update this README with new content.

**Comment by KittJonathan** [comment]
Maybe I can try this one :-)

**Comment by KittJonathan** [comment]
I'll take this one !

**Comment by ColinFay** [comment]
Super @KittJonathan 🤩 

I've update my original post. Does that sound clear enough to you? Please let me know.

**Comment by KittJonathan** [comment]
> Super @KittJonathan 🤩 
> 
> I've update my original post. Does that sound clear enough to you? Please let me know. 

Thanks Colin, sounds clear to me !

**Comment by ColinFay** [comment]
That's great, thanks!

**Comment by KittJonathan** [comment]
Hi Colin, is it possible to do a PR for the wiki ?

**Comment by ColinFay** [comment]
Hey @KittJonathan

Finally took the time to gather all the content you curated + some I've found on the web. 

https://github.com/ThinkR-open/golem/wiki

Thanks again for your help :)

**Comment by KittJonathan** [comment]
@ColinFay great, thanks for letting me know !
