### ISSUE TITLE
[Feature request] run_dev.R as a single function

### ISSUE THREAD

**Issue by KasperThystrup** [ThinkR-open/golem#517]
Hi
I really think the run-dev script is awesome, as it minimizes human errors.
Would it be possible to implement a function that runs the script, so that we during developmnet could execute a run_dev() command, instead of selecting and executing the entire script? (e.g. like running source("dev/run_dev.R"))

**Comment by ColinFay** [comment]
thanks for the idea @KasperThystrup :) 

It's already implemented in the latest (GitHub) version, through https://github.com/ThinkR-open/golem/pull/478 & https://github.com/ThinkR-open/golem/blob/dev/R/run_dev.R

Does it match what you're looking for?

**Comment by KasperThystrup** [comment]
Yes!
I'm sorry for the excess post, I only recently installed the Github version, so didn't realize it was already here.. Neat!

Closing

**Comment by ColinFay** [comment]
No problem, thanks anyway :)
