### ISSUE TITLE
`add_dockerfile()` should use GITHUB_PAT when calling `remotes::install_github`

### ISSUE THREAD

**Issue by antoine-sachet** [ThinkR-open/golem#531]
Context: I manage a shinyproxy server and we use golem for most of our apps. They deploy via an AWS CD pipeline powered by a Dockerfile created with `golem::add_dockerfile()`

Problem: docker build can fail when installing packages from github because the rate limit of the GitHub API is exceeded.

For example, this is from my AWS build log:

```
1090 | Error: Failed to install 'unknown package' from GitHub:
1091 | Failed to install 'gargle' from GitHub:
1092 | HTTP error 403.
1093 | API rate limit exceeded for 35.176.92.34. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
1094 |  
1095 | Rate limit remaining: 0/60
1096 | Rate limit reset at: 2020-10-12 16:31:43 UTC
1097 |  
1098 | To increase your GitHub API rate limit
1099 | - Use `usethis::browse_github_pat()` to create a Personal Access Token.
1100 | - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.
1101 | Execution halted
1102 | The command '/bin/sh -c Rscript -e 'remotes::install_github("tidyverse/googlesheets4@b86b6f76ee857493dd58135169272c66cb5493f2")'' returned a non-zero code: 1
1103
```

Solution:  Change the command used to install packages from github in the Dockerfile:

```
RUN Rscript -e 'remotes::install_github("r-lib/rlang@v0.4.7")'
```

should become

```
ARG GITHUB_PAT  # Only once before non CRAN remotes
RUN GITHUB_PAT=$GITHUB_PAT Rscript -e 'remotes::install_github("r-lib/rlang@v0.4.7")'
```

This would allow the user to pass a `GITHUB_PAT` when building the docker image and avoid the rate limit. Another HUGE advantage is that it would allow access to private repository!

I would suggest adding a logical argument `use_github_pat = FALSE` to the various `add_dockerfile_XXX()` functions. The default value (`FALSE`) would preserve the existing behaviour but `use_github_pat = TRUE` would add the necessary code in the Dockerfile.

Note that the user does not need to pass the value of their GITHUB_PAT to add_dockerfile. Instead it must be passed as a  build argument when calling `docker build`.

**Comment by VincentGuyader** [comment]
hi, 
thanks a lot for this idea !

can you please consider doing a PR ?

Regards

**Comment by antoine-sachet** [comment]
Thinking about the UI a bit deeper. Maybe this should not be so github-centric. After all, gitlab requires GITLAB_PAT and bitbucket (which my team uses) requires both `BITBUCKET_USER` and `BITBUCKET_PASSWORD`.

A more generic way to handle this would be to have an argument `build_args` listing the build args needed.

`add_dockerfile_shinyproxy(build_args = c("GITHUB_PAT", "BITBUCKET_USER", "BITBUCKET_PASSWORD"))`

The Dockerfile would contain:

```
ARG GITHUB_PAT
ARG BITBUCKET_USER
ARG BITBUCKET_PASSWORD

RUN GITHUB_PAT=$GITHUB_PAT \
         BITBUCKET_USER = $BITBUCKET_USER \
         BITBUCKET_PASSWORD = $BITBUCKET_PASSWORD \
         Rscript -e 'remotes::install_github("r-lib/rlang@v0.4.7")'
```

We'd have to list all the args before every install or we could match known values to the relevant services. I am sure there is a more elegant way to do it though.

**Comment by antoine-sachet** [comment]
I've had a much better idea. We don't need to add any argument to `add_dockerfile_XXX()`. Instead we _always_ add `GITHUB_PAT` and other credentials to the Dockerfile, but with an empty default value.

```
ARG GITHUB_PAT=""
RUN GITHUB_PAT=$GITHUB_PAT Rscript -e 'remotes::install_github("r-lib/rlang@v0.4.7")'
```

This means you can build the docker image without any build arguments (just like before) but you can pass them if you need to.
This change is completely transparent for the users not using a PAT but enables authenticating with a simple `docker build --build-arg GITHUB_PAT=XXX`. 

This is also a great occasion to fix #425 at the same time and start using the right remote when it is not github.

If you install stuff from several remote types, the resulting dockerfile would look like:

```
ARG GITHUB_PAT=""
RUN GITHUB_PAT=$GITHUB_PAT Rscript -e 'remotes::install_github("r-lib/rlang@v0.4.7")'

ARG BITBUCKET_USER=""
ARG BITBUCKET_PASSWORD=""
RUN BITBUCKET_USER=$BITBUCKET_USER BITBUCKET_PASSWORD=$BITBUCKET_PASSWORD \
    Rscript -e 'remotes::install_bitbucket("soundout/echartR@ba7b6e52
```

Aaaah, my dreams coming true :p We just have to maintain an internal mapping between remotes and build args which is pretty straightforward.

@VincentGuyader Let me know if you agree with this approach and I'll prep a PR taking care of both issues (when I have some free time).

**Comment by VincentGuyader** [comment]
HI, 

for the next {golem} lrelease, we plan to move all function about docker in https://github.com/ColinFay/dockerfiler. we will include your idea in dockerfiler

thanks

**Comment by ColinFay** [comment]
Note : my issue right now is that env var are contained inside the built container, hence if you pass your GitHub PAT there are some security issues.

**Comment by ColinFay** [comment]
Hey,
All docker-related functions have moved to [{dockerfiler}](https://github.com/ColinFay/dockerfiler).
We'll keep track of the issues here.
