### ISSUE TITLE
dockerignore file keeps growing

### ISSUE THREAD

**Issue by antoine-sachet** [ThinkR-open/golem#532]
Creating a dockerfile with one of the `add_dockerfile_XXX` creates and appends to a `.dockerignore` file as a side effect.

If you re-generate the dockerfile, the dockerignore keeps growing. For example, after calling `add_dockerfile_shinyproxy` 3 times, the `.dockerignore` contains:

```
.RData
.Rhistory
.git
.gitignore
manifest.json
rsconnect/
Rproj.user
.RData
.Rhistory
.git
.gitignore
manifest.json
rsconnect/
Rproj.user
.RData
.Rhistory
.git
.gitignore
manifest.json
rsconnect/
Rproj.user
```

I also think we ought to mention a .dockerignore file is created so we should add a green tick.

Note: this is a reference issue for a PR I am working on.

**Comment by ColinFay** [comment]
Hey, 

You're indeed right, I didn't see that upfront 🤦‍♀️

Thank you for your help on this 🤘

**Comment by ColinFay** [comment]
Should be good by now, 

Feel free to reopen if ever there is another issue on that. 

Cheers,
 
Colin
