### ISSUE TITLE
Nicer error about package name restriction

### ISSUE THREAD

**Issue by cderv** [ThinkR-open/golem#54]
When using creation of the project in the IDE, with an invalid package name, I got this nice error 
```r
Error: 'test-with-dash' is not a valid package name. It should:
* Contain only ASCII letters, numbers, and '.'
* Have at least two characters
* Start with a letter
* Not end with '.'
```
This is related to #18 as it can be created from commandline and this is not really an issue if you are well aware that a Golem Project is in fact a package Project.

However, I think that most users won't be aware of that directly. Me the first as I stumble upon during the workshop. 

Should the error message be golem specific with 
* Reminder that user is creating a 📦 
* Point to some doc explaining the restriction 
* POint to some doc explaining the workflow for advaced user to create a RStudio Project then transform in a golem template with `check_name = FALSE` 
? 

Just an idea for user friendly experience 😄

**Comment by cderv** [comment]
And no @DianeBeldame I did not put dash (`-`) on purpose 😉  I just don't name project without them usually.  😀

**Comment by DianeBeldame** [comment]
Ok. I believe you @cderv....this time

**Comment by ColinFay** [comment]
Hey, 

So after more than two years of this issue open, I don't think we have had anyone else complaining about this :D 

Joking aside, my thought so far is that we shouldn't try and reinvent the wheel here. 
We're using an internal `{usethis}` function that does a great job at detecting this pattern, so I feel like we should rely on this one, even if there is the small downside of the message :) 

Cheers, 
Colin

**Comment by cderv** [comment]
OK, as you wish. I see my feedback are of high value ! 🙄 

😜
