### ISSUE TITLE
No need to depend on htmltools

### ISSUE THREAD

**Issue by antoine-sachet** [ThinkR-open/golem#540]
When using the UI utils, the `htmltools` package is added to dependencies because the ui utils need `tags`, `tagAppend`, etc. But all those are re-exported by shiny so we could just import them from shiny instead and remove the extra dependency.

I just realised that when signing off on an app before deployment and wondering why `htmltools` was in the `Imports`.

**Comment by ColinFay** [comment]
Closed via #617 , thanks a lot @antoine-sachet !
