### ISSUE TITLE
custom.css file - style by module

### ISSUE THREAD

**Issue by mraess** [ThinkR-open/golem#547]
Hi @VincentGuyader & @ColinFay! 

First time `golem` user and I have to say I love it. It's fairly intuitive. I hadn't worked with modules before but the concept is super accessible as long as you know `shiny`. 

I have one problem though. I'm in the process of getting an app ready for deployment but the `custom.css` file is not working, i.e. the css code won't apply to specific module elements.

For example:

Module - `mod_sidebar`
`actionButton(inputId = ns("generate"), label = "Generate", icon = icon("play", lib = "glyphicon"))`

CALL

`r <- callModule(mod_sidebar_server, "sidebar_ui_1")`

CSS
```
#mod_sidebar-generate {
  background-color: #FC4559;
  font-weight: bold;
  color: #2C3039;
  border-color: #2C3039;
  border-width: 0;
}
```

I also tried

```
#sidebar_ui_1-generate {
  background-color: #FC4559;
  font-weight: bold;
  color: #2C3039;
  border-color: #2C3039;
  border-width: 0;
}
```
which also doesn't work.

But for whatever reason, this does not work and the css is not applied to the `actionButton`. Am I missing anything here? I checked http://connect.thinkr.fr/engineering-shiny/css.html#integrate-css-files-to-your-shiny-app but saw that the CSS section is still empty.

I hope this is enough context.

**Comment by ColinFay** [comment]
Hey @mraess, 

Thanks for your feedback. 

Just a sidenote, the book is now at https://engineering-shiny.org/ and is finished ;)

I've tried to reproduce and was able to implement the CSS with:

```
#sidebar_ui_1-generate {
  background-color: #FC4559;
  font-weight: bold;
  color: #2C3039;
  border-color: #2C3039;
  border-width: 0;
}
```

See https://github.com/ColinFay/golem-552/blob/main/R/mod_sidebar.R#L13 and https://github.com/ColinFay/golem-552/blob/main/inst/app/www/custom.css#L1

![Screenshot 2020-11-06 at 17 14 58](https://user-images.githubusercontent.com/17936236/98388908-a35baa00-2053-11eb-84c3-8493ad9630b6.png)

Any chance you're doing something differently? 

Is your CSS in inst/app/www ? 

What is the version of golem you're using?

Is it linked to your application inside `golem_add_external_resources`? If you're using golem < 0.2.0, you have to manually link the CSS. If not, it should be caught by `bundle_resources`. 
Can you go to your browser, developper console, Source, and check that you have the css here in www? 

![Screenshot 2020-11-06 at 17 17 02](https://user-images.githubusercontent.com/17936236/98389132-f2a1da80-2053-11eb-952b-2ff575112db2.png)

Cheers, 
Colin

**Comment by mraess** [comment]
@ColinFay thanks so much for getting back to me on this! I'll check out these suggestions and will follow up with what I can find.

**Comment by mraess** [comment]
@ColinFay so the weirdest thing is happening. The `custom.css` seems to work and produce the desired output but only when I save changes, then close the RStudio Project, and then reopen the project. Then, when I run `run_dev.R` it works. Any idea what might be going on there?

**Comment by ColinFay** [comment]
I've noticed that some times (depending on your browser config), your web browser caches your css file, so when you reload your application, as it's on the same port, your browser uses the cached version instead of using the modified one. When you notice that the css is not taken into account, it might be worth checking the state of the css file using your browser developer console to verify that it has changed :)

**Comment by mraess** [comment]
@ColinFay ah I see. Thank you! That makes sense. I'll check that out.

**Comment by ColinFay** [comment]
Have you correctly defined the env var in Connect ? 

For example : https://github.com/ColinFay/hexmake is on Connect and uses env var https://github.com/ColinFay/hexmake/blob/master/R/app_server.R#L6

Indeed not in the YAML here, but yeah `!expr Sys.getenv('xxx')` should work 🤔
What error do you get?

**Comment by mraess** [comment]
When I tried to run `run_app.R` it would simply not load. I've moved the database connection into the `mod_mainpanel.R` file and now it works and it calls the envars correctly from RSC. Thanks!

**Comment by ColinFay** [comment]
Solved, closing now :)
