### ISSUE TITLE
Golem with {tidyquant} or {lubridate}: tq_get: error in evaluating the argument 'x' in selecting a method for function 'as_date'

### ISSUE THREAD

**Issue by kprimice** [ThinkR-open/golem#548]
When I try to use `tq_get` from `{tidyquant}` in `{golem}` I get the Warning:

> Warning: x = 'SPY', get = 'stock.prices': Error in h(simpleError(msg, call)): error in evaluating the argument 'x' in selecting a method for function 'as_date': object '_lubridate_C_valid_tz' not found

Same if I try to use `lubridate:today()`:

> Warning: Error in h: error in evaluating the argument 'x' in selecting a method for function 'as_date': object '_lubridate_C_valid_tz' not found

**Comment by ColinFay** [comment]
Hey, 

This is usually an issue due to restarting a package too often (I've seen. this issue before while developing using `{lubridate}`).

Do you see at the very start of your R session or is it after some dev iterations?

**Comment by ColinFay** [comment]
Closing for lack of further information :) 

If ever you encounter this issue again, please comment below so that I can reopen it! 

Cheers, 
Colin
