### ISSUE TITLE
Idea : use expect_known_output

### ISSUE THREAD

**Issue by cderv** [ThinkR-open/golem#55]
Related to feature added in #32 

Currently I see one drawback to the current function to test html: it will not handle encoding correctly because of readLines. Should not be a wide issue but could happen in some edge cases. 

It made me think about `testthat::expect_known_output`. I think it could be useful : it writes result to file and compare then compare following test with this file. It seems like what you want to do. 
I find it useful that the file is written at first test is not existing yet. You could update easily and I think it handles encoding by ensuring UTF8 for the written file. No need to write manually the comparison file. 

Just an idea for improvement.

**Comment by ColinFay** [comment]
Long overdue... but https://github.com/ThinkR-open/golem/pull/743 🎉
