### ISSUE TITLE
Cannot create {golem} from the RStudio interface

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/golem#550]
With the last version available on GitHub (sha1: 06707a8), I used the graphical interface to create a {golem} but it stopped with this message.  
Creation using command line still work properly though : `golem::create_golem("~/shinyapps")`.  

![image](https://user-images.githubusercontent.com/21193866/97480038-2f364d80-1953-11eb-9704-7dd8579197ba.png)

**Comment by ColinFay** [comment]
Can you share your sessionInfo() ? And RStudio version ? Thanks :)

**Comment by statnmap** [comment]
Ok now with _master_ : aaae5c8788802a7b4aef4df23691902a286dd964
Ok now with _dev_ : 728c2f5965f7ef2bff68fcb0c373eae27983a5c9
