### ISSUE TITLE
how to include built vignette in shiny app

### ISSUE THREAD

**Issue by gacolitti** [ThinkR-open/golem#553]
What is the recommended way to include built vignettes inside a golem shiny app while keeping standard vignette style and without opening new browser tab? The use case is when a golem app is developed for end users that won't be able to use `browseVignettes()` to see the documentation.

Section 10.4.1 of the book mentions using vignettes to document how the golem app works, but does not mention how to actually include the vignette content inside the app. 

See:
[https://engineering-shiny.org/stepbuild.html#documentation-and-code-coverage](https://engineering-shiny.org/stepbuild.html#documentation-and-code-coverage)

**Comment by VincentGuyader** [comment]
Please have a look to this module.

```
# Module UI

#' @title   mod_vignettes_ui and mod_vignettes_server
#' @description  A shiny Module.
#'
#' @param id shiny id
#' @param input internal
#' @param output internal
#' @param session internal
#'
#' @rdname mod_vignettes
#'
#' @keywords internal
#' @export
#' @importFrom shiny NS tagList
mod_vignettes_ui <- function(id){
  ns <- NS(id)
  tagList(
    htmltools::includeHTML(
      system.file("doc/my_vignette.html", package = "demogolem")
    ) %>% gsub(".*<body>(.*)</body>.*","\\1", .)
  )
}


# Module Server

#' @rdname mod_vignettes
#' @export
#' @keywords internal

mod_vignettes_server <- function(input, output, session){
  ns <- session$ns
}

## To be copied in the UI
# mod_vignettes_ui("vignettes_ui_1")

## To be copied in the server
# callModule(mod_vignettes_server, "vignettes_ui_1")


```

Regards

**Comment by gacolitti** [comment]
Hi Vincent, thanks for your response. I am new to shiny modules. Can you comment on the need/usefulness of using `NS()` in the UI function? It seems to me this is not actually serving any purpose because there are no inputs being created. Also, I'm not sure why there needs to be a server function at all.

**Comment by ColinFay** [comment]
Hey @gacolitti 

If you're including the HTML only and there is no server, you can definitely go your way (no module). 

Also, `getPackageName()` will only work if you're in development (once the app is installed, `{pkgload}` will not find it). So I'd suggest using the `app_sys()` shortcut from `R/config.R`. 

In other words

```
        includeHTML(app_sys(
          paste0("doc/", vignette, ".html")
        )) %>%
          gsub(".*<body>(.*)</body>.*", "\\1", .)
```

For your other question, here are two resources that go over modules:

- https://mastering-shiny.org/scaling-modules.html

- https://engineering-shiny.org/structure.html#using-shiny-modules

Let me know if that helps!

Colin

**Comment by gacolitti** [comment]
Hi Colin, this does help! Thank you!
