### ISSUE TITLE
Remove `{usethis}` from hard dep

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#559]
As of today, if we use `{usethis}` (dev version), we can't deploy to shinyapps.io: usethis depends on gert that has a C lib that is not available on shiny apps io.

**Comment by diwashrestha** [comment]
How to sort out this problem?

**Comment by ColinFay** [comment]
@diwashrestha what version of usethis do you have ?

**Comment by diwashrestha** [comment]
I reinstalled the old version of the usethis which solved the problem. Thank You @ColinFay

**Comment by ColinFay** [comment]
Let's close this for now : using a dev version for a prod app is not recommended. 

And usethis won't be needed when deployed when we have `{prague}` set up
