### ISSUE TITLE
Use a GOLEM_CONFIG_ACTIVE 

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#563]
Current implementation relies on R_CONFIG_ACTIVE, but that might conflict with server configuration. 

We should add a `GOLEM_CONFIG_ACTIVE` to prevent from that

**Comment by gtm19** [comment]
Are you me? 😂 I literally just had this problem on RStudio Connect:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/9137502/101152897-982c7780-361b-11eb-8acf-dc6a376580fe.png">

**Comment by ColinFay** [comment]
Yeah I was chatting with @andrie about that and there is no support for R_CONFIG_ACTIVE at the application level on Connect. 

@gtm19 my current workaround is the following: 

+ modify get_golem_config with

```
get_golem_config <- function(
  value, 
  config = Sys.getenv("GOLEM_CONFIG_ACTIVE", "default"), 
  use_parent = TRUE
){
  config::get(
    value = value, 
    config = config, 
    # Modify this if your config file is somewhere else:
    file = app_sys("golem-config.yml"), 
    use_parent = use_parent
  )
}
```

+ Use `GOLEM_CONFIG_ACTIVE ` inside Connect instead of `R_CONFIG_ACTIVE `

**Comment by antoine-sachet** [comment]
Hi Colin,

1. There's a typo in the code:

`Sys.getenv("GOLEM_CONFIG_ACTIVE", "R_CONFIG_ACTIVE", "default")`

should be 

`Sys.getenv("GOLEM_CONFIG_ACTIVE", "default")`

2. That's a breaking change - please document it. All our devops (shinyproxy on AWS) rely on R_CONFIG_ACTIVE, so it is not a trivial change at all.

3. Please bump the dev version (e.g. to 0.3.0.9000) so we can guard against it. Right now, master and dev have the same version but the code is different.

4. How about checking for `R_CONFIG_ACTIVE` if `GOLEM_CONFIG_ACTIVE` is not set? I am happy to do a PR for it.

Thanks :)

**Comment by ColinFay** [comment]
Argh, my original idea was to do : 

`Sys.getenv("GOLEM_CONFIG_ACTIVE", Sys.getenv("R_CONFIG_ACTIVE", "default"))` (which should probably be a `golem::get_active_config()` function to be clearer: what do you think ?)

I don't know what happened with my code 🤦‍♀️

I'm currently working on `{golem}` so I'll correct that today. 

As this is what I'm aiming for, that shouldn't be a breaking change (but a change indeed) — This will be added to the NEWS file when merged to master. 

For the package version, `master` is right now a Release Candidate (hence the `0.3.0`), but there has been a bunch of changes / bug I needed to fix before submitting to CRAN... and this have been delayed for a long time now unfortunately. 

I suggest always using the `master` branch unless trying `{golem}` new features :)
