### ISSUE TITLE
Development Data Location?

### ISSUE THREAD

**Issue by James-G-Hill** [ThinkR-open/golem#565]
Hello, this is more a query rather than bug or request.  Many applications depend upon data that's downloaded from an external source such as an SQL database or AirTable.  During development of such applications the download time for the dataset can be long enough to feel like an interruption in the workflow.  It therefore sometimes seems best to include a simple dataset for development purposes that can be loaded quickly in from disk.  In this case, where is the best place to store such data; would you recommend to put it in a sub-directory of the /dev directory & then load in within the 'run_dev.R' file?

**Comment by ColinFay** [comment]
(Moving this to the Discussion board :) )
