### ISSUE TITLE
Do we need importFrom(config,get) ?

### ISSUE THREAD

**Issue by moodymudskipper** [ThinkR-open/golem#591]
I noticed that in the golem package and in a package created with it, we find `importFrom(config,get)` in the NAMESPACE file.
`get` is quite a common function, and I was very surprised to to see it work as `base::get`. Maybe it'd be safer to use `config::get` ?

**Comment by ColinFay** [comment]
Hey, 

I think this has been solved in the github version of golem: 

+ https://github.com/ThinkR-open/golem/blob/master/inst/shinyexample/NAMESPACE
+ https://github.com/ThinkR-open/golem/blob/master/inst/shinyexample/R/app_config.R#L28

Is this what you're looking for? 

Cheers, 
Colin

**Comment by ColinFay** [comment]
Seems to be solved :) 

@moodymudskipper feel free to comment if you have any other question :) 

Cheers,

Colin
