### ISSUE TITLE
clarify docs for using invoke_js

### ISSUE THREAD

**Issue by yonicd** [ThinkR-open/golem#593]
The current help docs for `invoke_js` are a bit opaque on how the user is intended to use the this function.

eg if i want to click on an id i would use `clickon`, where the docs say "Click on an element. The full jQuery selector has to be used."

is the intention then: 

`golem::invoke_js('clickon',"#el")`

or

`golem::invoke_js('clickon',"$('#el')")`

or 

`golem::invoke_js('clickon',"$('#el').click()")`

or can it be just a raw js call?

`golem::invoke_js("$('#el').click()")`

**Comment by ColinFay** [comment]
Thanks Yoni 🎉

This was closed via #618. 

Cheers, 

Colin
