### ISSUE TITLE
Argument "name" should be renamed "copyright_holder" for usethis::use_mit_license

### ISSUE THREAD

**Issue by fBedecarrats** [ThinkR-open/golem#594]
The latest version of usethis (2.0), the "name" argument for use_mit_license was replaced by "copyright_holder". 
The def/01_start.R that currently reads:
```
usethis::use_mit_license( name = "Golem user" ) 
```
Which returns an error with the latest version of usethis.
It should read:
```
usethis::use_mit_license( copyright_holder = "Golem user" ) 
```
Another option would be not to mention any element name to ensure backward compatibility:
```
usethis::use_mit_license( "Golem user" ) 
```
Many thanks!

**Comment by ColinFay** [comment]
Thanks for this! 

I've removed the arg so this doesn't bug anymore. 

cheers, 
colin
