### ISSUE TITLE
How to include global.R in run_app?

### ISSUE THREAD

**Issue by happyshows** [ThinkR-open/golem#6]
Hi,

The [tutorial](https://rtask.thinkr.fr/blog/our-shiny-template-to-design-a-prod-ready-app/#disqus_thread) is not very clear.

Could you share how to include a global.R file in the template approach?

**Comment by VincentGuyader** [comment]
hi, you dont need to use a global.R file.
put your function inside the R folder, 
(if you realy want I suppose you can source your global.R from the server part)

**Comment by jerome-laurent-pro** [comment]
Hi,

I'm having trouble conceptualizing something and this seemed the most related issue, albeit closed.

I already have a simple 3 files shiny application (`ui.R`, `server.R` and `global.R`) which I'm trying to convert to `golem`.

I don't know what to do with my current `global.R` file below.

```
# Various library calls, shouldn't be needed with `import` and `packagename::`
library(DBI)
library(pool)

# Pool creation and cleanup for DB access
pool_mysql <- dbPool(
    RMySQL::MySQL(),
    dbname = Sys.getenv("mysql_dbname"),
    host = Sys.getenv("mysql_host"),
    # port = Sys.getenv("mysql_port"),
    user = Sys.getenv("mysql_user"),
    password = Sys.getenv("mysql_password")
)

onStop(function() {
    cat("Doing application cleanup\n")
    cat("-----\n Removing connections\n")
    poolClose(pool_mysql)
})

# Various queries like

name <- dbGetQuery(pool_mysql, "SELECT DISTINCT name FROM users_profile")
all_names <- sort(unique(name$name))
```

The various queries are used in my `ui.R` file, simplified below

```
tagList(
    dashboardPage(
        dashboardHeader),
        dashboardSidebar(),
        dashboardBody(fluidRow(
            box(
                title = "Controls",
                width = 12,
                selectInput(
                    inputId = "name",
                    label = "name",
                    choices =  all_names,
                    selected = 'name1',
                    multiple = TRUE,
                    selectize = TRUE
                )
            )
        ),
        fluidRow(box(
            width = 12, plotOutput("plot1")
        )))
    ))
```

I run into scoping issues because my ui needs the queries to have run and the connection to already exists.

I tried to `source("global.R")` in my `app_server.R` but the `app_ui.R` is called first so it doesn't work.
I also tried to modify `run_app.R` by adding
```
app = shinyApp(ui = app_ui, server = app_server, onStart = source("global.R", local = TRUE))
```
but it didn't work either. I was placing `global.R` in the `inst` folder, which may be wrong.

I read your various blogposts and the *workflow book* but I still don't know how to solve this problem. I'm far from a `Shiny` expert so I'm probably missing something obvious but I would greatly appreciate any help because I would really like to continue using `golem`.

Thanks, have a nice day :+1:

**Comment by VincentGuyader** [comment]
Hi, 

If you want a quick and dirty way, put your global.r in your `inst` folder and use 


run_app <- function(...) {
source(system.file("global.R",package = "mygolem"))
  with_golem_options(
    app = shinyApp(ui = app_ui, server = app_server), 
    golem_opts = list(...)
  )
}


But in your case It could be better to use golem_opts .

Regards

**Comment by jerome-laurent-pro** [comment]
Thank you, it works perfectly.

When I have more time, I'll try to use `golem_opts` to build something clean.

**Comment by mohitsahasrabudhe** [comment]
Did you get time to add global.R to golem_opts

**Comment by ColinFay** [comment]
@mohitsahasrabudhe there is no such plan as integrating globals.R in golem_opts :)

Here is the methodology for integrating what you've got in globals.R inside your golem app:

- all the datasets that are fixed should be added as a package dataset 
- functions should be integrated as package functions 
- things that need to be launched at runtime should be listed in the app_server function

You can also use golem_opts for things needed at runtime, to have something like run_app(param = this). 

Best, 
Colin

**Comment by mohitsahasrabudhe** [comment]
Thanks.

**Comment by soetang** [comment]
An alternative would be to create a global.r file in your R directory and in that global file you create a quote:

global <- quote({
# your global code
})

Then you can change the run_app code to:
run_app <- function(...) {
  golem::with_golem_options(
    app = shinyApp(
      ui = app_ui
      , server = app_server
      , onStart = purrr::partial(eval, expr = global, envir = globalenv())), 
    golem_opts = list(...)
  )
}
This is pretty similar to how shiny reads you global file in a non-golem situation. See the onstart function here: https://github.com/rstudio/shiny/blob/e84beffee39d540d3e891faafb9f333af32deca4/R/app.R

**Comment by dwhdai** [comment]
If you guys are still interested in this, this vignette was helpful in demonstrating how with_golem_options() can be used for both your UI and server modules.

https://cran.r-project.org/web/packages/golem/vignettes/c_deploy.html

**Comment by ShinyFabio** [comment]
Hi and what about `{cicerone}` package? Look at the usage from the github page [https://github.com/JohnCoene/cicerone](url). The package in order to work need some code outside ui and server. Where I can put this code?

**Comment by ColinFay** [comment]
@ShinyFabio 

There is no reason for cicerone to be defined outside of the ui and server, you can define the guide inside the server or inside the module as in https://github.com/ColinFay/hexmake/blob/master/R/mod_guided_tour.R#L40 or, to refactor the example from cicerone vignette : 

```r
library(shiny)
library(cicerone)

ui <- fluidPage(
  use_cicerone(), # include dependencies
  textInput("text_inputId", "Enter some text"),
  actionButton("submit_inputId", "Submit text"),
  verbatimTextOutput("print")
)

server <- function(input, output){
  
  Cicerone$
    new()$ 
    step(
      el = "text_inputId",
      title = "Text Input",
      description = "This is where you enter the text you want to print."
    )$
    step(
      "submit_inputId",
      "Send the Text",
      "Send the text to the server for printing"
    )$init()$start()
  
  
  txt <- eventReactive(input$submit_inputId, {
    input$text_inputId
  })
  
  output$print <- renderPrint(txt())
}

shinyApp(ui, server)
```

You can also functionalize it inside an `fct_cicerone.R` like, with something like : 

```r
library(shiny)
library(cicerone)

# This would be in another R file
gen_guide <- function(){
  Cicerone$
    new()$ 
    step(
      el = "text_inputId",
      title = "Text Input",
      description = "This is where you enter the text you want to print."
    )$
    step(
      "submit_inputId",
      "Send the Text",
      "Send the text to the server for printing"
    )
}

ui <- fluidPage(
  use_cicerone(), # include dependencies
  textInput("text_inputId", "Enter some text"),
  actionButton("submit_inputId", "Submit text"),
  verbatimTextOutput("print")
)

server <- function(input, output){
  
  gen_guide()$init()$start()
  
  txt <- eventReactive(input$submit_inputId, {
    input$text_inputId
  })
  
  output$print <- renderPrint(txt())
}

shinyApp(ui, server)
```

Cheers, 
Colin

**Comment by ShinyFabio** [comment]
Cool! I like the idea to make another function. In the "fct_cicerone.R" file, do I need only this part?

```
# This would be in another R file
gen_guide <- function(){
  Cicerone$
    new()$ 
    step(
      el = "text_inputId",
      title = "Text Input",
      description = "This is where you enter the text you want to print."
    )$
    step(
      "submit_inputId",
      "Send the Text",
      "Send the text to the server for printing"
    )
}
```

Or do I need to put everything together? (I mean ui, server and the `gen_guide` function inside a new script).
