### ISSUE TITLE
Propose unit tests with golem_utils_ui

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/golem#625]
https://github.com/ThinkR-open/golem/blob/aaae5c8788802a7b4aef4df23691902a286dd964/inst/utils/golem_utils_ui.R

Starting with: 
```r
test_that("with_red_star works", {
  expect_equal(as.character(with_red_star("Enter your name here")), 
               '<span>Enter your name here<span style="color:red">*</span></span>')

})

test_that("list_to_li works", {
  expect_equal(as.character(list_to_li(c("a","b"))), "<li>a</li>\n<li>b</li>")
})

```

**Comment by ColinFay** [comment]
I wonder if these should live inside `{golem}` or inside the built app 🤔 

There are few chances these utils will be changed by the dev, so I think we could test them at `{golem}` level.

**Comment by VincentGuyader** [comment]
I think we need to put unit unit testing in both {golem} and in user's golem.

If user add, and use this functions they should be tested

**Comment by ColinFay** [comment]
We should also do that at the module level.

**Comment by ArthurData** [comment]
I'm in 😄
