### ISSUE TITLE
Add more info on package creation

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#63]
Not just the cat_rule("created")

**Comment by novica** [comment]
How about line 74-75 in `create-golem.R`:

```
cat_rule(paste0("A new golem package ", package_name, " was created."))
cat_rule("To continue work on your package start editing the 01_start.R file")
```

**Comment by ColinFay** [comment]
Mmh, I think we should go for a simple `cat_line` here instead of printed three lines. 

Also, I think the folder where the app was created would be nice :)

**Comment by novica** [comment]
If I understood correctly, this is it: https://github.com/novica/golem/commit/cc7f24ff469bb43258c7ca83bb34c164013aea70

**Comment by ColinFay** [comment]
Perfect, thanks!
