### ISSUE TITLE
Warning w/ add_js_file

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#65]
``` 
> golem:: add_js_file( "script" )
✔ File created at ././inst/app/www/script.js
Warning message:
In dir.create(dir, recursive = TRUE) : './inst/app/www' already exists
```

**Comment by Cervangirard** [comment]
showWarnings = FALSE ? or we need more ?

**Comment by ColinFay** [comment]
Mmh, I think the best way we could do this is setwd() into www and create the file and setwd() to old on exit

just like https://github.com/ThinkR-open/golem/blob/master/R/use_utils.R#L29

**Comment by ColinFay** [comment]
Still there if creating file and dir already exists
