### ISSUE TITLE
Remove "_ui_" in modules names

### ISSUE THREAD

**Issue by MargotBr** [ThinkR-open/golem#651]
The module has been created with `golem::add_module(name = "tab_couple")`, but it is then renamed `"tab_couple_ui_1"` everywhere : 

<img width="315" alt="Capture d’écran 2021-04-17 à 15 18 07" src="https://user-images.githubusercontent.com/20540890/115253679-e5be0280-a12c-11eb-8ab3-40181077754d.png">

**Comment by ColinFay** [comment]
closed via #652
