### ISSUE TITLE
Add parameteres 'speed' & 'callback' in invoke_js("show/hide")?

### ISSUE THREAD

**Issue by shahreyar-abeer** [ThinkR-open/golem#676]
Can we add parameters 'show' and 'callback' in the show/hide functions that comes with golem::activate_js()?

**Comment by ColinFay** [comment]
Hey, 

Thanks for the idea.

The JS functions will be deprecated in favor of `{shinyjs}` (which is now MIT), as described in #503, so I don't think I'll be working on updating these :)

Cheers, 
Colin
