### ISSUE TITLE
How to include/associate a python virtual environment in/with a golem app (with reticulate)

### ISSUE THREAD

**Issue by fBedecarrats** [ThinkR-open/golem#677]
Hello and many thanks for this wonderful framework.
I am building a shiny application with golem that runs a python forecasting model on the server side.What would be an appropriate way to include the python virtual environment and call it with reticulate::use_virtualenv() ?

**Comment by ColinFay** [comment]
hey @fBedecarrats, 

I was about to move this one to the Discussion panel, thanks for opening the Discussion topic :) 

I'll close this issue right now, and will try to answer this question in a few. 

Thanks, 
Colin
