### ISSUE TITLE
Struggling with paths in HTML template

### ISSUE THREAD

**Issue by etiennebacher** [ThinkR-open/golem#692]
Hello, I don't know if this is the right place to ask this question so sorry in advance if it is not the case.

I want to use an HTML template in a `golem` framework. I must be missing something in the way paths work in the html file. Basically, the template looks like this:
```
<!DOCTYPE html>
<html lang="en-US" dir="ltr">
  <head>
    <link href="assets/css/style.css" rel="stylesheet">
  </head>
  <body>
    <main>
      
      <!-- DOESN'T WORK (image not displayed) -->
      <section class="home-section home-full-height" id="home" data-background="assets/tennis_image.jpg">
        
      <!-- WORKS (may need a few seconds to load) -->
      <!-- <section class="home-section home-full-height" id="home" data-background="https://upload.wikimedia.org/wikipedia/commons/9/91/Wimbledon_2019_Nadal_v_Sousa.jpg"> -->
      
        <div class="titan-caption">
          <div class="caption-content">
            <div class="font-alt mb-30 titan-title-size-1">{{title}}</div>
          </div>
        </div>
    </main>
  </body>
</html>
```
As you can see from the comments, when I put the exact URL for the image I want to display in the background, it is displayed correctly. However, if I store this image in `assets` folder (see the folder structure below), it is not displayed anymore. It seems like the path is not recognized. The strange thing is that the CSS provided with the template is called with the same kind of path (`"assets/css/style.css"`) and it is correctly applied, so I wonder why the CSS path works but not the image path.

Do you know why this is the case, and how to solve it? This is likely related to the use of `golem`. In a more "classic" app (with only a `www` subfolder), the image is correctly displayed.

I have put the full app example on this repo: https://github.com/etiennebacher/test_titan_golem 

<details>
<summary> Click to see the folder structure </summary>
<pre>
.
├── DESCRIPTION
├── NAMESPACE
├── R
│   ├── app_config.R
│   ├── app_server.R
│   ├── app_ui.R
│   └── run_app.R
├── dev
│   ├── 01_start.R
│   ├── 02_dev.R
│   ├── 03_deploy.R
│   └── run_dev.R
├── inst
│   ├── app
│   │   └── www
│   │       ├── assets
│   │       │   ├── css
│   │       │   │   └── style.css
│   │       │   ├── js
│   │       │   │   ├── main.js
│   │       │   │   └── plugins.js
│   │       │   ├── lib
│   │       │   │   └── wow
│   │       │   │       └── dist
│   │       │   │           └── wow.js
│   │       │   └── tennis_image.jpg
│   │       ├── favicon.ico
│   │       └── index.html
│   └── golem-config.yml
├── man
│   └── run_app.Rd
└── test_titan_golem.Rproj
</pre>
</details>

**Comment by ColinFay** [comment]
Hey, 

If you want your UI to have access to resources on `assets`, you’ll need to declare the resource path using `add_resource_path("assets", app_sys("app/www/assets")`, just as we automatically link `www` here https://github.com/etiennebacher/test_titan_golem/blob/master/R/app_ui.R#L29. 

Then it will be available on `assets`. 

Also, as your assets is inside www, you can also link to it on www/assets instead. 

Cheers, 
Colin

**Comment by etiennebacher** [comment]
Thanks Colin, it works, but I don't understand why the CSS (in `assets/css`) was loading but not the image (in `assets`) before I add `add_resource_path`

**Comment by ColinFay** [comment]
golem::bundle_resources() does some magic under the hood and will link all the css and js from app/www, even the sub folders, but not the images ;)
