### ISSUE TITLE
Run code only if shinydashboard tab is clicked

### ISSUE THREAD

**Issue by henrique1008** [ThinkR-open/golem#696]
I'm building a shiny with golem, using shinydashboard , and it has a lot of tabs

I have date pickers on all the tabs so when shiny to be loaded, I do sql queries on databases to get the available dates of data and set the range on the date pickers

but this is slow because when shiny is loaded, it queries all tabs at once

I would like tab queries to be done only if the tab was clicked and opened

I got this code example below, where tab2 only loads the function that plots the graph if it is clicked

But inside the golem, I couldn't use the input$sidebarmenu, because I couldn't identify it inside the inputs

Thank you very much in advance
Bests

```
library(shiny)
library(shinydashboard)

ui = dashboardPage(
  dashboardHeader(title =  "Dashboard"),
  dashboardSidebar(
    sidebarMenu(
      id = "sidebarmenu",
      menuItem("menuItem1", tabName = "tab1"),
      menuItem("menuItem2", tabName = "tab2")
    )
  ),
  dashboardBody(
    tabItems(
      tabItem(tabName = "tab1",
              tableOutput("myTable")),
      tabItem(tabName = "tab2",
              plotOutput("myPlot"))
    )
  )
)

server <- function(input, output, session) {
  
  tableData = reactiveVal(data.frame(x = 1:10, y = LETTERS[1:10]))
  plotData = reactiveVal()

  observeEvent(input$sidebarmenu, {

    if(input$sidebarmenu == "tab2"){
      #Code for tab 2
      req(is.null(plotData()))
      print("Tab 2 code is run")
      plotData(runif(100))

    }

  })

  output$myTable = renderTable({
    tableData()
  })

  output$myPlot = renderPlot({
    plot(plotData())
  })
}

shinyApp(ui, server)
```

The example below also reflects something similar to what I want, detect the tab that is active and run your code, but I tried to implement similar and it didn't work.
https://stackoverflow.com/questions/53049659/loading-shiny-module-only-when-menu-items-is-clicked

**Comment by henrique1008** [comment]
I found the solution, sorry I created the Issue without much need, but I really had a hard time understanding it, although it seems very simple now

https://rstudio.github.io/shinydashboard/behavior.html

Looking at the documentation I understood that inside shinydashboard::sidebarMenu() , there was an id parameter, where I should specify something, in this case I put the id as "tabs"

So, now inside app_server.R, where I paste the server functions that are in the modules, and there is already a text to copy and paste very conveniently in Golem, thank you very much for that including, I do the following

```
  shiny::observeEvent(input$tabs,{
    if(input$tabs == 'mytab'){
      Server of my module
    }
  })
```

**Comment by RobWiederstein** [comment]
Thanks for asking this question.  The problem seemed like a scoping issue because I felt confident in the syntax of the code.  I was exploring namespace and module-within-a-module solutions and ran across your question.   The solution was to cut and paste the code into 'app_server.R' file and it worked like a charm. Thank you!
