### ISSUE TITLE
expect_running filepath does not resolve to R

### ISSUE THREAD

**Issue by waiteb5** [ThinkR-open/golem#699]
golem::expect_running fails due to bad R path generation. Adding 'bin' to path corrects the command and function works.

Tested on:
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

> normalizePath(file.path(Sys.getenv("R_HOME"),'R'))
[1] "/opt/R/4.1.0/lib/R/R"
Warning message:
In normalizePath(file.path(Sys.getenv("R_HOME"), "R")) :
  path[1]="/opt/R/4.1.0/lib/R/R": No such file or directory
> normalizePath(file.path(Sys.getenv("R_HOME"),'bin','R'))
[1] "/opt/R/4.1.0/lib/R/bin/R"

Tested on:
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Manjaro Linux

> normalizePath(file.path(Sys.getenv("R_HOME"),'R'))
[1] "/usr/lib64/R/R"
Warning message:
In normalizePath(file.path(Sys.getenv("R_HOME"), "R")) :
  path[1]="/usr/lib64/R/R": No such file or directory
> normalizePath(file.path(Sys.getenv("R_HOME"),'bin','R'))
[1] "/usr/bin/R"

**Comment by ColinFay** [comment]
Solved in #700
