### ISSUE TITLE
Package not added to `DESCRIPTION` file when using `importFrom`

### ISSUE THREAD

**Issue by isaactpetersen** [ThinkR-open/golem#704]
I'm experiencing an issue when with a Shiny app built in the `{golem}` framework while using package management with `{renv}`. The issue is that packages I've specified as `importFrom` do not get added to the `DESCRIPTION` file, and therefore do not get added to the `{renv}` lock file (https://github.com/rstudio/renv/issues/806). This occurs even though the packages are specified successfully in the `NAMESPACE` file.

As noted [here](https://r-pkgs.org/namespace.html?#imports), "It’s common for packages to be listed in `Imports` in `DESCRIPTION`, but not in `NAMESPACE`. In fact, this is what I [Hadley] recommend: list the package in `DESCRIPTION` so that it’s installed, then always refer to it explicitly with `pkg::fun()`. Unless there is a strong reason not to, it’s better to be explicit. It’s a little more work to write, but a lot easier to read when you come back to the code in the future. The converse is not true. Every package mentioned in `NAMESPACE` must also be present in the `Imports` or `Depends` fields." However, in my case, the packages are listed in `NAMESPACE` but not in the `DESCRIPTION` file. Is there a `{golem}` function that updates the `DESCRIPTION` file with all of the packages that are specified as `importFrom`?

Each package is listed using `importFrom` in one of the R scripts in the package repository:

```
#' @importFrom dplyr %>%
#' @importFrom lubridate interval
```

And they are included in my NAMESPACE file:

```
importFrom(dplyr,"%>%")
importFrom(lubridate,interval)
```

**Comment by ColinFay** [comment]
Hey, 

The packages are not automatically added to the DESCRIPTION file by the tools used. Under the hood, `{golem}` calls `roxygen2::roxygenize()`, which does not adds to the `DESCRIPTION`. 

To do what you're looking for, you need to call `usethis::use_package("dplyr")`, as defined in the `dev/02_dev.R` file: https://github.com/ThinkR-open/golem/blob/master/inst/shinyexample/dev/02_dev.R#L18

Note that this is not related to `{golem}` but to the way documentation is generated in R :)

You can also try `attachment::att_amend_desc()` to try and guess the dependencies in your project :) 

Cheers, 
Colin

**Comment by ColinFay** [comment]
Closing, I think it's solved. 

Feel free to comment if you want this to be reopen. 

Cheers, 
Colin
