### ISSUE TITLE
Docker Timeout

### ISSUE THREAD

**Issue by em-dataIntegrityEnthusiast** [ThinkR-open/golem#706]
My application is greying out shortly after loading in a docker environment. Upon inspection I did see that there were some websocket errors. I saw a comment on SO about external javascript packages causing this sometimes. Has anyone else dealt with this or have any recommendations for how to proceed with debugging it? Docker is a new tool for me and I appreciate any tips!

Error logs that lead me to thinking it was a websocket issue:
shinyapp.js:288 Uncaught TypeError: Cannot read property 'readyState' of null
    at ShinyApp.$sendMsg (shinyapp.js:288)
    at ShinyApp.sendInput (shinyapp.js:140)
    at InputBatchSender.$sendNow (input_rate.js:220)

shinyapp.js:83 WebSocket connection to [server] failed

**Comment by ColinFay** [comment]
Hey, 

1. Are you using the default docker image generated by `{golem}`, or are you creating a custom one? 
2. Any chance you could share a repo with the project and the Dockerfile? 

Cheers, 
Colin

**Comment by ColinFay** [comment]
Closing for lack of further information on the issue :) 

Feel free to comment if you still have this bug and I'll reopen.
