### ISSUE TITLE
`golem::document_and_reload()` fails

### ISSUE THREAD

**Issue by earnaud** [ThinkR-open/golem#716]
When launching `golem::document_and_reload()`, I get 
```
Error in if (grepl(package_name, where_system.file)) { : 
  argument is of length zero 
```
I used to invoke `golem::document_and_reload()` without having `app_config.R` file but an update seems to have made it mandatory. 
My app_config.R file is (found [here](https://cran.r-project.org/web/packages/golem/vignettes/e_config.html) ) :
```
pkgload::load_all()
get_golem_config(
  "where"
)
get_golem_config(
  "where", 
  config = "production"
)
```

**Comment by ColinFay** [comment]
Hey, 

This is not what your app_config.R file should look like, it should be https://github.com/ThinkR-open/golem/blob/master/inst/shinyexample/R/app_config.R, where `shinyexample` is the name of your package. 

Can you try updating your file and let me know?

**Comment by earnaud** [comment]
Hi,

I am getting this now:
```r
Warning message:
In readLines(con) :
  incomplete final line found on '/home/pndb-elie/Softwares/Gits/MetaShARK-v2/inst/golem-config.yml'
 ```
Here are my files:
**golem-conig.yml**
```yaml
default:
  golem_name: MetaShARK
  golem_version: 1.6.1
  app_prod: no
  
production:
  app_prod: yes
  
dev:
  golem_wd: !expr here::here()
```
**app-config.R**
```r
app_sys <- function(...){
  system.file(..., package = "MetaShARK")
}

get_golem_config <- function(
  value, 
  config = Sys.getenv(
    "GOLEM_CONFIG_ACTIVE", 
    Sys.getenv(
      "R_CONFIG_ACTIVE", 
      "default"
    )
  ), 
  use_parent = TRUE
){
  config::get(
    value = value, 
    config = config, 
    # Modify this if your config file is somewhere else:
    file = app_sys("golem-config.yml"), 
    use_parent = use_parent
  )
}
```

**Comment by ColinFay** [comment]
Can you add an empty line at the end of your yaml? (just got to the last line and press Enter :) )

**Comment by earnaud** [comment]
Oh, I tried by typing "\n" and it did not work, but it wrote a line as "\n\t". Removing the "\t" did it. 

Thanks !

**Comment by ColinFay** [comment]
Great! 

Thanks for using `{golem}` :) 

Cheers, 
Colin
