### ISSUE TITLE
Passing reactive object as additional argument to several golem modules

### ISSUE THREAD

**Issue by agronomofiorentini** [ThinkR-open/golem#730]
Hi ThinkR,
Thank you for the development of this amazing package which I always use when I am faced with the development of a very large web application.
I would like to pass to several golem module an additional argument which is the reactive object of check_credentials of shiny manager to:
1.	To call only the user data.
2.	To activate or deactivate based on the type of user

This is the way that i am operating right now, but finding many problems.

UI part

`app_ui<-shinymanager::secure_app(app_ui, status="primary")`

Server Part

`res_auth <- secure_server(check_credentials = check_credentials(credentials))
  auth_output<- reactive({
    reactiveValuesToList(res_auth)})`

Module Server
`mod_golem_User("golem_ui_1", res_auth)`

Then when i am calling the res_auth() in the golem module it is as if it did not exist

**Comment by agronomofiorentini** [comment]
also I found another issue and I apologize for that.

When i create the docker image, all it is working perfectly, with the follow Dockerfile

But when i try to run the follow code

`docker run ciaone`

It turns back the follow error

![Screenshot_1](https://user-images.githubusercontent.com/66969646/134774987-2d80af7f-029b-436e-b552-2780c6a89060.jpg)

Infact the Golem R-project is called ReportSatellite.

How can i surpass these problems?

Thanks

**Comment by VincentGuyader** [comment]
Hi, 

can you share your Dockerfile ?

Regards

**Comment by agronomofiorentini** [comment]
Hi, of course and thanks to help me.

![Screenshot_3](https://user-images.githubusercontent.com/66969646/134776588-9e0350ea-86fc-4682-8c52-26e2fd284022.jpg)

**Comment by VincentGuyader** [comment]
can you duplicate the row with remote::install_local ( to hack cache system )

like this : 

(...)
WORKDIR /build_zone
RUN R -e 'remotes::install_local(upgrade="never")'
RUN R -e 'remotes::install_local(upgrade="never")'
RUN rm -rf /build_zone
(...)
then you have do to this : 

```
cd ../path/to/ReportSatellite   (the Dockerfile need to be in this folder)

docker build -t ciaone .
docker run

```
Then me the log if it doesnt work.

Regards

**Comment by agronomofiorentini** [comment]
Hi @VincentGuyader,
I did what you mentioned before, but i have got the same error output.

It seems that the The R-golem package "ReportSatellite" doesn't exist.

This is the error output

> Error in loadNamespace(name) :
  there is no package called ‘ReportSatellite’
Calls: :: ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted

**Comment by ColinFay** [comment]
Hey, 

These two issues seems to be unrelated :) 
Please open one issue by topic so that we can keep track of everything 🤘

Can you please move the Docker related issue to [`{dockerfiler}`](https://github.com/ColinFay/dockerfiler/issues/new) please ? This is where all the docker related elements are now stored :) 

The original post being a question, I'll convert this issue to a Discussion :) 

Thanks for using `{golem}`! 

Cheers, 
Colin
