### ISSUE TITLE
When adding tests & fct/utils to module, check that the module exists

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#735]
`add_fct`, `add_utils` and `use_module_test` can be linked to a specific module. 

But right now, there is no check that this module actually exists. 

These functions should do a check to be sure they exist. 

```r
> list.files("R", pattern = "mod")
[1] "mod_page1.R" "mod_page2.R" "mod_page3.R" "mod_plop.R" 

# This should be doable
> golem::add_fct("xyz", module = "xyz")
✔ File created at R/mod_xyz_fct_xyz.R
```

**Comment by ALanguillaume** [comment]
Count me in !
