### ISSUE TITLE
Best practices for including dependencies?

### ISSUE THREAD

**Issue by yogat3ch** [ThinkR-open/golem#738]
Hi golem devs,
I've been using golem since Colin Fay presented at Javascript for Shiny Devs at rstudio::conf(2020) and somehow I've managed to avoid a situation where dependencies just don't appear to be loading with the app and I'm not sure how. 

We have a `golem` app that's using [`tippy`](https://github.com/JohnCoene/tippy) and [`cicerone`](https://github.com/JohnCoene/cicerone), both of which have associated dependencies.

We attempt to include these dependencies inside the `golem_add_external_resources` function with `mod_theme_ui`:

```
golem_add_external_resources <- function(){
  
  golem::add_resource_path(
    'www', app_sys('app/www')
  )
 
  tags$head(
    mod_theme_ui("theme"),
    golem::favicon(),
    golem::bundle_resources(
      path = app_sys('app/www'),
      app_title = 'crsspierViz'
    )
    # Add here other external resources
    # for example, you can add shinyalert::useShinyalert() 
  )
}
```

_mod_theme_ui_ is pretty straightforward:
```
mod_theme_ui <- function(id){
  ns <- shiny::NS(id)
  shiny::tagList(
    cicerone::use_cicerone(),
    tippy::useTippy(),
    tippy::tippyTheme("tip_theme",
                      box_bg = crssp_theme$bg,
                      box_color = crssp_theme$primary,
                      content_bg = crssp_theme$bg,
                      content_color = crssp_theme$`text-color`
    )
  )
}
```

The `use*` functions employ the `shiny::htmlDependency` function to add their dependencies. Here's the body of `use_cicerone` for example:
```
htmlDependency("cicerone", version = utils::packageVersion("cicerone"), 
    package = "cicerone", src = "packer", script = "cicerone.js")
```

While `tippyTheme` uses a bit more contrived method:
```
 if (missing(name)) 
    stop("Missing `name`")
  theme <- sprintf(".tippy-box[data-theme~='%s'] {\n\t\t\tbackground-color: %s;\n\t\t\tcolor: %s;\n\t\t\tfont-size: %s;\n\t\t}\n\t\t.tippy-box[data-theme~='%s'] > .tippy-arrow {\n\t\t\tcolor: %s;\n\t\t} \n\t\t.tippy-box[data-theme~='%s'] > .tippy-content {\n\t\t\tbackground-color: %s;\n\t\t\tcolor: %s;\n\t\t\tfont-size: %s;\n\t\t}", 
    name, box_bg, box_color, box_font_size, name, arrow_color, 
    name, content_bg, content_color, content_font_size)
  tags$head(HTML(sprintf("<style>%s</style>", theme)))
```

Unfortunately, it appears that none of these dependencies are loading using this method. The reason I think they're not loading is there doesn't appear to be any scripts included by the names indicated in the `use*` functions, and if I search the source for `tippy` or `cicerone` I return 0 matches. I've attempted to move the calls in `mod_theme_ui` directly into the `tags$head` in `golem_add_external_resources` but they still don't appear to be loading.

My questions are as follows:
1. What's the best practice for including dependencies such that they work properly?
2. Is there an issue with including these dependencies in a `tagList` inside `mod_theme_ui` and then plugging them in to `golem_add_external_resources` like we currently have it?
3. Could the `tippyTheme` method be creating a `head` tag nested inside the `head` tag with our current setup?

Any advice will be appreciated,
Stephen

**Comment by yogat3ch** [comment]
Hmm, nevermind - it looks like the dependencies are there now!

**Comment by rpodcast** [comment]
I am trying to use `cicerone` and `tippy` in a Shiny app produced with `golem` as well. Did you have to change anything in your code to make this work?

**Comment by ColinFay** [comment]
@rpodcast I use `{cicerone}` in `{hexmake}`, here is how to include it : https://github.com/ColinFay/hexmake/blob/master/R/app_ui.R#L36 :)
