### ISSUE TITLE
Dockerfile should be buildignored

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#81]
`golem::add_dockerfile` should add Dockerfile to the buildignore (heroku and shinyproxy already do

**Comment by statnmap** [comment]
Path should be relative, not absolute in .Rbuildignore

**Comment by ColinFay** [comment]
`{usethis}` does that part, we need to see if this can be handled there 
https://github.com/ThinkR-open/golem/blob/master/R/add_deploy_helpers.R#L185

**Comment by statnmap** [comment]
The problem seems to be the `where <- file.path(pkg, output)`. `pkg` should not be included for this case?  
https://github.com/ThinkR-open/golem/blob/master/R/add_deploy_helpers.R#L182
