### ISSUE TITLE
Add documentation about loading packages

### ISSUE THREAD

**Issue by ethantenison** [ThinkR-open/golem#818]
This is my first time using golem and making an R package, and the way you call other packages is very different. 

In the documentation it lists `usethis::use_package("your package")` to add dependencies, but that doesn't seem to be enough. I can't use functions like `read_csv` for example without calling `library(readr)`, despite adding it as a dependency. Otherwise I get the error, 

>   Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
>   there is no package called ‘readr,

None of the documentation shows using `library`, so I know I'm doing something wrong. Perhaps adding a little more documentation about how calling other packages is different in package development would help newbies like myself.

**Comment by ALanguillaume** [comment]
Hi Ethan,

Golem brings Shiny to the world of R packages assuming your are familiar with the matter.
Let me file you in about the quirks of R packages dependencies management.

`usethis::use_package("readr")` will only add `readr` to the DESCRIPTION file.
This will only insure that `readr` is installed alongside your package or golem app. However this does not mean that the functions of `readr` are readily accessible when you run your golem app as you found out !
More info here: https://r-pkgs.org/description.html#description-dependencies

To also guarantee that the functions of `readr` are available within your golem app/package you must tell R to put them in the NAMESPACE of your app. To do so the best practice is to include @importFrom tags in the documentation of your function. A quick example below:

```r
#' Reads the main dataset for the app
#' 
#' Reads in the dataset at the core of my golem app form a csv file.
#' 
#' @param file A character string indicating the path to the csv file.
#' 
#' @return A tibble with x and y columns...
#' 
#' @importFrom readr read_csv
#' 
#' @examples 
#' data_app <- read_data_app()
read_data_app <- function(file) {
  raw_data_app <- read_csv(
    file = file,
    show_col_types = FALSE
  )
  # Then you might wanna do some basics processing here...
  # and then return the data ready to be used within your golem app.
  return(data_app)
} 
```
More info here: https://r-pkgs.org/namespace.html#namespace

If you want to learn more about packages I also suggest you have a look at those slides form @statnmap 
https://statnmap.github.io/user2021.rmdd/stagiaire_complet.html#1
