### ISSUE TITLE
Add logo instructions to docs

### ISSUE THREAD

**Issue by jl5000** [ThinkR-open/golem#828]
It's not clear to me how to use the infrastructure to add a logo to the app. Please could you add an example to the docs?

**Comment by ColinFay** [comment]
Hey,

Are you referring to the favicon? 

Colin

**Comment by jl5000** [comment]
No, hex logo.

**Comment by ColinFay** [comment]
I'm really not sure what you are referring to, can you post a reprex / screenshot of what you're trying to do?

**Comment by jl5000** [comment]
I think it's just a case of showing an example of how to add a hex logo to a golem app using the existing infrastructure. Something like:


```
tags$head(
    favicon(),
    bundle_resources(
      path = app_sys('app/www'),
      app_title = 'package-name'
    ),
    div(img(src="www/logo.png", align="left"),
        style="margin-left: 10px"),
    
    # Add here other external resources
    # for example, you can add shinyalert::useShinyalert() 

  )
```

**Comment by ColinFay** [comment]
It's an old issue, and as of now you can refer to the documentation about including external resources here: https://engineering-shiny.org/golem.html?q=img#instappwww
