### ISSUE TITLE
R Shiny with golem application becoming grey after less than a minute

### ISSUE THREAD

**Issue by Jodavid** [ThinkR-open/golem#847]
Hello guys, I have an R Shiny with golem application that is running inside a docker container. On my local Windows machine, when I start the Docker container/image, the container/shiny App starts and stay up and running without becoming grey/dying off.

However, when deployed to a server, the container starts, and the App runs fine. The problem is: the application, when accessed via web interface, it becomes grey after less than one minute of inactivity. The container is up but it is the application that keeps becoming grey after less than a minute. When one refreshes the browser, the app comes back to life quickly.

Can anyone who understands this tell me what need to be done on the server or in config of golem? Or what I am missing in my container?

**Comment by ColinFay** [comment]
Hey,

do you run it via shiny server or using the standard Dockerfile created by golem?

**Comment by Jodavid** [comment]
Hi,

using the standard Dockerfile created by golem
