### ISSUE TITLE
Use {config}

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#85]
Just dropping the idea there, we should use the `{config}` package to set `golem options` (for example behaviour on app.prod) 

https://cran.r-project.org/web/packages/config/vignettes/introduction.html

**Comment by cderv** [comment]
Yeah ! FWIW I am in favor of this ! 👍

**Comment by ColinFay** [comment]
We should have a config.yml in inst/, and a function that is natively in the golem app called `get_golem_config()`

```r 
get_golem_config <- function(name, config = "default"){
  with_config(
    config, {
      config::get(
        name, 
        file = system.file(
          "config.yml", 
          package = "lpppa"
        )
      )
    }
  )
}

with_config <- function(config, expr){
  or_conf <- Sys.getenv("R_CONFIG_ACTIVE")
  on.exit({
    Sys.setenv(R_CONFIG_ACTIVE = or_conf)
  })
  Sys.setenv(R_CONFIG_ACTIVE = config)
  force(expr)
  
}
```

**Comment by cderv** [comment]
Why playing with the env var and not using the argument `config` in `config::get` ?? 

Also, why not depending only on how user configures there environment and use the same default as `config` 📦 . 

golem could just change the default path to find the file (in `inst`) ? 

All the rest would be the same as using {config} on its own.

**Comment by ColinFay** [comment]
Ok, just tried a few things and you're definitely right @cderv. 

So we should have sthg like `inst/golem-config.yml`

and something like `app_config.R` with in it

```r
app_sys <- function(...){
  system.file(..., package = "shinyexample")
}

#' @importFrom config get
golem_config <- function(
  value, 
  config = Sys.getenv("R_CONFIG_ACTIVE", "default"), 
  use_parent = TRUE
){
  get(
    value = value, 
    config = config, 
    file = app_sys("golem_config.yml"),
    use_parent = TRUE
  )
}
```

**Comment by ColinFay** [comment]
@cderv would you be willing to have a look to the new implementation with `{config}`? 

It's in the `dev` branch. Details are provided in the `config` Vignette.

Thanks :)

**Comment by cderv** [comment]
I'll do that this week end or next week. Thanks !

**Comment by VincentGuyader** [comment]
in the golem-config.yml i see : 

>dev:
  golem_wd: !expr here::here()

but no @import here anywhere and noting in DESCRIPTION

**Comment by VincentGuyader** [comment]
![image](https://user-images.githubusercontent.com/10470699/68990494-1cb32900-0854-11ea-961d-674316820e57.png)

**Comment by ColinFay** [comment]
It won't need to be @import as it is explicitely namespaced in the yaml, but indeed I forgot to push the update to DESCRIPTION.

**Comment by ColinFay** [comment]
pushed ✅
