### ISSUE TITLE
golem::add_partial_html_template()

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#858]
## Feature

Every time we add an htmltemplate with golem::add_html_template(), we have a full HTML page. We sometime need partial html template, with "just" a div and a `{{ }}`.

## TODO

+ [ ] Create a `add_partial_html_template()` that would build a partial HTML template with just a <div>
   + [ ] Inspired by `add_html_template()`
    + [ ] Only writes : 

```
<div>
  {{ content }}
</div>
```

**Comment by nathansquan** [comment]
Hi Colin,

I am happy to work on this issue.

**Comment by ColinFay** [comment]
@nathansquan great! Please do :) 

let me know if you need more information

**Comment by nathansquan** [comment]
Thanks @ColinFay 

Should there be a test for `add_partial_html_template()` and `add_html_template()`? I don't see a test for `add_html_template()` in `/tests/testthat/test-add_files.R`.

**Comment by ColinFay** [comment]
Yes, some part of the code are not covered so if you have some time to add tests that would be awesome 🤩
