### ISSUE TITLE
How to build a Shinymanager and Brochure app?

### ISSUE THREAD

**Issue by Jopgood** [ThinkR-open/golem#864]
Hi there,

I don't really have a repository to share as I am falling at the first hurdle sadly. I was wondering how to build an golem app that is both a Brochure and shinymanager one as I am hoping to create a login page for my app that leads to a menu page that can lead to multiple options of other pages. 

I have tried wrapping the first page UI with secure_app but nothing happens when I hit 'log in'. I'm not quite sure how to determine what page the auth page goes to after logging in.

Just looking for a starting point to go off!

Best,
James

**Comment by statnmap** [comment]
Colin, FYI, this question is cross-posted here: https://stackoverflow.com/questions/71997458/how-to-build-a-shinymanager-and-brochure-app-with-golem

**Comment by Jopgood** [comment]
> Colin, FYI, this question is cross-posted here: https://stackoverflow.com/questions/71997458/how-to-build-a-shinymanager-and-brochure-app-with-golem That's ok, I add the link to avoid answering twice 🙂

Hey statnmap,

Sorry, yes I should have mentioned, my apologies!

**Comment by ColinFay** [comment]
Hey @Jopgood, 

Yeah `{brochure}` won't work with `{shinyManager}`. A lot of the tools around `{shiny}` revolve (for a good reason) around the idea that `{shiny}` apps are single page apps, and `{brochure}` moves away from this limitation. 

I'll write an example of a login app soon and let you know. 

Cheers, 
Colin

**Comment by Jopgood** [comment]
Hi @ColinFay,

Ah I see! Yes, of course that makes sense. Originally, I had planned to design multiple apps that could link to each other via URLs but when I came across Golem/Brochure I thought it would be a quick and easy solution. That example login app would be incredibly appreciated thank you for that.

Best,
James
