### ISSUE TITLE
testthat package not included in namespace and giving check error

### ISSUE THREAD

**Issue by ncls33** [ThinkR-open/golem#866]
HI! I'm new to golem, so this is likely a mistake on my part, but checks pass fine before I add anything and when I add a module I get 
![image](https://user-images.githubusercontent.com/7446031/170049603-b54140ad-dcad-4583-ad22-99bd59e26370.png)

I re-run attachment::att_amend_desc() and added "#' @import testthat" on test files, but this doesn't help. Would you mind pointing me in the right direcion?

Thank you!

**Comment by VincentGuyader** [comment]
adding #' @import testthat is a good idea, but you need to launch `attachment::att_amend_desc()` next

**Comment by ncls33** [comment]
Hi, I had it installed but removed the library(testthat) call from the created file (changed it to import) and it works now. Thank you both and my apologies.

**Comment by ColinFay** [comment]
@ncls33 don't apologize, you're very much allowed to ask questions if something troubles you :) 

happy to hear your issue is solved !

Colin
