### ISSUE TITLE
How to manage R CMD check Note(s)

### ISSUE THREAD

**Issue by JohnStaples** [ThinkR-open/golem#867]
For variable names within a function I use ‘mpg’ <- NULL.
However, where within the golem framework should utils::globalVariables(‘mpg’) be called?
Thank you.

**Comment by VincentGuyader** [comment]
Hi

Yes you have to use globalVariables()

You will like this : 
https://github.com/ThinkR-open/checkhelper

**Comment by JohnStaples** [comment]
Thank you Vincent ..

**Comment by JohnStaples** [comment]
Hi Vincent
Many thanks for your reply; I thought you would have the problem covered ….
For your interest I am using ‘golem’ for ‘Swine Research & Epidemiology’ ; it is building into a very complex app. I have mastered using R6 & gargoyle for module communication.
Kind regards
John Staples. UK.
