### ISSUE TITLE
fill_desc pkg_name doesn't work

### ISSUE THREAD

**Issue by Cervangirard** [ThinkR-open/golem#88]
You can't change the name of your pkg with fill_desc, maybe we don't need the pkg_name parameter for fill_desc.

**Comment by ColinFay** [comment]
This should be handled there : https://github.com/ThinkR-open/golem/blob/master/R/desc.R#L33

**Comment by ColinFay** [comment]
Indeed, there's something forgotten here  https://github.com/ThinkR-open/golem/blob/master/R/desc.R#L33

Can you add this ?

```
desc$set(Package = pkg_title)
```

**Comment by ColinFay** [comment]
(sorry, closed by mistake)

**Comment by ColinFay** [comment]
good by now
