### ISSUE TITLE
Issue with .Deprecated() message for `golem::use_recommended_deps()`

### ISSUE THREAD

**Issue by dmenne** [ThinkR-open/golem#900]
Version 0.3.3.9000

```

Warning message:
'golem::use_recommended_deps' ist veraltet.
Benutzen Sie stattdessen 'golem::use_recommended_deps'
Siehe help("Deprecated") und help("use_recommended_deps() is soft deprecated and will be removed in future versions of {golem}.-deprecated").

**Comment by ColinFay** [comment]
Hey,

Can you give us more details about your issue here? 

Thanks, 
Colin

**Comment by dmenne** [comment]
Sounds like some circular reference to me:
Translation:
golem::use_recommended_deps is deprecated.
Please use
golem::use_recommended_deps instead.

**Comment by ColinFay** [comment]
Ah, indeed, thanks a lot :) (Sorry my German is not good enough).

Will correct that.

**Comment by ColinFay** [comment]
Close via #901
