### ISSUE TITLE
feat: remove {rstudioapi} hard desc

### ISSUE THREAD

**Issue by VincentGuyader** [ThinkR-open/golem#950]
to lower the number of packages to install to deploy à shiny app.

**Comment by ColinFay** [comment]
Duplicate of #940 :)

**Comment by ColinFay** [comment]
Some work already here : https://github.com/ThinkR-open/golem/commit/53b14d9817247abe0c4e7fa5ca6e489fdd1123da 

but it will be worth starting from a fresh clean branch :)
