### ISSUE TITLE
idea : make possible to init a git repository in project template

### ISSUE THREAD

**Issue by cderv** [ThinkR-open/golem#97]
I wonder if it would be possible to have a box in project template to init a git repository when creating a golem. 
It would be like in New RStudio Project template pane, with a checkbox for that. 

I guess it is related to the choice in #69 . 
Did you already tried ?

**Comment by ColinFay** [comment]
Two places where this needs to be implemented: 

+ create_golem, with a `with_git` param https://github.com/ThinkR-open/golem/blob/master/R/create_golem.R#L32

+ inside the RStudio project template https://github.com/ThinkR-open/golem/blob/master/inst/rstudio/templates/project/create_golem.dcf

**Comment by ColinFay** [comment]
Yes please do ! 

Thanks
