### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gabrielburcea** [ThinkR-open/golem#974]
**Cannot use the fonts with golem nor the FEATURE unit with the choice of libraries and their description **

I have tried to change: 

1. some paths - I have deleted fonts folder the original repo https://github.com/nz-stefan/cran-explorer. As you can see app/www has fonts
 2. see the change  my repository where golem framework is applied
https://github.com/gabrielburcea/cran_explorer_golem/tree/crngolem/crngolem
3. look in both bootstrap.min.css and themify.icons.css files - in the original repo posted above has src = "../fonts/etc" 4. 
4. I have tried in src = "../inst/app/www/etc" **YET IT DOES NOT WORK**

I am trying to reproduce this app: 
https://gallery.shinyapps.io/cran-explorer/?_ga=2.33355193.643983280.1673875561-1724596956.1673624821

But cannot get the expected output as above with the nice blue fonts and the patterns. 
This is what I get instead: 

<img width="1791" alt="Screenshot 2023-01-17 at 14 43 17" src="https://user-images.githubusercontent.com/34777178/212928607-09791ed7-427c-4d0e-817a-c4e03f3d15ca.png">

I add by GitHub repository link here so that you can see. I am not sure where the problem lies but please help if you can? 
https://github.com/gabrielburcea/cran_explorer_golem/tree/crngolem/crngolem

**Comment by ArthurData** [comment]
Hello @gabrielburcea, 

Sorry for the very long wait for a response on this issue too. 
Is this problem still true?

**Comment by ColinFay** [comment]
Old issue, closing
