### ISSUE TITLE
Package data is not exported in dockerized image

### ISSUE THREAD

**Issue by YonghuiDong** [ThinkR-open/golem#978]
**Describe the bug**

My golem app works well locally. But when I run the created a docker image, it pops up one warning: 

> Warning: Error in <reactive>: object 'cancerCell' not found

- The `cancerCell` is saved  in `data/cancerCell.rda`, and documented in `R/data.R`, which was prepared in an exact way as preparing an R package.

```r
#' Cancer cell line data
#'
#' This example data set is a data frame exported from Compound Discoverer software
#'
#' @format A data frame with 6 rows and 37 columns:
#' \describe{
#'   \item{Name}{Feature Name}
#'   \item{Area: EKVX_Lung_1p.raw (F6)}{Peak Area}
#'   \item{Area: EKVX_Lung_2p.raw (F9)}{Peak Area}
#'   \item{Area: EKVX_Lung_3p.raw (F16)}{Peak Area}
#'   \item{Area: EKVX_Lung_4p.raw (F20)}{Peak Area}
#'   \item{Area: EKVX_Lung_5p.raw (F29)}{Peak Area}
#'   \item{Area: EKVX_Lung_6p.raw (F36)}{Peak Area}
#' }
"cancerCell"
```
- In `Description` file, I made `LazyData: true`

- The package data was called in shinyapp like this:

```r
inputData <- reactive({
      if(showExample() == "Yes") {return(cancerCell)}
```

**To Reproduce**

I used the following script to run my app:

`docker run -p 80:80 mtreport:latest`

**Expected behavior**

The package data can be loaded by the shinyapp

**Screenshots**

The shinyapp page looks like this:

<img width="1000" alt="Screen Shot 2023-01-22 at 19 49 26" src="https://user-images.githubusercontent.com/22663189/213931669-5d10e42f-9f04-43f0-b3e1-1a508c576d78.png">

Could you please help to figure out the problem?

Thanks a lot.

Dong

**Comment by VincentGuyader** [comment]
90% of chance thaht the reason of the bug that the data are made available only after a real loading of the package.

can you try to tweak your CMD
from :

`CMD R -e "options('shiny.port'=80,shiny.host='0.0.0.0');mtreport::run_app()"`

to 

`CMD R -e "options('shiny.port'=80,shiny.host='0.0.0.0');library(mtreport);mtreport::run_app()"`


you can also replace all your `cancerCell` with `mtreport::cancerCell` in your app.


I think I will add the library in the CMD by default (in golem 4.0 :) )

**Comment by YonghuiDong** [comment]
Dear @VincentGuyader, Thanks a lot for your help. It works now!
