### ISSUE TITLE
in 01_start.R, move use_git up

### ISSUE THREAD

**Issue by cderv** [ThinkR-open/golem#98]
Why don't moving up `usethis::use_git()` ?

I does not matter a lot but `usethis::use_news_md( open = FALSE )` is just above 
https://github.com/ThinkR-open/golem/blob/6e7c1b312cdf33d36c8913eec5ac5c90cf3ed6b3/inst/shinyexample/dev/01_start.R#L34-L35

and give this message
```r
> usethis::use_news_md( open = FALSE )
✔ Writing 'NEWS.md'
Error: Cannot detect that project is already a Git repository.
Do you need to run `use_git()`?
```
At least, putting `use_git()` just before would prevent this message.

**Comment by ColinFay** [comment]
I think this is not an issue anymore, ` usethis::use_news_md( open = FALSE ) ` doesn't need git to work. Closing :)
