### ISSUE TITLE
in 01_start.R, give incitation to name DATASET

### ISSUE THREAD

**Issue by cderv** [ThinkR-open/golem#99]
```r
usethis::use_data_raw( open = FALSE )
```
will default to a name DATASET 

do you think it could be helpful to suggest to change the name of the dataset by

* indicating the default `usethis::use_data_raw( name = "DATASET", open = FALSE )`
* suggesting to change `usethis::use_data_raw( name = "my-dataset-name", open = FALSE )`

❓

**Comment by VincentGuyader** [comment]
hi, good idea. 

I dont like the capital letters name "DATASET.R" so maybe :

`usethis::use_data_raw( name = "my_dataset_name", open = FALSE )`

**Comment by cderv** [comment]
Thanks !
